# Generated by AccelFury IP Toolchain
FROM rust:1-bookworm

ENV DEBIAN_FRONTEND=noninteractive
ENV AF_OFFLINE=true
ENV PATH="/opt/af-python/bin:${PATH}"

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        pkg-config \
        git \
        curl \
        make \
        python3 \
        python3-pip \
        python3-venv \
        verilator \
        yosys; \
    if apt-cache show openfpgaloader >/dev/null 2>&1; then \
        apt-get install -y --no-install-recommends openfpgaloader; \
    fi; \
    if apt-cache show symbiyosys >/dev/null 2>&1; then \
        apt-get install -y --no-install-recommends symbiyosys; \
    fi; \
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    rustup component add rustfmt clippy; \
    python3 -m venv /opt/af-python; \
    /opt/af-python/bin/pip install --upgrade pip; \
    /opt/af-python/bin/pip install --no-cache-dir fusesoc litex

WORKDIR /work

CMD ["scripts/docker-smoke.sh"]
