# Generated by AccelFury IP Toolchain
FROM rust:1-slim-bookworm

ARG AF_INSTALL_LITEX=false
ARG AF_INSTALL_FULL_SMT_SOLVERS=true
ARG BITWUZLA_REF=0.8.2
ARG RUST_TOOLCHAIN=1.95.0-x86_64-unknown-linux-gnu

ENV DEBIAN_FRONTEND=noninteractive
ENV AF_OFFLINE=true
ENV PATH="/opt/af-python/bin:${PATH}"

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        pkg-config \
        git \
        curl \
        libxml2-utils \
        make \
        python3 \
        python3-pip \
        python3-venv \
        verilator \
        yosys; \
    if apt-cache show openfpgaloader >/dev/null 2>&1; then \
        apt-get install -y --no-install-recommends openfpgaloader; \
    fi; \
    if apt-cache show symbiyosys >/dev/null 2>&1; then \
        apt-get install -y --no-install-recommends symbiyosys; \
    fi; \
    rm -rf /var/lib/apt/lists/*

COPY scripts/install-smt-solvers.sh /usr/local/bin/af-install-smt-solvers

RUN set -eux; \
    chmod 0755 /usr/local/bin/af-install-smt-solvers; \
    if [ "${AF_INSTALL_FULL_SMT_SOLVERS}" = "true" ]; then \
        /usr/local/bin/af-install-smt-solvers --yes --with-yices-binary --with-bitwuzla-source --bitwuzla-ref "${BITWUZLA_REF}"; \
    else \
        /usr/local/bin/af-install-smt-solvers --yes --allow-missing; \
    fi; \
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    python3 -m venv /opt/af-python; \
    /opt/af-python/bin/pip --default-timeout=120 --retries 10 install --no-cache-dir edalize fusesoc; \
    if [ "${AF_INSTALL_LITEX}" = "true" ]; then \
        /opt/af-python/bin/pip --default-timeout=120 --retries 10 install --no-cache-dir litex; \
    else \
        echo "Skipping optional LiteX Python package; af MVP generates LiteX wrapper skeletons without importing litex."; \
    fi

ENV RUSTUP_TOOLCHAIN=${RUST_TOOLCHAIN}

WORKDIR /work

CMD ["scripts/docker-smoke.sh"]
