# Generated by AccelFury IP Toolchain
FROM rust:1-slim-bookworm

ARG AF_INSTALL_LITEX=false

ENV DEBIAN_FRONTEND=noninteractive
ENV AF_OFFLINE=true
ENV PATH="/opt/af-python/bin:${PATH}"

RUN set -eux; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ca-certificates \
        build-essential \
        pkg-config \
        git \
        curl \
        make \
        python3 \
        python3-pip \
        python3-venv \
        verilator \
        yosys; \
    if apt-cache show openfpgaloader >/dev/null 2>&1; then \
        apt-get install -y --no-install-recommends openfpgaloader; \
    fi; \
    if apt-cache show symbiyosys >/dev/null 2>&1; then \
        apt-get install -y --no-install-recommends symbiyosys; \
    fi; \
    rm -rf /var/lib/apt/lists/*

RUN set -eux; \
    python3 -m venv /opt/af-python; \
    /opt/af-python/bin/pip --default-timeout=120 --retries 10 install --no-cache-dir fusesoc; \
    if [ "${AF_INSTALL_LITEX}" = "true" ]; then \
        /opt/af-python/bin/pip --default-timeout=120 --retries 10 install --no-cache-dir litex; \
    else \
        echo "Skipping optional LiteX Python package; af MVP generates LiteX wrapper skeletons without importing litex."; \
    fi

WORKDIR /work

CMD ["scripts/docker-smoke.sh"]
