# Generated by AccelFury IP Toolchain
.PHONY: smoke docker-build docker-smoke docker-shell oss-hdl-smoke

IMAGE ?= accelfury-af:oss
AF_BUILD_ROOT ?= .af-build/docker-smoke
RUST_TOOLCHAIN ?= 1.95.0-x86_64-unknown-linux-gnu
DOCKER_TARGET_CACHE ?= /tmp/af-docker-target
CARGO_HOME ?= $(HOME)/.cargo

smoke: docker-build docker-smoke

oss-hdl-smoke:
	scripts/oss-hdl-smoke.sh

docker-build:
	docker build --build-arg RUST_TOOLCHAIN=$(RUST_TOOLCHAIN) -t $(IMAGE) .

docker-smoke:
	docker run --rm \
		-v "$(PWD):/work" \
		-v "$(CARGO_HOME)/registry:/usr/local/cargo/registry" \
		-v "$(CARGO_HOME)/git:/usr/local/cargo/git" \
		-v "$(DOCKER_TARGET_CACHE):/tmp/af-target" \
		-w /work \
		-e AF_BUILD_ROOT=/work/$(AF_BUILD_ROOT) \
		-e RUSTUP_TOOLCHAIN=$(RUST_TOOLCHAIN) \
		-e CARGO_TARGET_DIR=/tmp/af-target \
		$(IMAGE) scripts/docker-smoke.sh

docker-shell:
	docker run --rm -it \
		-v "$(PWD):/work" \
		-v "$(CARGO_HOME)/registry:/usr/local/cargo/registry" \
		-v "$(CARGO_HOME)/git:/usr/local/cargo/git" \
		-v "$(DOCKER_TARGET_CACHE):/tmp/af-target" \
		-w /work \
		-e AF_BUILD_ROOT=/work/$(AF_BUILD_ROOT) \
		-e RUSTUP_TOOLCHAIN=$(RUST_TOOLCHAIN) \
		-e CARGO_TARGET_DIR=/tmp/af-target \
		$(IMAGE) bash
