# Generated by AccelFury IP Toolchain
.PHONY: smoke docker-build docker-smoke docker-shell

IMAGE ?= accelfury-af:oss
AF_BUILD_ROOT ?= .af-build/docker-smoke

smoke: docker-build docker-smoke

docker-build:
	docker build -t $(IMAGE) .

docker-smoke:
	docker run --rm -v "$(PWD):/work" -w /work -e AF_BUILD_ROOT=/work/$(AF_BUILD_ROOT) $(IMAGE) scripts/docker-smoke.sh

docker-shell:
	docker run --rm -it -v "$(PWD):/work" -w /work -e AF_BUILD_ROOT=/work/$(AF_BUILD_ROOT) $(IMAGE) bash
