// SPDX-License-Identifier: Apache-2.0
use assert_cmd::Command;
use predicates::str::contains;
use std::path::{Path, PathBuf};
use tempfile::tempdir;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .unwrap()
        .to_path_buf()
}

#[test]
fn doctor_json_works_without_optional_tools() {
    let mut cmd = Command::cargo_bin("af").unwrap();
    cmd.args(["doctor", "--json"])
        .assert()
        .success()
        .stdout(contains("\"generated_by\""))
        .stdout(contains("\"tool_versions\""));
}

#[test]
fn core_check_af_pdm_rx_passes() {
    let root = repo_root();
    let build = tempdir().unwrap();
    let mut cmd = Command::cargo_bin("af").unwrap();
    cmd.arg("--build-root")
        .arg(build.path())
        .args(["core", "check"])
        .arg(root.join("examples/af-pdm-rx"))
        .arg("--json")
        .assert()
        .success()
        .stdout(contains("\"status\": \"passed\""));

    assert!(build.path().join("reports/core-check.json").is_file());
    assert!(build.path().join("reports/core-check.md").is_file());
}

#[test]
fn wrapper_generate_fusesoc_writes_core() {
    let root = repo_root();
    let build = tempdir().unwrap();
    let mut cmd = Command::cargo_bin("af").unwrap();
    cmd.arg("--build-root")
        .arg(build.path())
        .args(["wrapper", "generate"])
        .arg(root.join("examples/af-pdm-rx"))
        .args(["--target", "fusesoc", "--json"])
        .assert()
        .success()
        .stdout(contains("accelfury_audio_af_pdm_rx.core"));

    let core_file = build.path().join("fusesoc/accelfury_audio_af_pdm_rx.core");
    assert!(core_file.is_file());
    let content = std::fs::read_to_string(core_file).unwrap();
    assert!(content.starts_with("# Generated by AccelFury IP Toolchain"));
}

#[test]
fn wrapper_generate_litex_writes_skeleton() {
    let root = repo_root();
    let build = tempdir().unwrap();
    let mut cmd = Command::cargo_bin("af").unwrap();
    cmd.arg("--build-root")
        .arg(build.path())
        .args(["wrapper", "generate"])
        .arg(root.join("examples/af-pdm-rx"))
        .args(["--target", "litex", "--board", "tang-nano-20k", "--json"])
        .assert()
        .success()
        .stdout(contains("af_pdm_rx_litex.py"));

    let wrapper = build.path().join("litex/af_pdm_rx_litex.py");
    assert!(wrapper.is_file());
    let content = std::fs::read_to_string(wrapper).unwrap();
    assert!(content.starts_with("# Generated by AccelFury IP Toolchain"));
    assert!(content.contains("must not generate CDC"));
}

#[test]
fn board_check_and_backend_list_work() {
    let root = repo_root();
    let mut board = Command::cargo_bin("af").unwrap();
    board
        .args(["board", "check"])
        .arg(root.join("boards/tang-nano-20k/af-board.toml"))
        .arg("--json")
        .assert()
        .success()
        .stdout(contains("\"id\": \"tang-nano-20k\""));

    let mut backend = Command::cargo_bin("af").unwrap();
    backend
        .args(["backend", "list", "--json"])
        .assert()
        .success()
        .stdout(contains("litex-wrapper-skeleton"));
}

#[test]
fn core_new_supports_verilog_2001_scaffold() {
    let dir = tempdir().unwrap();
    let core_dir = dir.path().join("verilog-demo");
    let build = tempdir().unwrap();

    let mut cmd = Command::cargo_bin("af").unwrap();
    cmd.arg("--build-root")
        .arg(build.path())
        .args(["core", "new"])
        .arg(&core_dir)
        .args(["--name", "verilog-demo", "--language", "verilog", "--json"])
        .assert()
        .success()
        .stdout(contains("\"language\": \"verilog\""));

    assert!(core_dir.join("af-core.toml").is_file());
    assert!(core_dir.join("rtl/verilog_demo.v").is_file());

    let mut check = Command::cargo_bin("af").unwrap();
    check
        .arg("--build-root")
        .arg(build.path())
        .args(["core", "check"])
        .arg(&core_dir)
        .arg("--json")
        .assert()
        .success()
        .stdout(contains("\"status\": \"passed\""));
}

#[test]
fn broken_fixtures_fail_without_panics() {
    let root = repo_root();
    let fixtures = [
        "missing-source",
        "missing-top",
        "invalid-port-width",
        "unknown-clock-domain",
        "path-traversal",
    ];

    for fixture in fixtures {
        let mut cmd = Command::cargo_bin("af").unwrap();
        cmd.args(["core", "check"])
            .arg(root.join("tests/fixtures/broken").join(fixture))
            .arg("--json")
            .assert()
            .failure()
            .stdout(contains("\"code\""))
            .stdout(contains("\"exit_code\""));
    }
}
