use assert_cmd::Command;
use predicates::str::contains;
use std::path::{Path, PathBuf};
use tempfile::tempdir;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .unwrap()
        .to_path_buf()
}

#[test]
fn doctor_json_works_without_optional_tools() {
    let mut cmd = Command::cargo_bin("af").unwrap();
    cmd.args(["doctor", "--json"])
        .assert()
        .success()
        .stdout(contains("\"generated_by\""))
        .stdout(contains("\"tool_versions\""));
}

#[test]
fn core_check_af_pdm_rx_passes() {
    let root = repo_root();
    let build = tempdir().unwrap();
    let mut cmd = Command::cargo_bin("af").unwrap();
    cmd.arg("--build-root")
        .arg(build.path())
        .args(["core", "check"])
        .arg(root.join("examples/af-pdm-rx"))
        .arg("--json")
        .assert()
        .success()
        .stdout(contains("\"status\": \"passed\""));

    assert!(build.path().join("reports/core-check.json").is_file());
    assert!(build.path().join("reports/core-check.md").is_file());
}

#[test]
fn wrapper_generate_fusesoc_writes_core() {
    let root = repo_root();
    let build = tempdir().unwrap();
    let mut cmd = Command::cargo_bin("af").unwrap();
    cmd.arg("--build-root")
        .arg(build.path())
        .args(["wrapper", "generate"])
        .arg(root.join("examples/af-pdm-rx"))
        .args(["--target", "fusesoc", "--json"])
        .assert()
        .success()
        .stdout(contains("accelfury_ip_af_pdm_rx.core"));

    let core_file = build.path().join("fusesoc/accelfury_ip_af_pdm_rx.core");
    assert!(core_file.is_file());
    let content = std::fs::read_to_string(core_file).unwrap();
    assert!(content.starts_with("# Generated by AccelFury IP Toolchain"));
}

#[test]
fn broken_fixtures_fail_without_panics() {
    let root = repo_root();
    let fixtures = [
        "missing-source",
        "missing-top",
        "invalid-port-width",
        "unknown-clock-domain",
        "path-traversal",
    ];

    for fixture in fixtures {
        let mut cmd = Command::cargo_bin("af").unwrap();
        cmd.args(["core", "check"])
            .arg(root.join("tests/fixtures/broken").join(fixture))
            .arg("--json")
            .assert()
            .failure()
            .stdout(contains("\"code\""))
            .stdout(contains("\"exit_code\""));
    }
}
