use af_manifest::CoreManifest;
use af_security::{safe_join, SecurityError};
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

pub const GENERATED_HEADER: &str = "Generated by AccelFury IP Toolchain";

#[derive(Debug, Error)]
pub enum FuseSocError {
    #[error(transparent)]
    Security(#[from] SecurityError),
    #[error("failed to write FuseSoC core `{path}`: {message}")]
    Write { path: PathBuf, message: String },
}

impl FuseSocError {
    pub fn code(&self) -> &'static str {
        match self {
            FuseSocError::Security(err) => err.code(),
            FuseSocError::Write { .. } => "AF_FUSESOC_WRITE_FAILED",
        }
    }

    pub fn hint(&self) -> &'static str {
        match self {
            FuseSocError::Security(err) => err.hint(),
            FuseSocError::Write { .. } => {
                "Check filesystem permissions and the selected output path."
            }
        }
    }

    pub fn exit_code(&self) -> i32 {
        match self {
            FuseSocError::Security(err) => err.exit_code(),
            FuseSocError::Write { .. } => 5,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct FuseSocArtifact {
    pub path: PathBuf,
    pub content: String,
}

pub fn core_file_name(manifest: &CoreManifest) -> String {
    format!(
        "{}_{}_{}.core",
        sanitize_component(&manifest.vendor),
        sanitize_component(&manifest.library),
        sanitize_component(&manifest.core)
    )
}

pub fn generate_core(manifest: &CoreManifest) -> String {
    let mut out = String::new();
    out.push_str("# ");
    out.push_str(GENERATED_HEADER);
    out.push('\n');
    out.push_str("CAPI=2:\n");
    out.push_str(&format!("name: {}\n", yaml_quote(&manifest.vlnv())));
    if let Some(description) = &manifest.metadata.description {
        out.push_str(&format!("description: {}\n", yaml_quote(description)));
    }
    if let Some(license) = &manifest.metadata.license {
        out.push_str(&format!("license: {}\n", yaml_quote(license)));
    }

    out.push_str("filesets:\n");
    out.push_str("  rtl:\n");
    out.push_str("    files:\n");
    for file in &manifest.sources.files {
        out.push_str(&format!("      - {}\n", yaml_quote(file)));
    }
    out.push_str(&format!(
        "    file_type: {}\n",
        yaml_quote(file_type(&manifest.rtl.language))
    ));

    if !manifest.testbenches.is_empty() {
        out.push_str("  tb:\n");
        out.push_str("    files:\n");
        for tb in &manifest.testbenches {
            for file in &tb.sources {
                out.push_str(&format!("      - {}\n", yaml_quote(file)));
            }
        }
        out.push_str(&format!(
            "    file_type: {}\n",
            yaml_quote(file_type(&manifest.rtl.language))
        ));
    }

    out.push_str("targets:\n");
    out.push_str("  default:\n");
    out.push_str("    filesets:\n");
    out.push_str("      - rtl\n");
    out.push_str(&format!(
        "    toplevel: {}\n",
        yaml_quote(&manifest.rtl.top)
    ));
    if !manifest.parameters.is_empty() {
        out.push_str("    parameters:\n");
        for parameter in &manifest.parameters {
            out.push_str(&format!(
                "      {}: {}\n",
                yaml_key(&parameter.name),
                yaml_quote(&parameter.value)
            ));
        }
    }
    if !manifest.testbenches.is_empty() {
        out.push_str("  sim:\n");
        out.push_str("    filesets:\n");
        out.push_str("      - rtl\n");
        out.push_str("      - tb\n");
        if let Some(tb) = manifest.testbenches.first() {
            out.push_str(&format!("    toplevel: {}\n", yaml_quote(&tb.top)));
        }
    }

    out
}

pub fn write_core(
    manifest: &CoreManifest,
    output_dir: impl AsRef<Path>,
) -> Result<FuseSocArtifact, FuseSocError> {
    let output_dir = output_dir.as_ref();
    fs::create_dir_all(output_dir).map_err(|err| FuseSocError::Write {
        path: output_dir.to_path_buf(),
        message: err.to_string(),
    })?;
    let file_name = core_file_name(manifest);
    let output = safe_join(output_dir, &file_name)?;
    let content = generate_core(manifest);
    fs::write(&output, &content).map_err(|err| FuseSocError::Write {
        path: output.clone(),
        message: err.to_string(),
    })?;
    Ok(FuseSocArtifact {
        path: output,
        content,
    })
}

fn sanitize_component(input: &str) -> String {
    input
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() || c == '_' || c == '-' {
                c
            } else {
                '_'
            }
        })
        .collect()
}

fn file_type(language: &str) -> &'static str {
    match language {
        "verilog" => "verilogSource",
        "vhdl" => "vhdlSource",
        _ => "systemVerilogSource",
    }
}

fn yaml_quote(input: &str) -> String {
    format!("'{}'", input.replace('\'', "''"))
}

fn yaml_key(input: &str) -> String {
    if input
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || matches!(c, '_' | '-'))
    {
        input.to_string()
    } else {
        yaml_quote(input)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn manifest() -> CoreManifest {
        CoreManifest::from_toml_str(
            r#"
af_version = "0.1"
name = "demo"
vendor = "accelfury"
library = "ip"
core = "demo"
version = "0.1.0"

[metadata]
license = "Apache-2.0"
description = "Demo core"

[rtl]
top = "demo"
language = "systemverilog"

[sources]
files = ["rtl/demo.sv"]

[[testbenches]]
name = "smoke"
top = "tb_demo"
sources = ["tb/tb_demo.sv"]
"#,
            "af-core.toml",
        )
        .unwrap()
    }

    #[test]
    fn generates_stable_fusesoc_core() {
        insta::assert_snapshot!(
            generate_core(&manifest()),
            @r###"
# Generated by AccelFury IP Toolchain
CAPI=2:
name: 'accelfury:ip:demo:0.1.0'
description: 'Demo core'
license: 'Apache-2.0'
filesets:
  rtl:
    files:
      - 'rtl/demo.sv'
    file_type: 'systemVerilogSource'
  tb:
    files:
      - 'tb/tb_demo.sv'
    file_type: 'systemVerilogSource'
targets:
  default:
    filesets:
      - rtl
    toplevel: 'demo'
  sim:
    filesets:
      - rtl
      - tb
    toplevel: 'tb_demo'
"###
        );
    }
}
