// SPDX-License-Identifier: Apache-2.0
//
// LiteX skeleton emission contract: deterministic Python output with the
// generated-by stamp, sanitised class name, and a board placeholder
// when none is supplied. The skeleton must not contain CDC, FIFO, or
// bus-bridge logic — it is a wrapper, not RTL.

mod common;

use af_backend::AfBackend;
use af_backend_litex::{generate_litex_skeleton, LitexBackend};
use af_manifest::CoreManifest;
use common::clone_example;

fn load_manifest() -> (tempfile::TempDir, CoreManifest) {
    let tmp = clone_example("af-mod-add");
    let manifest = CoreManifest::from_path(tmp.path().join("af-core.toml")).expect("manifest");
    (tmp, manifest)
}

#[test]
fn skeleton_carries_generated_by_stamp() {
    let (_tmp, manifest) = load_manifest();
    let skel = generate_litex_skeleton(&manifest, None);
    assert!(
        skel.content
            .starts_with("# Generated by AccelFury IP Toolchain"),
        "litex skeleton must carry the generated-by stamp on line 1"
    );
}

#[test]
fn skeleton_file_name_is_python_module() {
    let (_tmp, manifest) = load_manifest();
    let skel = generate_litex_skeleton(&manifest, None);
    assert!(skel.file_name.ends_with("_litex.py"));
    assert!(
        !skel.file_name.contains('-'),
        "file name must use underscores: {}",
        skel.file_name
    );
}

#[test]
fn board_unbound_when_none_passed() {
    let (_tmp, manifest) = load_manifest();
    let skel = generate_litex_skeleton(&manifest, None);
    assert!(skel.content.contains("self.board = \"unbound-board\""));
}

#[test]
fn board_is_propagated() {
    let (_tmp, manifest) = load_manifest();
    let skel = generate_litex_skeleton(&manifest, Some("digilent_arty_a7"));
    assert!(skel.content.contains("self.board = \"digilent_arty_a7\""));
}

#[test]
fn skeleton_never_emits_cdc_or_fifo_blocks() {
    let (_tmp, manifest) = load_manifest();
    let skel = generate_litex_skeleton(&manifest, None);
    let banned = [
        "AsyncFIFO",
        "MultiReg",
        "ClockDomainsRenamer",
        "CDCRegister",
    ];
    for b in banned {
        assert!(
            !skel.content.contains(b),
            "litex skeleton must remain pure wrapper, found {b}"
        );
    }
}

#[test]
fn warnings_disclose_the_skeleton_nature() {
    let (_tmp, manifest) = load_manifest();
    let skel = generate_litex_skeleton(&manifest, None);
    assert!(!skel.warnings.is_empty());
    assert!(!skel.limitations.is_empty());
}

#[test]
fn backend_trait_doctor_returns_unavailable() {
    let report = LitexBackend.doctor().expect("doctor must not error");
    assert_eq!(report.status, af_backend::BackendStatus::Unavailable);
}

#[test]
fn backend_advertises_wrapper_skeleton_capability() {
    let caps = LitexBackend.capabilities();
    assert!(caps
        .iter()
        .any(|c| c.name == "wrapper-skeleton" && c.supported));
}
