// SPDX-License-Identifier: Apache-2.0
use af_backend::{BackendReport, CommandRecord, ToolVersion};
use af_manifest::CoreManifest;
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};
use serde_json::Value;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};
use thiserror::Error;

pub const GENERATED_BY: &str = "Generated by AccelFury IP Toolchain";

#[derive(Debug, Error)]
pub enum ReportError {
    #[error("failed to serialize report: {message}")]
    Serialize { message: String },
    #[error("failed to create report directory `{path}`: {message}")]
    CreateDir { path: PathBuf, message: String },
    #[error("failed to write report `{path}`: {message}")]
    Write { path: PathBuf, message: String },
}

impl ReportError {
    pub fn code(&self) -> &'static str {
        match self {
            ReportError::Serialize { .. } => "AF_REPORT_SERIALIZE_FAILED",
            ReportError::CreateDir { .. } => "AF_REPORT_CREATE_DIR_FAILED",
            ReportError::Write { .. } => "AF_REPORT_WRITE_FAILED",
        }
    }

    pub fn hint(&self) -> &'static str {
        match self {
            ReportError::Serialize { .. } => "Check report data for unsupported values.",
            ReportError::CreateDir { .. } | ReportError::Write { .. } => {
                "Check filesystem permissions and the selected build root."
            }
        }
    }

    pub fn exit_code(&self) -> i32 {
        5
    }
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct CoreIdentity {
    pub name: String,
    pub vendor: String,
    pub library: String,
    pub core: String,
    pub version: String,
    pub vlnv: String,
}

impl From<&CoreManifest> for CoreIdentity {
    fn from(manifest: &CoreManifest) -> Self {
        Self {
            name: manifest.name.clone(),
            vendor: manifest.vendor.clone(),
            library: manifest.library.clone(),
            core: manifest.core.clone(),
            version: manifest.version.clone(),
            vlnv: manifest.vlnv(),
        }
    }
}

/// Reproducibility metadata for a report. Designed to be **deterministic**
/// given identical inputs and tool versions (NFR-004): no wall-clock timestamp
/// or runtime duration is included. Wall-clock telemetry, if needed, belongs
/// in a separate sidecar artifact.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct Reproducibility {
    pub host_os: String,
    pub host_arch: String,
    /// FNV1a64 hash of the sorted tool-version list, formatted as a 16-char
    /// hex string. Same env + same `tool_versions` → same hash, so the
    /// report stays bit-deterministic across runs on the same host.
    pub environment_hash: String,
    pub af_version: String,
}

impl Reproducibility {
    pub fn capture(tool_versions: &[ToolVersion]) -> Self {
        Self {
            host_os: std::env::consts::OS.to_string(),
            host_arch: std::env::consts::ARCH.to_string(),
            environment_hash: environment_hash_of(tool_versions),
            af_version: env!("CARGO_PKG_VERSION").to_string(),
        }
    }
}

fn environment_hash_of(tool_versions: &[ToolVersion]) -> String {
    let mut entries: Vec<String> = tool_versions
        .iter()
        .map(|tv| {
            format!(
                "{}={}",
                tv.tool,
                tv.version.as_deref().unwrap_or("unavailable")
            )
        })
        .collect();
    entries.sort();
    let mut hash: u64 = 0xcbf29ce484222325;
    for entry in entries {
        for byte in entry.bytes() {
            hash ^= u64::from(byte);
            hash = hash.wrapping_mul(0x100000001b3);
        }
        hash ^= u64::from(b'\n');
        hash = hash.wrapping_mul(0x100000001b3);
    }
    format!("{hash:016x}")
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct AfReport {
    pub schema_version: String,
    pub kind: String,
    pub generated_by: String,
    pub report_version: String,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub core: Option<CoreIdentity>,
    #[serde(default)]
    pub tool_versions: Vec<ToolVersion>,
    #[serde(default)]
    pub commands: Vec<CommandRecord>,
    #[serde(default)]
    pub artifacts: Vec<String>,
    #[serde(default)]
    pub warnings: Vec<String>,
    #[serde(default)]
    pub limitations: Vec<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub maturity: Option<ReusableCoreMaturity>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub standards: Option<Value>,
    /// M3 reproducibility metadata. Populated via `with_reproducibility()`
    /// when the producer has finished merging tool_versions. Deterministic by
    /// construction (no timestamps).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub reproducibility: Option<Reproducibility>,
    /// M3 per-command typed payload. Each command-handler in af-cli fills in
    /// the variant relevant to the command that was just run, so the JSON
    /// emitted by `af core lint` is structurally distinguishable from
    /// `af core sim` / `af core formal` / `af core package` / `af build`.
    /// `None` for commands that do not have a dedicated payload yet (e.g.
    /// `core check`, `core report`).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub command_payload: Option<CommandPayload>,
}

/// Typed per-command payload (M3). The `kind` discriminator carries the
/// command name so consumers can branch without sniffing schemas, while the
/// inner data is command-specific. Adding a new variant does not break old
/// consumers that ignore unknown kinds.
#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum CommandPayload {
    Check(CheckPayload),
    Lint(LintPayload),
    Simulation(SimulationPayload),
    Formal(FormalPayload),
    Build(BuildPayload),
    Package(PackagePayload),
    Report(ReportPayload),
    Tooling(ToolingPayload),
    Doctor(DoctorPayload),
    Flash(FlashPayload),
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct CheckPayload {
    pub manifest_status: String,
    pub source_count: usize,
    pub inspection_issue_count: usize,
    pub legal_issue_count: usize,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct LintPayload {
    pub backend: String,
    pub backend_status: String,
    pub source_count: usize,
    pub include_dir_count: usize,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct SimulationPayload {
    pub backend: String,
    pub backend_status: String,
    pub testbench_count: usize,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct FormalPayload {
    pub backend: String,
    pub backend_status: String,
    pub property_count: usize,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct BuildPayload {
    pub backend: String,
    pub backend_status: String,
    pub board: String,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct PackagePayload {
    pub format: String,
    pub manifest_path: PathBuf,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct ReportPayload {
    /// `"core_with_manifest"` when an `af-core.toml` was found, otherwise
    /// `"build_dir_only"`. Lets consumers branch without re-checking inputs.
    pub input_kind: String,
    pub maturity_verdict: String,
    pub maturity_blocked_rows: usize,
    pub artifact_count: usize,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct ToolingPayload {
    pub total_tools: usize,
    pub available_tools: usize,
    pub missing_tools: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct DoctorPayload {
    pub overall_status: String,
    pub total_tools: usize,
    pub available_tools: usize,
    pub missing_tools: Vec<String>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct FlashPayload {
    pub backend: String,
    pub backend_status: String,
}

impl AfReport {
    pub fn new(status: impl Into<String>) -> Self {
        Self {
            schema_version: "0.1".to_string(),
            kind: "accelfury.report".to_string(),
            generated_by: GENERATED_BY.to_string(),
            report_version: "0.1".to_string(),
            status: status.into(),
            core: None,
            tool_versions: vec![ToolVersion::available("af", env!("CARGO_PKG_VERSION"))],
            commands: Vec::new(),
            artifacts: Vec::new(),
            warnings: Vec::new(),
            limitations: Vec::new(),
            maturity: None,
            standards: None,
            reproducibility: None,
            command_payload: None,
        }
    }

    /// Populate `reproducibility` from the report's current `tool_versions`.
    /// Idempotent: calling twice with the same `tool_versions` yields the
    /// same hash. Safe to call after `merge_backend`.
    pub fn with_reproducibility(mut self) -> Self {
        self.reproducibility = Some(Reproducibility::capture(&self.tool_versions));
        self
    }

    pub fn for_core(status: impl Into<String>, manifest: &CoreManifest) -> Self {
        let mut report = Self::new(status);
        report.core = Some(CoreIdentity::from(manifest));
        report
            .limitations
            .extend(manifest.known_limitations.clone());
        report
    }

    pub fn merge_backend(&mut self, backend: &BackendReport) {
        self.tool_versions
            .extend(backend.tool_versions.iter().cloned());
        self.commands.extend(backend.commands.iter().cloned());
        self.artifacts.extend(
            backend
                .artifacts
                .iter()
                .map(|path| path.display().to_string()),
        );
        self.warnings.extend(backend.warnings.iter().cloned());
        self.limitations.extend(backend.limitations.iter().cloned());
    }
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct ReusableCoreMaturity {
    pub verdict: String,
    pub summary: String,
    pub rows: Vec<MaturityRow>,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct MaturityRow {
    pub area: String,
    pub status: String,
    pub evidence: Vec<String>,
    pub limitations: Vec<String>,
}

#[derive(Clone, Debug, Default, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct CiEvidenceRecord {
    #[serde(default)]
    pub workflow_run_url: Option<String>,
    pub commit_sha: String,
    pub conclusion: String,
    #[serde(default)]
    pub artifact_bundle: Option<String>,
    #[serde(default)]
    pub sha256sums: Option<String>,
    #[serde(default)]
    pub source_path: Option<String>,
}

#[derive(Clone, Copy, Debug)]
pub struct MaturityInputs<'a> {
    pub manifest: Option<&'a CoreManifest>,
    pub artifacts: &'a [String],
    pub warnings: &'a [String],
    pub limitations: &'a [String],
    pub ci_evidence: &'a [CiEvidenceRecord],
    pub current_commit_sha: Option<&'a str>,
    /// Board ids declared by the manifest whose registry status is not
    /// `verified_on_hardware`. The maturity row enumerates them so consumers
    /// see exactly which boards remain template-only.
    pub placeholder_boards: &'a [String],
}

impl<'a> MaturityInputs<'a> {
    pub fn from_legacy(
        manifest: Option<&'a CoreManifest>,
        artifacts: &'a [String],
        warnings: &'a [String],
        limitations: &'a [String],
    ) -> Self {
        Self {
            manifest,
            artifacts,
            warnings,
            limitations,
            ci_evidence: &[],
            current_commit_sha: None,
            placeholder_boards: &[],
        }
    }
}

pub fn reusable_core_maturity(inputs: &MaturityInputs<'_>) -> ReusableCoreMaturity {
    let manifest = inputs.manifest;
    let artifacts = inputs.artifacts;
    let warnings = inputs.warnings;
    let limitations = inputs.limitations;
    let mut rows = Vec::new();
    let manifest_evidence = manifest
        .map(|manifest| format!("af-core.toml parsed for {}", manifest.vlnv()))
        .into_iter()
        .collect::<Vec<_>>();
    rows.push(row(
        "manifest_contract",
        if manifest.is_some() {
            "supported"
        } else {
            "blocked"
        },
        manifest_evidence,
        if manifest.is_some() {
            Vec::new()
        } else {
            vec!["No af-core.toml was available for this report input.".to_string()]
        },
    ));

    let source_status = manifest
        .map(|manifest| {
            if manifest.sources.files.is_empty() {
                "blocked"
            } else {
                "supported"
            }
        })
        .unwrap_or("blocked");
    rows.push(row(
        "source_portability",
        source_status,
        manifest
            .map(|manifest| {
                vec![format!(
                    "{} manifest source file(s) declared for top `{}`",
                    manifest.sources.files.len(),
                    manifest.rtl.top
                )]
            })
            .unwrap_or_default(),
        if warnings.is_empty() {
            Vec::new()
        } else {
            warnings.to_vec()
        },
    ));

    rows.push(row(
        "evidence_portability",
        if artifacts.is_empty() {
            "blocked"
        } else {
            "supported"
        },
        artifacts.to_vec(),
        if artifacts.is_empty() {
            vec!["No portable evidence artifacts were discovered.".to_string()]
        } else {
            Vec::new()
        },
    ));

    let wrapper_artifacts = matching_artifacts(artifacts, &["fusesoc", "litex", "ipxact", ".core"]);
    rows.push(row(
        "wrapper_package_compatibility",
        if wrapper_artifacts.is_empty() {
            "blocked"
        } else {
            "supported"
        },
        wrapper_artifacts,
        if artifacts.iter().any(|artifact| {
            artifact.contains("fusesoc")
                || artifact.contains("litex")
                || artifact.contains("ipxact")
                || artifact.ends_with(".core")
        }) {
            Vec::new()
        } else {
            vec![
                "Run wrapper generation for FuseSoC, LiteX, or IP-XACT to populate this row."
                    .to_string(),
            ]
        },
    ));

    let open_source_artifacts = matching_artifacts(
        artifacts,
        &[
            "native",
            "verilator",
            "yosys",
            "sby",
            "openfpga-ci",
            "evidence",
            "core-check",
            "core-sim",
            "lint_report",
            "simulation_report",
            "formal_report",
            "synthesis_report",
            "pnr_report",
        ],
    );
    rows.push(row(
        "open_source_tool_evidence",
        if open_source_artifacts.is_empty() {
            "blocked"
        } else {
            "supported"
        },
        open_source_artifacts,
        if artifacts.iter().any(|artifact| {
            artifact.contains("native")
                || artifact.contains("verilator")
                || artifact.contains("yosys")
                || artifact.contains("sby")
                || artifact.contains("openfpga-ci")
                || artifact.contains("evidence")
                || artifact.contains("core-check")
                || artifact.contains("core-sim")
                || artifact.contains("lint_report")
                || artifact.contains("simulation_report")
                || artifact.contains("formal_report")
                || artifact.contains("synthesis_report")
                || artifact.contains("pnr_report")
        }) {
            Vec::new()
        } else {
            vec!["No open-source backend report artifacts were discovered.".to_string()]
        },
    ));

    let vendor_artifacts =
        matching_artifacts(artifacts, &["vivado", "quartus", "gowin", "efinity"]);
    rows.push(row(
        "vendor_tool_evidence",
        if vendor_artifacts.is_empty() {
            "blocked"
        } else {
            "supported"
        },
        vendor_artifacts,
        if artifacts.iter().any(|artifact| {
            artifact.contains("vivado")
                || artifact.contains("quartus")
                || artifact.contains("gowin")
                || artifact.contains("efinity")
        }) {
            Vec::new()
        } else {
            vec!["No vendor implementation report artifacts were discovered.".to_string()]
        },
    ));

    rows.push(ci_evidence_row(
        manifest,
        artifacts,
        inputs.ci_evidence,
        inputs.current_commit_sha,
    ));

    rows.push(board_hardware_evidence_row(
        manifest,
        inputs.placeholder_boards,
    ));

    let release_supported = manifest
        .and_then(|manifest| manifest.metadata.license.as_deref())
        .is_some_and(|license| !license.trim().is_empty());
    rows.push(row(
        "release_support_legal_evidence",
        if release_supported {
            "supported"
        } else {
            "blocked"
        },
        manifest
            .and_then(|manifest| manifest.metadata.license.as_deref())
            .map(|license| vec![format!("license `{license}` declared")])
            .unwrap_or_default(),
        limitations.to_vec(),
    ));

    rows.extend(standards_profile_rows(manifest, artifacts));

    rows.push(row(
        "buyer_grade_readiness",
        "blocked",
        Vec::new(),
        vec![
            "Buyer-grade readiness requires wrapper, CI, backend, limitation, and release evidence rows to be populated.".to_string(),
        ],
    ));
    rows.push(row(
        "enterprise_grade_readiness",
        "blocked",
        Vec::new(),
        vec![
            "Enterprise-grade readiness additionally requires vendor, board, support, and production-flow evidence.".to_string(),
        ],
    ));

    let verdict = if rows
        .iter()
        .any(|row| row.status == "blocked" && row.area.ends_with("_readiness"))
    {
        "blocked"
    } else if rows.iter().any(|row| row.status == "blocked") {
        "partial"
    } else {
        "supported"
    }
    .to_string();
    let blocked_count = rows.iter().filter(|row| row.status == "blocked").count();
    ReusableCoreMaturity {
        verdict: verdict.clone(),
        summary: format!(
            "Reusable-core maturity verdict is `{verdict}` with {blocked_count} blocked row(s)."
        ),
        rows,
    }
}

fn standards_profile_rows(
    manifest: Option<&CoreManifest>,
    artifacts: &[String],
) -> Vec<MaturityRow> {
    let Some(manifest) = manifest else {
        return Vec::new();
    };
    let Some(standards) = manifest.standards.as_ref() else {
        return Vec::new();
    };
    let profile = standards
        .profile
        .as_deref()
        .unwrap_or(af_manifest::standards::FPGA_IP_CORE_PROFILE_ID);
    let declared = standards
        .artifacts
        .iter()
        .map(|artifact| format!("{}:{}", artifact.kind, artifact.path))
        .collect::<Vec<_>>();
    let mut rows = Vec::new();
    rows.push(row(
        "standards_profile",
        "supported",
        vec![format!("standards profile `{profile}` declared")],
        Vec::new(),
    ));
    rows.push(standards_row(
        "metadata_packaging",
        &["ip-xact"],
        &["ipxact", "component.xml"],
        &declared,
        artifacts,
        "Declare or generate an IP-XACT artifact for machine-readable packaging.",
    ));
    rows.push(standards_row(
        "register_map_evidence",
        &["systemrdl"],
        &[".rdl", "reg_pkg", "regs.h"],
        &declared,
        artifacts,
        "Declare a SystemRDL artifact when the core exposes CSRs/registers, or document N/A.",
    ));
    rows.push(standards_row(
        "lint_style_evidence",
        &["verible-lint", "native-lint"],
        &["verible", "core-lint", "lint_report"],
        &declared,
        artifacts,
        "Run native lint or Verible and declare the lint artifact.",
    ));
    rows.push(standards_row(
        "provenance_hbom",
        &["spdx-hbom", "cyclonedx-hbom"],
        &["hbom", "spdx", "cyclonedx"],
        &declared,
        artifacts,
        "Generate a per-core HBOM/SBOM-equivalent artifact.",
    ));
    rows.push(standards_row(
        "security_foundation",
        &["security-threat-model", "sa-edi", "cwe-coverage"],
        &["threat_model", "sa-edi", "cwe"],
        &declared,
        artifacts,
        "Security rows are foundation hooks unless a threat model, SA-EDI, or CWE coverage artifact is declared.",
    ));
    rows.push(standards_row(
        "safety_foundation",
        &["safety-manual"],
        &["safety_manual", "fmeda", "do254", "iso26262"],
        &declared,
        artifacts,
        "Safety rows are foundation hooks; do not claim certification without a safety manual and supporting evidence.",
    ));
    rows.push(standards_row(
        "asic_power_dft_foundation",
        &["upf", "power-na", "dft", "jtag-na"],
        &[".upf", ".ctl", "bsdl", "power", "dft"],
        &declared,
        artifacts,
        "Declare UPF/DFT artifacts or explicit N/A rationale for non-ASIC FPGA-only cores.",
    ));
    rows
}

fn standards_row(
    area: &str,
    accepted_kinds: &[&str],
    artifact_markers: &[&str],
    declared: &[String],
    artifacts: &[String],
    missing: &str,
) -> MaturityRow {
    let mut evidence = declared
        .iter()
        .filter(|entry| {
            accepted_kinds
                .iter()
                .any(|kind| entry.starts_with(&format!("{kind}:")))
        })
        .cloned()
        .collect::<Vec<_>>();
    evidence.extend(matching_artifacts(artifacts, artifact_markers));
    evidence.sort();
    evidence.dedup();
    if evidence.is_empty() {
        row(area, "planned", Vec::new(), vec![missing.to_string()])
    } else {
        row(area, "supported", evidence, Vec::new())
    }
}

fn row(
    area: impl Into<String>,
    status: impl Into<String>,
    evidence: Vec<String>,
    limitations: Vec<String>,
) -> MaturityRow {
    MaturityRow {
        area: area.into(),
        status: status.into(),
        evidence,
        limitations,
    }
}

fn matching_artifacts(artifacts: &[String], markers: &[&str]) -> Vec<String> {
    artifacts
        .iter()
        .filter(|artifact| {
            let lowered = artifact.to_ascii_lowercase();
            markers.iter().any(|marker| lowered.contains(marker))
        })
        .cloned()
        .collect()
}

fn ci_workflow_files(artifacts: &[String]) -> Vec<String> {
    artifacts
        .iter()
        .filter(|artifact| {
            let lowered = artifact.to_ascii_lowercase();
            lowered.contains(".github/workflows")
                && (lowered.ends_with(".yml") || lowered.ends_with(".yaml"))
                || lowered.contains("hdl-ci.yml")
                || lowered.contains("af-ci.yml")
        })
        .cloned()
        .collect()
}

fn ci_evidence_row(
    manifest: Option<&CoreManifest>,
    artifacts: &[String],
    records: &[CiEvidenceRecord],
    current_commit_sha: Option<&str>,
) -> MaturityRow {
    // Early branch: prefer declarative manifest evidence when the recorded
    // commit_sha matches the current HEAD AND conclusion == "success".
    // Manifesto rule: declarations are structured input, not fabricated
    // assertion — SHA mismatch or non-success keeps the row as `planned`.
    if let Some(ev) = manifest
        .and_then(|m| m.evidence.as_ref())
        .and_then(|e| e.docker_ci_cd.as_ref())
    {
        let workflows = ci_workflow_files(artifacts);
        let sha_ok = current_commit_sha
            .map(|cur| sha_matches(&ev.commit_sha, cur))
            .unwrap_or(false);
        let conclusion_ok = ev.conclusion.eq_ignore_ascii_case("success");
        if sha_ok && conclusion_ok {
            let mut evidence = workflows.clone();
            evidence.push(format!("declared run_url={}", ev.run_url));
            evidence.push(format!("declared commit_sha={}", ev.commit_sha));
            evidence.push(format!("declared sha256sums={}", ev.sha256sums));
            evidence.push(format!("declared conclusion={}", ev.conclusion));
            evidence.sort();
            evidence.dedup();
            return row("docker_ci_cd_evidence", "supported", evidence, Vec::new());
        }
        // Declared but does not match — fall through and surface the
        // reason via the existing "planned"/"blocked" branches; treat
        // explicitly here when there is no other artefact in play to
        // give a precise limitation message.
        if records.is_empty() && workflows.is_empty() {
            let limitation = if !sha_ok {
                format!(
                    "Declared docker_ci_cd evidence commit_sha `{}` does not match current HEAD.",
                    ev.commit_sha
                )
            } else {
                format!(
                    "Declared docker_ci_cd evidence conclusion `{}` is not `success`.",
                    ev.conclusion
                )
            };
            return row(
                "docker_ci_cd_evidence",
                "planned",
                vec![
                    format!("declared run_url={}", ev.run_url),
                    format!("declared commit_sha={}", ev.commit_sha),
                ],
                vec![limitation],
            );
        }
    }

    let workflows = ci_workflow_files(artifacts);

    if workflows.is_empty() && records.is_empty() {
        return row(
            "docker_ci_cd_evidence",
            "blocked",
            Vec::new(),
            vec!["No CI configuration or CI run evidence was discovered.".to_string()],
        );
    }

    if records.is_empty() {
        return row(
            "docker_ci_cd_evidence",
            "blocked",
            workflows,
            vec![
                "Workflow file present without an attributable CI run evidence record; run `af evidence ingest --kind ci-run` after a successful workflow run.".to_string(),
            ],
        );
    }

    let Some(current_sha) = current_commit_sha else {
        let mut evidence = workflows.clone();
        for record in records {
            evidence.push(format!(
                "recorded ci-run commit_sha={} conclusion={}",
                record.commit_sha, record.conclusion
            ));
        }
        return row(
            "docker_ci_cd_evidence",
            "blocked",
            evidence,
            vec![
                "Cannot determine current commit SHA to compare against ingested CI evidence."
                    .to_string(),
            ],
        );
    };

    let matching: Vec<&CiEvidenceRecord> = records
        .iter()
        .filter(|record| sha_matches(&record.commit_sha, current_sha))
        .collect();

    if matching.is_empty() {
        let mut evidence = workflows.clone();
        let mut recorded = Vec::new();
        for record in records {
            evidence.push(format!(
                "recorded ci-run commit_sha={} conclusion={}",
                record.commit_sha, record.conclusion
            ));
            recorded.push(record.commit_sha.clone());
        }
        return row(
            "docker_ci_cd_evidence",
            "blocked",
            evidence,
            vec![format!(
                "CI evidence is stale: recorded commit_sha {:?} does not match current HEAD `{}`.",
                recorded, current_sha
            )],
        );
    }

    let successful: Vec<&&CiEvidenceRecord> = matching
        .iter()
        .filter(|record| record.conclusion.eq_ignore_ascii_case("success"))
        .collect();

    if successful.is_empty() {
        let mut evidence = workflows.clone();
        let mut conclusions = Vec::new();
        for record in &matching {
            evidence.push(format!(
                "recorded ci-run commit_sha={} conclusion={}",
                record.commit_sha, record.conclusion
            ));
            conclusions.push(record.conclusion.clone());
        }
        return row(
            "docker_ci_cd_evidence",
            "blocked",
            evidence,
            vec![format!(
                "Recorded CI run for current HEAD concluded as {:?}, not `success`.",
                conclusions
            )],
        );
    }

    let mut evidence = workflows.clone();
    for record in &successful {
        if let Some(url) = &record.workflow_run_url {
            evidence.push(format!("workflow_run_url={url}"));
        }
        evidence.push(format!("commit_sha={}", record.commit_sha));
        evidence.push(format!("conclusion={}", record.conclusion));
        if let Some(bundle) = &record.artifact_bundle {
            evidence.push(format!("artifact_bundle={bundle}"));
        }
        if let Some(sha256) = &record.sha256sums {
            evidence.push(format!("sha256sums={sha256}"));
        }
        if let Some(source) = &record.source_path {
            evidence.push(format!("evidence_source={source}"));
        }
    }
    evidence.sort();
    evidence.dedup();
    row("docker_ci_cd_evidence", "supported", evidence, Vec::new())
}

fn board_hardware_evidence_row(
    manifest: Option<&CoreManifest>,
    placeholder_boards: &[String],
) -> MaturityRow {
    let declared: Vec<&String> = manifest
        .map(|m| m.boards.iter().collect::<Vec<_>>())
        .unwrap_or_default();
    if declared.is_empty() {
        return row(
            "board_hardware_evidence",
            "not-applicable",
            Vec::new(),
            vec!["Declared board support is not hardware bring-up evidence.".to_string()],
        );
    }

    let placeholder_set: std::collections::BTreeSet<&str> =
        placeholder_boards.iter().map(|s| s.as_str()).collect();
    let mut evidence = Vec::with_capacity(declared.len());
    let mut placeholders_in_manifest: Vec<String> = Vec::new();
    for board in &declared {
        let label = if placeholder_set.contains(board.as_str()) {
            placeholders_in_manifest.push((*board).clone());
            "draft"
        } else {
            "verified-or-unknown"
        };
        evidence.push(format!("manifest declares board `{board}` ({label})"));
    }

    let mut limitations =
        vec!["Declared board support is not hardware bring-up evidence.".to_string()];
    if !placeholders_in_manifest.is_empty() {
        limitations.push(format!(
            "Boards {:?} have `draft_placeholder` (or non-verified) registry status; their pin/clock/resource metadata is template-only.",
            placeholders_in_manifest
        ));
    }

    row("board_hardware_evidence", "planned", evidence, limitations)
}

fn sha_matches(recorded: &str, current: &str) -> bool {
    let recorded = recorded.trim();
    let current = current.trim();
    if recorded.is_empty() || current.is_empty() {
        return false;
    }
    let min_len = recorded.len().min(current.len());
    if min_len < 7 {
        return false;
    }
    recorded
        .get(..min_len)
        .zip(current.get(..min_len))
        .map(|(a, b)| a.eq_ignore_ascii_case(b))
        .unwrap_or(false)
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct WrittenReports {
    pub json: PathBuf,
    pub markdown: PathBuf,
}

#[derive(Clone, Debug, Deserialize, JsonSchema, Serialize, PartialEq, Eq)]
pub struct Artifact {
    pub generated_by: String,
    pub timestamp: String,
    pub label: String,
    pub content: String,
}

pub fn render_json(report: &AfReport) -> Result<String, ReportError> {
    serde_json::to_string_pretty(report).map_err(|err| ReportError::Serialize {
        message: err.to_string(),
    })
}

pub fn render_markdown(report: &AfReport) -> String {
    let mut out = String::new();
    out.push_str("<!-- ");
    out.push_str(GENERATED_BY);
    out.push_str(" -->\n");
    out.push_str("# AccelFury Report\n\n");
    out.push_str(&format!("- Kind: `{}`\n", report.kind));
    out.push_str(&format!("- Schema version: `{}`\n", report.schema_version));
    out.push_str(&format!("- Status: `{}`\n", report.status));
    out.push_str(&format!("- Report version: `{}`\n", report.report_version));
    if let Some(core) = &report.core {
        out.push_str(&format!("- Core: `{}`\n", core.vlnv));
    }

    write_section(
        &mut out,
        "Tool Versions",
        &tool_version_lines(&report.tool_versions),
    );
    write_section(&mut out, "Commands", &command_lines(&report.commands));
    write_section(&mut out, "Artifacts", &report.artifacts);
    write_section(&mut out, "Warnings", &report.warnings);
    write_section(&mut out, "Limitations", &report.limitations);
    if let Some(maturity) = &report.maturity {
        out.push_str("\n## Reusable Core Maturity\n\n");
        out.push_str(&format!("- Verdict: `{}`\n", maturity.verdict));
        out.push_str(&format!("- Summary: {}\n", maturity.summary));
        for row in &maturity.rows {
            out.push_str(&format!("- `{}`: `{}`", row.area, row.status));
            if !row.evidence.is_empty() {
                out.push_str(&format!("; evidence: {}", row.evidence.join(", ")));
            }
            if !row.limitations.is_empty() {
                out.push_str(&format!("; limitations: {}", row.limitations.join(", ")));
            }
            out.push('\n');
        }
    }
    if let Some(standards) = &report.standards {
        out.push_str("\n## FPGA/IP Standards Evidence\n\n");
        if let Some(profile) = standards["profile"].as_str() {
            out.push_str(&format!("- Profile: `{profile}`\n"));
        }
        if let Some(summary) = standards.get("summary") {
            out.push_str(&format!(
                "- Summary: `{}` supported, `{}` blocked, `{}` planned of `{}` total\n",
                summary["supported_items"],
                summary["blocked_items"],
                summary["planned_items"],
                summary["total_items"]
            ));
        }
        if let Some(limitations) = standards["limitations"].as_array() {
            for limitation in limitations {
                if let Some(text) = limitation.as_str() {
                    out.push_str(&format!("- Limitation: {text}\n"));
                }
            }
        }
    }
    out
}

pub fn write_reports(
    output_dir: impl AsRef<Path>,
    base_name: &str,
    report: &AfReport,
) -> Result<WrittenReports, ReportError> {
    let output_dir = output_dir.as_ref();
    fs::create_dir_all(output_dir).map_err(|err| ReportError::CreateDir {
        path: output_dir.to_path_buf(),
        message: err.to_string(),
    })?;

    let json = output_dir.join(format!("{base_name}.json"));
    let markdown = output_dir.join(format!("{base_name}.md"));
    let json_content = render_json(report)?;
    let markdown_content = render_markdown(report);
    fs::write(&json, json_content).map_err(|err| ReportError::Write {
        path: json.clone(),
        message: err.to_string(),
    })?;
    fs::write(&markdown, markdown_content).map_err(|err| ReportError::Write {
        path: markdown.clone(),
        message: err.to_string(),
    })?;
    Ok(WrittenReports { json, markdown })
}

pub fn collect_report(label: &str, content: &str) -> Result<Artifact, ReportError> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|err| ReportError::Serialize {
            message: err.to_string(),
        })?
        .as_secs();
    Ok(Artifact {
        generated_by: GENERATED_BY.to_string(),
        timestamp: now.to_string(),
        label: label.to_string(),
        content: content.to_string(),
    })
}

pub fn save_report(artifact: &Artifact, dir: impl AsRef<Path>) -> Result<PathBuf, ReportError> {
    let dir = dir.as_ref();
    fs::create_dir_all(dir).map_err(|err| ReportError::CreateDir {
        path: dir.to_path_buf(),
        message: err.to_string(),
    })?;
    let path = dir.join(format!("{}_{}.json", artifact.label, artifact.timestamp));
    let payload = serde_json::to_string_pretty(artifact).map_err(|err| ReportError::Serialize {
        message: err.to_string(),
    })?;
    fs::write(&path, payload).map_err(|err| ReportError::Write {
        path: path.clone(),
        message: err.to_string(),
    })?;
    Ok(path)
}

fn write_section(out: &mut String, title: &str, values: &[String]) {
    out.push('\n');
    out.push_str("## ");
    out.push_str(title);
    out.push_str("\n\n");
    if values.is_empty() {
        out.push_str("- None\n");
    } else {
        for value in values {
            out.push_str("- ");
            out.push_str(value);
            out.push('\n');
        }
    }
}

fn tool_version_lines(versions: &[ToolVersion]) -> Vec<String> {
    versions
        .iter()
        .map(|version| {
            if version.available {
                format!(
                    "`{}`: {}",
                    version.tool,
                    version.version.as_deref().unwrap_or("available")
                )
            } else {
                format!(
                    "`{}`: unavailable ({})",
                    version.tool,
                    version.message.as_deref().unwrap_or("no detail")
                )
            }
        })
        .collect()
}

fn command_lines(commands: &[CommandRecord]) -> Vec<String> {
    commands
        .iter()
        .map(|command| {
            let argv = std::iter::once(command.program.as_str())
                .chain(command.args.iter().map(String::as_str))
                .collect::<Vec<_>>()
                .join(" ");
            format!(
                "`{argv}` exit={}",
                command
                    .exit_code
                    .map(|code| code.to_string())
                    .unwrap_or_else(|| "signal".to_string())
            )
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use af_backend::{BackendStatus, CommandRecord, ToolVersion};

    fn sample_report() -> AfReport {
        let mut report = AfReport::new("passed");
        let mut backend = BackendReport::new("fake", BackendStatus::Passed);
        backend.tool_versions = vec![ToolVersion::available("fake", "fake 1.0")];
        backend.commands = vec![CommandRecord {
            program: "fake".to_string(),
            args: vec!["--version".to_string()],
            cwd: None,
            exit_code: Some(0),
            stdout: "fake 1.0".to_string(),
            stderr: String::new(),
            env: Default::default(),
            allow_network: false,
            timeout_seconds: None,
            stdout_log: None,
            stderr_log: None,
        }];
        backend.artifacts = vec![PathBuf::from(".af-build/report.json")];
        backend.warnings = vec!["warning".to_string()];
        backend.limitations = vec!["limitation".to_string()];
        report.merge_backend(&backend);
        report
    }

    #[test]
    fn reproducibility_is_deterministic_for_same_tool_versions() {
        let versions = vec![
            ToolVersion::available("af", "0.1.0"),
            ToolVersion::available("yosys", "0.36"),
        ];
        let a = Reproducibility::capture(&versions);
        let b = Reproducibility::capture(&versions);
        assert_eq!(a, b, "reproducibility metadata must be deterministic");
    }

    #[test]
    fn reproducibility_changes_when_tool_versions_change() {
        let v1 = vec![ToolVersion::available("yosys", "0.36")];
        let v2 = vec![ToolVersion::available("yosys", "0.40")];
        let a = Reproducibility::capture(&v1);
        let b = Reproducibility::capture(&v2);
        assert_ne!(
            a.environment_hash, b.environment_hash,
            "different tool versions must yield different environment_hash"
        );
    }

    #[test]
    fn reproducibility_captures_host_os_and_af_version() {
        let r = Reproducibility::capture(&[ToolVersion::available("af", "0.1.0")]);
        assert_eq!(r.host_os, std::env::consts::OS);
        assert_eq!(r.host_arch, std::env::consts::ARCH);
        assert_eq!(r.af_version, env!("CARGO_PKG_VERSION"));
        assert_eq!(r.environment_hash.len(), 16, "FNV1a64 hex must be 16 chars");
    }

    #[test]
    fn with_reproducibility_is_idempotent() {
        let a = AfReport::new("passed").with_reproducibility();
        let b = a.clone().with_reproducibility();
        assert_eq!(a.reproducibility, b.reproducibility);
    }

    #[test]
    fn docker_ci_cd_evidence_supported_via_manifest_declaration() {
        let manifest = CoreManifest::from_toml_str(
            r#"
af_version = "0.3"
name = "demo"
vendor = "accelfury"
library = "ip"
core = "demo"
version = "0.1.0"

[rtl]
top = "demo"
language = "verilog-2001"

[sources]
files = ["rtl/demo.v"]

[[clocks]]
name = "clk"
port = "clk"

[[resets]]
name = "rst_n"
port = "rst_n"
active = "low"

[[ports]]
name = "clk"
direction = "input"
width = 1

[[ports]]
name = "rst_n"
direction = "input"
width = 1

[evidence.docker_ci_cd]
run_url = "https://github.com/accelfury/af/actions/runs/123"
commit_sha = "abcdef1234567890"
sha256sums = "deadbeef00000001"
conclusion = "success"
"#,
            "af-core.toml",
        )
        .unwrap();

        let inputs = MaturityInputs {
            manifest: Some(&manifest),
            artifacts: &[],
            warnings: &[],
            limitations: &[],
            ci_evidence: &[],
            current_commit_sha: Some("abcdef1234567890"),
            placeholder_boards: &[],
        };
        let mat = reusable_core_maturity(&inputs);
        let row = mat
            .rows
            .iter()
            .find(|r| r.area == "docker_ci_cd_evidence")
            .unwrap();
        assert_eq!(row.status, "supported");
        assert!(row
            .evidence
            .iter()
            .any(|e| e.contains("declared commit_sha=abcdef1234567890")));
    }

    #[test]
    fn docker_ci_cd_evidence_planned_on_manifest_sha_mismatch() {
        let manifest = CoreManifest::from_toml_str(
            r#"
af_version = "0.3"
name = "demo"
vendor = "accelfury"
library = "ip"
core = "demo"
version = "0.1.0"

[rtl]
top = "demo"
language = "verilog-2001"

[sources]
files = ["rtl/demo.v"]

[[clocks]]
name = "clk"
port = "clk"

[[resets]]
name = "rst_n"
port = "rst_n"
active = "low"

[[ports]]
name = "clk"
direction = "input"
width = 1

[[ports]]
name = "rst_n"
direction = "input"
width = 1

[evidence.docker_ci_cd]
run_url = "https://github.com/accelfury/af/actions/runs/123"
commit_sha = "stale111111"
sha256sums = "deadbeef0"
conclusion = "success"
"#,
            "af-core.toml",
        )
        .unwrap();

        let inputs = MaturityInputs {
            manifest: Some(&manifest),
            artifacts: &[],
            warnings: &[],
            limitations: &[],
            ci_evidence: &[],
            current_commit_sha: Some("abcdef1234567890"),
            placeholder_boards: &[],
        };
        let mat = reusable_core_maturity(&inputs);
        let row = mat
            .rows
            .iter()
            .find(|r| r.area == "docker_ci_cd_evidence")
            .unwrap();
        assert_eq!(row.status, "planned");
        assert!(row.limitations.iter().any(|l| l.contains("stale111111")));
    }

    #[test]
    fn renders_json_snapshot() {
        let json = render_json(&sample_report()).unwrap();
        insta::assert_snapshot!(
            json,
            @r###"
{
  "schema_version": "0.1",
  "kind": "accelfury.report",
  "generated_by": "Generated by AccelFury IP Toolchain",
  "report_version": "0.1",
  "status": "passed",
  "tool_versions": [
    {
      "tool": "af",
      "available": true,
      "version": "0.1.0"
    },
    {
      "tool": "fake",
      "available": true,
      "version": "fake 1.0"
    }
  ],
  "commands": [
    {
      "program": "fake",
      "args": [
        "--version"
      ],
      "exit_code": 0,
      "stdout": "fake 1.0",
      "stderr": "",
      "allow_network": false
    }
  ],
  "artifacts": [
    ".af-build/report.json"
  ],
  "warnings": [
    "warning"
  ],
  "limitations": [
    "limitation"
  ]
}
"###
        );
    }

    #[test]
    fn renders_markdown_snapshot() {
        let markdown = render_markdown(&sample_report());
        insta::assert_snapshot!(
            markdown,
            @r###"
<!-- Generated by AccelFury IP Toolchain -->
# AccelFury Report

- Kind: `accelfury.report`
- Schema version: `0.1`
- Status: `passed`
- Report version: `0.1`

## Tool Versions

- `af`: 0.1.0
- `fake`: fake 1.0

## Commands

- `fake --version` exit=0

## Artifacts

- .af-build/report.json

## Warnings

- warning

## Limitations

- limitation
"###
        );
    }

    fn ci_row(maturity: &ReusableCoreMaturity) -> &MaturityRow {
        maturity
            .rows
            .iter()
            .find(|row| row.area == "docker_ci_cd_evidence")
            .expect("docker_ci_cd_evidence row must be present")
    }

    fn make_record(sha: &str, conclusion: &str) -> CiEvidenceRecord {
        CiEvidenceRecord {
            workflow_run_url: Some(format!(
                "https://github.com/example/repo/actions/runs/{conclusion}"
            )),
            commit_sha: sha.to_string(),
            conclusion: conclusion.to_string(),
            artifact_bundle: Some(".af-build/ci/bundle.tar.gz".to_string()),
            sha256sums: Some(".af-build/ci/SHA256SUMS".to_string()),
            source_path: Some(".af-build/reports/evidence/ci_run_report-x.json".to_string()),
        }
    }

    #[test]
    fn maturity_no_workflow_no_evidence_is_blocked() {
        let artifacts: Vec<String> = Vec::new();
        let inputs = MaturityInputs {
            manifest: None,
            artifacts: &artifacts,
            warnings: &[],
            limitations: &[],
            ci_evidence: &[],
            current_commit_sha: None,
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = ci_row(&maturity);
        assert_eq!(row.status, "blocked");
        assert!(row
            .limitations
            .iter()
            .any(|line| line.contains("No CI configuration or CI run evidence was discovered")));
    }

    #[test]
    fn maturity_workflow_only_blocks_ci_evidence() {
        let artifacts = vec![".github/workflows/hdl-ci.yml".to_string()];
        let inputs = MaturityInputs {
            manifest: None,
            artifacts: &artifacts,
            warnings: &[],
            limitations: &[],
            ci_evidence: &[],
            current_commit_sha: Some("abc1234abc1234abc1234abc1234abc1234abc12"),
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = ci_row(&maturity);
        assert_eq!(row.status, "blocked");
        assert!(row
            .limitations
            .iter()
            .any(|line| line.contains("Workflow file present without an attributable")));
        assert!(row
            .evidence
            .iter()
            .any(|line| line.contains(".github/workflows/hdl-ci.yml")));
    }

    #[test]
    fn maturity_evidence_without_current_sha_blocks() {
        let artifacts = vec![".github/workflows/hdl-ci.yml".to_string()];
        let records = vec![make_record(
            "abc1234abc1234abc1234abc1234abc1234abc12",
            "success",
        )];
        let inputs = MaturityInputs {
            manifest: None,
            artifacts: &artifacts,
            warnings: &[],
            limitations: &[],
            ci_evidence: &records,
            current_commit_sha: None,
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = ci_row(&maturity);
        assert_eq!(row.status, "blocked");
        assert!(row
            .limitations
            .iter()
            .any(|line| line.contains("Cannot determine current commit SHA")));
    }

    #[test]
    fn maturity_stale_ci_evidence_blocks() {
        let artifacts = vec![".github/workflows/hdl-ci.yml".to_string()];
        let records = vec![make_record(
            "1111111111111111111111111111111111111111",
            "success",
        )];
        let inputs = MaturityInputs {
            manifest: None,
            artifacts: &artifacts,
            warnings: &[],
            limitations: &[],
            ci_evidence: &records,
            current_commit_sha: Some("2222222222222222222222222222222222222222"),
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = ci_row(&maturity);
        assert_eq!(row.status, "blocked");
        assert!(row
            .limitations
            .iter()
            .any(|line| line.contains("CI evidence is stale")));
    }

    #[test]
    fn maturity_failed_conclusion_blocks() {
        let artifacts = vec![".github/workflows/hdl-ci.yml".to_string()];
        let records = vec![make_record(
            "3333333333333333333333333333333333333333",
            "failure",
        )];
        let inputs = MaturityInputs {
            manifest: None,
            artifacts: &artifacts,
            warnings: &[],
            limitations: &[],
            ci_evidence: &records,
            current_commit_sha: Some("3333333333333333333333333333333333333333"),
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = ci_row(&maturity);
        assert_eq!(row.status, "blocked");
        assert!(row
            .limitations
            .iter()
            .any(|line| line.contains("concluded as") && line.contains("failure")));
    }

    #[test]
    fn maturity_matching_success_evidence_marks_supported() {
        let artifacts = vec![".github/workflows/hdl-ci.yml".to_string()];
        let records = vec![make_record(
            "deadbeefdeadbeefdeadbeefdeadbeefdeadbeef",
            "success",
        )];
        let inputs = MaturityInputs {
            manifest: None,
            artifacts: &artifacts,
            warnings: &[],
            limitations: &[],
            ci_evidence: &records,
            current_commit_sha: Some("deadbeefdeadbeefdeadbeefdeadbeefdeadbeef"),
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = ci_row(&maturity);
        assert_eq!(row.status, "supported");
        assert!(row
            .evidence
            .iter()
            .any(|line| line.contains("workflow_run_url=")));
        assert!(row.evidence.iter().any(|line| line == "conclusion=success"));
        assert!(row
            .evidence
            .iter()
            .any(|line| line.contains("commit_sha=deadbeefdeadbeefdeadbeefdeadbeefdeadbeef")));
        assert!(row.limitations.is_empty());
    }

    #[test]
    fn maturity_short_sha_prefix_matches() {
        let artifacts = vec![".github/workflows/hdl-ci.yml".to_string()];
        let records = vec![make_record("abc1234", "success")];
        let inputs = MaturityInputs {
            manifest: None,
            artifacts: &artifacts,
            warnings: &[],
            limitations: &[],
            ci_evidence: &records,
            current_commit_sha: Some("abc1234deadbeefdeadbeefdeadbeefdeadbeefa"),
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = ci_row(&maturity);
        assert_eq!(row.status, "supported");
    }

    #[test]
    fn sha_matches_rejects_short_prefixes() {
        assert!(!sha_matches("abcd", "abcdef1234"));
        assert!(!sha_matches("", "abcdef1234"));
        assert!(!sha_matches("abcd123", ""));
    }

    fn manifest_with_boards(boards: &[&str]) -> CoreManifest {
        let board_array = boards
            .iter()
            .map(|b| format!("\"{b}\""))
            .collect::<Vec<_>>()
            .join(", ");
        let raw = format!(
            r#"
af_version = "0.1"
name = "demo"
vendor = "accelfury"
library = "ip"
core = "demo"
version = "0.1.0"
boards = [{board_array}]

[rtl]
top = "demo"
language = "verilog-2001"

[sources]
files = ["rtl/demo.v"]
"#,
        );
        CoreManifest::from_toml_str(&raw, std::path::Path::new("af-core.toml")).unwrap()
    }

    fn board_row(maturity: &ReusableCoreMaturity) -> &MaturityRow {
        maturity
            .rows
            .iter()
            .find(|row| row.area == "board_hardware_evidence")
            .expect("board_hardware_evidence row must be present")
    }

    #[test]
    fn board_evidence_not_applicable_when_manifest_has_no_boards() {
        let manifest = manifest_with_boards(&[]);
        let inputs = MaturityInputs {
            manifest: Some(&manifest),
            artifacts: &[],
            warnings: &[],
            limitations: &[],
            ci_evidence: &[],
            current_commit_sha: None,
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = board_row(&maturity);
        assert_eq!(row.status, "not-applicable");
        assert!(row.evidence.is_empty());
    }

    #[test]
    fn board_evidence_lists_placeholder_boards_explicitly() {
        let manifest = manifest_with_boards(&["sipeed_tang_nano_1k", "tang_nano_20k"]);
        let placeholders = vec!["sipeed_tang_nano_1k".to_string()];
        let inputs = MaturityInputs {
            manifest: Some(&manifest),
            artifacts: &[],
            warnings: &[],
            limitations: &[],
            ci_evidence: &[],
            current_commit_sha: None,
            placeholder_boards: &placeholders,
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = board_row(&maturity);
        assert_eq!(row.status, "planned");
        assert!(row
            .evidence
            .iter()
            .any(|line| line.contains("sipeed_tang_nano_1k") && line.contains("(draft)")));
        assert!(row
            .evidence
            .iter()
            .any(|line| line.contains("tang_nano_20k") && line.contains("(verified-or-unknown)")));
        assert!(
            row.limitations
                .iter()
                .any(|line| line.contains("sipeed_tang_nano_1k")
                    && line.contains("draft_placeholder"))
        );
    }

    #[test]
    fn board_evidence_no_placeholder_warning_when_all_verified() {
        let manifest = manifest_with_boards(&["tang_nano_20k"]);
        let inputs = MaturityInputs {
            manifest: Some(&manifest),
            artifacts: &[],
            warnings: &[],
            limitations: &[],
            ci_evidence: &[],
            current_commit_sha: None,
            placeholder_boards: &[],
        };
        let maturity = reusable_core_maturity(&inputs);
        let row = board_row(&maturity);
        assert_eq!(row.status, "planned");
        // Only the generic limitation remains; no placeholder-specific warning.
        assert_eq!(row.limitations.len(), 1);
        assert!(row.limitations[0].contains("Declared board support"));
    }
}
