// SPDX-License-Identifier: Apache-2.0
use af_backend::{BackendReport, CommandRecord, ToolVersion};
use af_manifest::CoreManifest;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};
use thiserror::Error;

pub const GENERATED_BY: &str = "Generated by AccelFury IP Toolchain";

#[derive(Debug, Error)]
pub enum ReportError {
    #[error("failed to serialize report: {message}")]
    Serialize { message: String },
    #[error("failed to create report directory `{path}`: {message}")]
    CreateDir { path: PathBuf, message: String },
    #[error("failed to write report `{path}`: {message}")]
    Write { path: PathBuf, message: String },
}

impl ReportError {
    pub fn code(&self) -> &'static str {
        match self {
            ReportError::Serialize { .. } => "AF_REPORT_SERIALIZE_FAILED",
            ReportError::CreateDir { .. } => "AF_REPORT_CREATE_DIR_FAILED",
            ReportError::Write { .. } => "AF_REPORT_WRITE_FAILED",
        }
    }

    pub fn hint(&self) -> &'static str {
        match self {
            ReportError::Serialize { .. } => "Check report data for unsupported values.",
            ReportError::CreateDir { .. } | ReportError::Write { .. } => {
                "Check filesystem permissions and the selected build root."
            }
        }
    }

    pub fn exit_code(&self) -> i32 {
        5
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct CoreIdentity {
    pub name: String,
    pub vendor: String,
    pub library: String,
    pub core: String,
    pub version: String,
    pub vlnv: String,
}

impl From<&CoreManifest> for CoreIdentity {
    fn from(manifest: &CoreManifest) -> Self {
        Self {
            name: manifest.name.clone(),
            vendor: manifest.vendor.clone(),
            library: manifest.library.clone(),
            core: manifest.core.clone(),
            version: manifest.version.clone(),
            vlnv: manifest.vlnv(),
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct AfReport {
    pub schema_version: String,
    pub kind: String,
    pub generated_by: String,
    pub report_version: String,
    pub status: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub core: Option<CoreIdentity>,
    #[serde(default)]
    pub tool_versions: Vec<ToolVersion>,
    #[serde(default)]
    pub commands: Vec<CommandRecord>,
    #[serde(default)]
    pub artifacts: Vec<String>,
    #[serde(default)]
    pub warnings: Vec<String>,
    #[serde(default)]
    pub limitations: Vec<String>,
}

impl AfReport {
    pub fn new(status: impl Into<String>) -> Self {
        Self {
            schema_version: "0.1".to_string(),
            kind: "accelfury.report".to_string(),
            generated_by: GENERATED_BY.to_string(),
            report_version: "0.1".to_string(),
            status: status.into(),
            core: None,
            tool_versions: vec![ToolVersion::available("af", env!("CARGO_PKG_VERSION"))],
            commands: Vec::new(),
            artifacts: Vec::new(),
            warnings: Vec::new(),
            limitations: Vec::new(),
        }
    }

    pub fn for_core(status: impl Into<String>, manifest: &CoreManifest) -> Self {
        let mut report = Self::new(status);
        report.core = Some(CoreIdentity::from(manifest));
        report
            .limitations
            .extend(manifest.known_limitations.clone());
        report
    }

    pub fn merge_backend(&mut self, backend: &BackendReport) {
        self.tool_versions
            .extend(backend.tool_versions.iter().cloned());
        self.commands.extend(backend.commands.iter().cloned());
        self.artifacts.extend(
            backend
                .artifacts
                .iter()
                .map(|path| path.display().to_string()),
        );
        self.warnings.extend(backend.warnings.iter().cloned());
        self.limitations.extend(backend.limitations.iter().cloned());
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct WrittenReports {
    pub json: PathBuf,
    pub markdown: PathBuf,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct Artifact {
    pub generated_by: String,
    pub timestamp: String,
    pub label: String,
    pub content: String,
}

pub fn render_json(report: &AfReport) -> Result<String, ReportError> {
    serde_json::to_string_pretty(report).map_err(|err| ReportError::Serialize {
        message: err.to_string(),
    })
}

pub fn render_markdown(report: &AfReport) -> String {
    let mut out = String::new();
    out.push_str("<!-- ");
    out.push_str(GENERATED_BY);
    out.push_str(" -->\n");
    out.push_str("# AccelFury Report\n\n");
    out.push_str(&format!("- Kind: `{}`\n", report.kind));
    out.push_str(&format!("- Schema version: `{}`\n", report.schema_version));
    out.push_str(&format!("- Status: `{}`\n", report.status));
    out.push_str(&format!("- Report version: `{}`\n", report.report_version));
    if let Some(core) = &report.core {
        out.push_str(&format!("- Core: `{}`\n", core.vlnv));
    }

    write_section(
        &mut out,
        "Tool Versions",
        &tool_version_lines(&report.tool_versions),
    );
    write_section(&mut out, "Commands", &command_lines(&report.commands));
    write_section(&mut out, "Artifacts", &report.artifacts);
    write_section(&mut out, "Warnings", &report.warnings);
    write_section(&mut out, "Limitations", &report.limitations);
    out
}

pub fn write_reports(
    output_dir: impl AsRef<Path>,
    base_name: &str,
    report: &AfReport,
) -> Result<WrittenReports, ReportError> {
    let output_dir = output_dir.as_ref();
    fs::create_dir_all(output_dir).map_err(|err| ReportError::CreateDir {
        path: output_dir.to_path_buf(),
        message: err.to_string(),
    })?;

    let json = output_dir.join(format!("{base_name}.json"));
    let markdown = output_dir.join(format!("{base_name}.md"));
    let json_content = render_json(report)?;
    let markdown_content = render_markdown(report);
    fs::write(&json, json_content).map_err(|err| ReportError::Write {
        path: json.clone(),
        message: err.to_string(),
    })?;
    fs::write(&markdown, markdown_content).map_err(|err| ReportError::Write {
        path: markdown.clone(),
        message: err.to_string(),
    })?;
    Ok(WrittenReports { json, markdown })
}

pub fn collect_report(label: &str, content: &str) -> Result<Artifact, ReportError> {
    let now = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|err| ReportError::Serialize {
            message: err.to_string(),
        })?
        .as_secs();
    Ok(Artifact {
        generated_by: GENERATED_BY.to_string(),
        timestamp: now.to_string(),
        label: label.to_string(),
        content: content.to_string(),
    })
}

pub fn save_report(artifact: &Artifact, dir: impl AsRef<Path>) -> Result<PathBuf, ReportError> {
    let dir = dir.as_ref();
    fs::create_dir_all(dir).map_err(|err| ReportError::CreateDir {
        path: dir.to_path_buf(),
        message: err.to_string(),
    })?;
    let path = dir.join(format!("{}_{}.json", artifact.label, artifact.timestamp));
    let payload = serde_json::to_string_pretty(artifact).map_err(|err| ReportError::Serialize {
        message: err.to_string(),
    })?;
    fs::write(&path, payload).map_err(|err| ReportError::Write {
        path: path.clone(),
        message: err.to_string(),
    })?;
    Ok(path)
}

fn write_section(out: &mut String, title: &str, values: &[String]) {
    out.push('\n');
    out.push_str("## ");
    out.push_str(title);
    out.push_str("\n\n");
    if values.is_empty() {
        out.push_str("- None\n");
    } else {
        for value in values {
            out.push_str("- ");
            out.push_str(value);
            out.push('\n');
        }
    }
}

fn tool_version_lines(versions: &[ToolVersion]) -> Vec<String> {
    versions
        .iter()
        .map(|version| {
            if version.available {
                format!(
                    "`{}`: {}",
                    version.tool,
                    version.version.as_deref().unwrap_or("available")
                )
            } else {
                format!(
                    "`{}`: unavailable ({})",
                    version.tool,
                    version.message.as_deref().unwrap_or("no detail")
                )
            }
        })
        .collect()
}

fn command_lines(commands: &[CommandRecord]) -> Vec<String> {
    commands
        .iter()
        .map(|command| {
            let argv = std::iter::once(command.program.as_str())
                .chain(command.args.iter().map(String::as_str))
                .collect::<Vec<_>>()
                .join(" ");
            format!(
                "`{argv}` exit={}",
                command
                    .exit_code
                    .map(|code| code.to_string())
                    .unwrap_or_else(|| "signal".to_string())
            )
        })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use af_backend::{BackendStatus, CommandRecord, ToolVersion};

    fn sample_report() -> AfReport {
        let mut report = AfReport::new("passed");
        let mut backend = BackendReport::new("fake", BackendStatus::Passed);
        backend.tool_versions = vec![ToolVersion::available("fake", "fake 1.0")];
        backend.commands = vec![CommandRecord {
            program: "fake".to_string(),
            args: vec!["--version".to_string()],
            cwd: None,
            exit_code: Some(0),
            stdout: "fake 1.0".to_string(),
            stderr: String::new(),
            env: Default::default(),
            allow_network: false,
            timeout_seconds: None,
        }];
        backend.artifacts = vec![PathBuf::from(".af-build/report.json")];
        backend.warnings = vec!["warning".to_string()];
        backend.limitations = vec!["limitation".to_string()];
        report.merge_backend(&backend);
        report
    }

    #[test]
    fn renders_json_snapshot() {
        let json = render_json(&sample_report()).unwrap();
        insta::assert_snapshot!(
            json,
            @r###"
{
  "schema_version": "0.1",
  "kind": "accelfury.report",
  "generated_by": "Generated by AccelFury IP Toolchain",
  "report_version": "0.1",
  "status": "passed",
  "tool_versions": [
    {
      "tool": "af",
      "available": true,
      "version": "0.1.0"
    },
    {
      "tool": "fake",
      "available": true,
      "version": "fake 1.0"
    }
  ],
  "commands": [
    {
      "program": "fake",
      "args": [
        "--version"
      ],
      "exit_code": 0,
      "stdout": "fake 1.0",
      "stderr": "",
      "allow_network": false
    }
  ],
  "artifacts": [
    ".af-build/report.json"
  ],
  "warnings": [
    "warning"
  ],
  "limitations": [
    "limitation"
  ]
}
"###
        );
    }

    #[test]
    fn renders_markdown_snapshot() {
        let markdown = render_markdown(&sample_report());
        insta::assert_snapshot!(
            markdown,
            @r###"
<!-- Generated by AccelFury IP Toolchain -->
# AccelFury Report

- Kind: `accelfury.report`
- Schema version: `0.1`
- Status: `passed`
- Report version: `0.1`

## Tool Versions

- `af`: 0.1.0
- `fake`: fake 1.0

## Commands

- `fake --version` exit=0

## Artifacts

- .af-build/report.json

## Warnings

- warning

## Limitations

- limitation
"###
        );
    }
}
