// SPDX-License-Identifier: Apache-2.0
use af_manifest::CoreManifest;
use serde::{Deserialize, Serialize};
use serde_json::{json, Value};
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct ConstructorExportReport {
    pub generated_by: String,
    pub status: String,
    pub input: PathBuf,
    pub output: PathBuf,
    pub files: Vec<PathBuf>,
    pub warnings: Vec<String>,
    pub limitations: Vec<String>,
}

#[derive(Debug, Error)]
pub enum ConstructorExportError {
    #[error(transparent)]
    Manifest(#[from] af_manifest::ManifestError),
    #[error("failed to create `{path}`: {message}")]
    CreateDir { path: PathBuf, message: String },
    #[error("failed to write `{path}`: {message}")]
    Write { path: PathBuf, message: String },
}

impl ConstructorExportError {
    pub fn code(&self) -> &'static str {
        match self {
            Self::Manifest(err) => err.code(),
            Self::CreateDir { .. } | Self::Write { .. } => "AF_CONSTRUCTOR_EXPORT_WRITE_FAILED",
        }
    }

    pub fn hint(&self) -> &'static str {
        match self {
            Self::Manifest(err) => err.hint(),
            Self::CreateDir { .. } | Self::Write { .. } => {
                "Check output directory permissions and remove conflicting files."
            }
        }
    }

    pub fn exit_code(&self) -> i32 {
        match self {
            Self::Manifest(err) => err.exit_code(),
            Self::CreateDir { .. } | Self::Write { .. } => 5,
        }
    }
}

pub fn export_constructor_package(
    input: impl AsRef<Path>,
    output: impl AsRef<Path>,
    catalog: bool,
) -> Result<ConstructorExportReport, ConstructorExportError> {
    let input = input.as_ref();
    let output = output.as_ref();
    fs::create_dir_all(output).map_err(|err| ConstructorExportError::CreateDir {
        path: output.to_path_buf(),
        message: err.to_string(),
    })?;

    let manifest = if input.join("af-core.toml").is_file() {
        Some(CoreManifest::from_path(input.join("af-core.toml"))?)
    } else {
        None
    };

    let mut warnings = Vec::new();
    if manifest.is_none() {
        warnings.push(
            "AF_CONSTRUCTOR_EXPORT_INCOMPLETE: system/product graph export is metadata-only in the first release".to_string(),
        );
    }
    let limitations = manifest
        .as_ref()
        .map(|manifest| {
            if manifest.known_limitations.is_empty() {
                vec!["No known_limitations were declared in the source manifest.".to_string()]
            } else {
                manifest.known_limitations.clone()
            }
        })
        .unwrap_or_else(|| {
            vec![
                "Catalog/system export skeleton; dependency resolution is not executed."
                    .to_string(),
            ]
        });

    let files = constructor_files()
        .into_iter()
        .map(|name| {
            let path = output.join(name);
            let payload =
                constructor_payload(name, input, manifest.as_ref(), catalog, &limitations);
            write_json(&path, &payload)?;
            Ok(path)
        })
        .collect::<Result<Vec<_>, ConstructorExportError>>()?;

    Ok(ConstructorExportReport {
        generated_by: "Generated by AccelFury IP Toolchain".to_string(),
        status: if warnings.is_empty() {
            "passed".to_string()
        } else {
            "warning".to_string()
        },
        input: input.to_path_buf(),
        output: output.to_path_buf(),
        files,
        warnings,
        limitations,
    })
}

fn constructor_files() -> Vec<&'static str> {
    vec![
        "core.json",
        "interfaces.json",
        "parameters.json",
        "compatibility.json",
        "resources.json",
        "variants.json",
        "dependencies.json",
        "reports.json",
        "limitations.json",
    ]
}

fn constructor_payload(
    name: &str,
    input: &Path,
    manifest: Option<&CoreManifest>,
    catalog: bool,
    limitations: &[String],
) -> Value {
    match name {
        "core.json" => json!({
            "schema": "af.constructor.core.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "catalog": catalog,
            "input": input,
            "core": manifest.map(|manifest| json!({
                "name": manifest.name,
                "vendor": manifest.vendor,
                "library": manifest.library,
                "core": manifest.core,
                "version": manifest.version,
                "class": manifest.complexity.as_ref().map(|complexity| complexity.class.as_str()),
                "top": manifest.rtl.top,
            })),
        }),
        "interfaces.json" => json!({
            "schema": "af.constructor.interfaces.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "interfaces": manifest.map(|manifest| &manifest.interfaces),
            "stream_interfaces": manifest.map(|manifest| &manifest.stream_interfaces),
        }),
        "parameters.json" => json!({
            "schema": "af.constructor.parameters.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "parameters": manifest.map(|manifest| &manifest.parameters),
        }),
        "compatibility.json" => json!({
            "schema": "af.constructor.compatibility.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "profile": manifest.and_then(|manifest| manifest.constructor.as_ref()).and_then(|constructor| constructor.compatibility_profile.as_deref()),
            "backpressure": "manifest_level",
            "adapters": [],
        }),
        "resources.json" => json!({
            "schema": "af.constructor.resources.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "resources": manifest.map(|manifest| &manifest.resources),
        }),
        "variants.json" => json!({
            "schema": "af.constructor.variants.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "backend_variants": manifest.map(|manifest| &manifest.backend_variants),
        }),
        "dependencies.json" => json!({
            "schema": "af.constructor.dependencies.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "dependencies": manifest.map(|manifest| &manifest.dependencies),
        }),
        "reports.json" => json!({
            "schema": "af.constructor.reports.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "reports": [],
            "status": "metadata_skeleton",
        }),
        "limitations.json" => json!({
            "schema": "af.constructor.limitations.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
            "limitations": limitations,
        }),
        _ => json!({
            "schema": "af.constructor.unknown.v1",
            "generated_by": "Generated by AccelFury IP Toolchain",
        }),
    }
}

fn write_json(path: &Path, payload: &Value) -> Result<(), ConstructorExportError> {
    let text =
        serde_json::to_string_pretty(payload).map_err(|err| ConstructorExportError::Write {
            path: path.to_path_buf(),
            message: err.to_string(),
        })?;
    fs::write(path, format!("{text}\n")).map_err(|err| ConstructorExportError::Write {
        path: path.to_path_buf(),
        message: err.to_string(),
    })
}

// ============================================================================
// Constructor assemble v1 (minimal): multi-core + board → buildable FuseSoC
// project. No automatic port-wiring or topology resolution — that is v2.
// ============================================================================

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct AssembleReport {
    pub generated_by: String,
    pub status: String,
    pub name: String,
    pub board: String,
    pub toolchain: String,
    pub cores: Vec<String>,
    pub output: PathBuf,
    pub files: Vec<PathBuf>,
    pub warnings: Vec<String>,
    pub limitations: Vec<String>,
}

#[derive(Debug, Error)]
pub enum AssembleError {
    #[error(transparent)]
    Manifest(#[from] af_manifest::ManifestError),
    #[error(transparent)]
    Board(#[from] af_board_db::BoardDbError),
    #[error("no core directories supplied to constructor assemble")]
    NoCores,
    #[error("board `{board}` not found in registries/boards.registry.json")]
    BoardUnknown { board: String },
    #[error("failed to create `{path}`: {message}")]
    CreateDir { path: PathBuf, message: String },
    #[error("failed to write `{path}`: {message}")]
    Write { path: PathBuf, message: String },
}

impl AssembleError {
    pub fn code(&self) -> &'static str {
        match self {
            Self::Manifest(err) => err.code(),
            Self::Board(err) => err.code(),
            Self::NoCores => "AF_CONSTRUCTOR_ASSEMBLE_NO_CORES",
            Self::BoardUnknown { .. } => "AF_CONSTRUCTOR_ASSEMBLE_BOARD_UNKNOWN",
            Self::CreateDir { .. } | Self::Write { .. } => "AF_CONSTRUCTOR_ASSEMBLE_WRITE_FAILED",
        }
    }

    pub fn hint(&self) -> &'static str {
        match self {
            Self::Manifest(err) => err.hint(),
            Self::Board(err) => err.hint(),
            Self::NoCores => "Pass one or more core directories that contain af-core.toml.",
            Self::BoardUnknown { .. } => {
                "Use `af board list` to discover declared board ids; aliases live in registries/board_aliases.json."
            }
            Self::CreateDir { .. } | Self::Write { .. } => {
                "Check output directory permissions and remove conflicting files."
            }
        }
    }

    pub fn exit_code(&self) -> i32 {
        match self {
            Self::Manifest(err) => err.exit_code(),
            Self::Board(err) => err.exit_code(),
            Self::NoCores | Self::BoardUnknown { .. } => 2,
            Self::CreateDir { .. } | Self::Write { .. } => 5,
        }
    }
}

/// Assemble a buildable FuseSoC project from one or more cores and a board.
///
/// Minimum v1: writes `<output>/<name>.core`, `<output>/Makefile`,
/// `<output>/README.md`. Does **not** perform automatic port-wiring or
/// topology resolution — every constituent core appears as a filesets
/// entry and a depend. Engineers wire ports manually in a top-level RTL.
pub fn assemble_project(
    cores: &[PathBuf],
    board_id: &str,
    name: &str,
    output: impl AsRef<Path>,
    registry_root: impl AsRef<Path>,
) -> Result<AssembleReport, AssembleError> {
    if cores.is_empty() {
        return Err(AssembleError::NoCores);
    }
    let output = output.as_ref();
    fs::create_dir_all(output).map_err(|err| AssembleError::CreateDir {
        path: output.to_path_buf(),
        message: err.to_string(),
    })?;

    let manifests: Vec<(PathBuf, CoreManifest)> = cores
        .iter()
        .map(|core_dir| {
            let manifest = CoreManifest::from_path(core_dir.join("af-core.toml"))?;
            Ok::<_, AssembleError>((core_dir.clone(), manifest))
        })
        .collect::<Result<_, _>>()?;

    let boards = af_board_db::list_boards(&registry_root)?;
    // Resolve aliases (e.g. `tang-nano-20k` -> `sipeed_tang_nano_20k`).
    let aliases_path = registry_root.as_ref().join("registries/board_aliases.json");
    let resolved_id = if aliases_path.is_file() {
        let aliases = af_board_db::load_board_aliases(&aliases_path)?;
        aliases
            .into_iter()
            .find(|a| a.alias == board_id)
            .map(|a| a.canonical)
            .unwrap_or_else(|| board_id.to_string())
    } else {
        board_id.to_string()
    };
    let Some(board) = boards.into_iter().find(|b| b.board_id == resolved_id) else {
        return Err(AssembleError::BoardUnknown {
            board: board_id.to_string(),
        });
    };

    let toolchain = board.default_toolchain.clone();
    let mut warnings: Vec<String> = Vec::new();
    if board.exact_pinout_status != "verified" {
        warnings.push(format!(
            "Board `{}` pinout status is `{}` (not `verified`); assembled project carries this risk.",
            board.board_id, board.exact_pinout_status
        ));
    }

    let mut limitations: Vec<String> = vec![
        "Constructor v1 does not wire ports between cores automatically. Add a top-level RTL that instantiates each core and routes signals.".to_string(),
        "Constructor v1 does not run clock-domain-crossing inference. Declare CDC crossings in af-arch.toml on the composite project.".to_string(),
        "Constructor v1 does not produce a bitstream. The generated Makefile delegates `make synth` to FuseSoC + Edalize; vendor tool availability is the user's responsibility.".to_string(),
    ];
    for (_, manifest) in &manifests {
        limitations.extend(manifest.known_limitations.iter().cloned());
    }
    limitations.sort();
    limitations.dedup();

    let core_path = output.join(format!("{name}.core"));
    let makefile_path = output.join("Makefile");
    let readme_path = output.join("README.md");

    let core_content = render_fusesoc_core(name, &board.board_id, &toolchain, &manifests);
    write_text(&core_path, &core_content)?;

    let makefile = render_makefile(name);
    write_text(&makefile_path, &makefile)?;

    let readme = render_readme(name, &board, &toolchain, &manifests, &limitations);
    write_text(&readme_path, &readme)?;

    Ok(AssembleReport {
        generated_by: "Generated by AccelFury IP Toolchain".to_string(),
        status: "passed".to_string(),
        name: name.to_string(),
        board: board_id.to_string(),
        toolchain,
        cores: manifests.iter().map(|(_, m)| m.vlnv()).collect(),
        output: output.to_path_buf(),
        files: vec![core_path, makefile_path, readme_path],
        warnings,
        limitations,
    })
}

fn render_fusesoc_core(
    name: &str,
    board_id: &str,
    toolchain: &str,
    manifests: &[(PathBuf, CoreManifest)],
) -> String {
    let depends: Vec<String> = manifests
        .iter()
        .map(|(_, m)| {
            format!(
                "    - {}::{}::{}::{}",
                m.vendor, m.library, m.core, m.version
            )
        })
        .collect();
    let mut filesets = String::new();
    for (path, m) in manifests {
        let core_id = format!("{}_{}", m.vendor, m.core);
        filesets.push_str(&format!("  {core_id}:\n    files:\n"));
        for src in &m.sources.files {
            filesets.push_str(&format!("      - {}\n", path.join(src).display()));
        }
        filesets.push_str(&format!("    file_type: {}\n", m.rtl.language));
    }
    let toolchain_line = match toolchain {
        "vivado" => "    tool: vivado",
        "quartus" => "    tool: quartus",
        "gowin_eda" | "gowin" => "    tool: gowin",
        "lattice_oss" | "icestorm" => "    tool: icestorm",
        "efinix_efinity" => "    tool: efinity",
        "microchip_libero" => "    tool: libero",
        _ => "    tool: yosys",
    };
    format!(
        r#"# Generated by AccelFury IP Toolchain
CAPI=2:
name: ::{name}:0.1.0
description: AccelFury assembled project for board `{board_id}` (toolchain `{toolchain}`).

filesets:
{filesets}
targets:
  default:
    filesets:
{filesets_ref}    description: Default synthesis target on `{board_id}`.
{toolchain_line}

depend:
{depends}
"#,
        filesets_ref = manifests
            .iter()
            .map(|(_, m)| format!("      - {}_{}\n", m.vendor, m.core))
            .collect::<String>(),
        depends = depends.join("\n"),
    )
}

fn render_makefile(name: &str) -> String {
    format!(
        r#"# Generated by AccelFury IP Toolchain
NAME := {name}

.PHONY: sim synth clean

sim:
	fusesoc run --target=sim $(NAME)

synth:
	fusesoc run --target=default $(NAME)

clean:
	rm -rf build
"#
    )
}

fn render_readme(
    name: &str,
    board: &af_board_db::BoardEntry,
    toolchain: &str,
    manifests: &[(PathBuf, CoreManifest)],
    limitations: &[String],
) -> String {
    let core_lines: Vec<String> = manifests
        .iter()
        .map(|(p, m)| format!("- `{}` ({}, top `{}`)", m.vlnv(), p.display(), m.rtl.top))
        .collect();
    let limitation_lines: Vec<String> = limitations.iter().map(|l| format!("- {l}")).collect();
    format!(
        r#"<!-- Generated by AccelFury IP Toolchain -->
# {name}

AccelFury constructor-assembled project.

- Board: `{board_id}` ({display_name}, vendor `{vendor}`, family `{family}`)
- Default toolchain: `{toolchain}`
- Pinout status: `{pinout}`

## Cores

{cores}

## Build

```bash
make sim     # FuseSoC simulation target
make synth   # FuseSoC default (synthesis) target
make clean
```

## Limitations

{limitations}
"#,
        name = name,
        board_id = board.board_id,
        display_name = board.display_name,
        vendor = board.vendor,
        family = board.fpga_family,
        toolchain = toolchain,
        pinout = board.exact_pinout_status,
        cores = core_lines.join("\n"),
        limitations = limitation_lines.join("\n"),
    )
}

fn write_text(path: &Path, content: &str) -> Result<(), AssembleError> {
    fs::write(path, content).map_err(|err| AssembleError::Write {
        path: path.to_path_buf(),
        message: err.to_string(),
    })
}
