// SPDX-License-Identifier: Apache-2.0
//
// `generate_core(manifest)` → FuseSoC `.core` YAML string;
// `write_core(manifest, dir)` writes it to disk. The integration tests
// pin the VLNV identifier, fileset structure, and round-trip equality.

use af_backend_fusesoc::{generate_core, write_core};
use af_manifest::CoreManifest;
use std::path::{Path, PathBuf};
use tempfile::TempDir;

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .ancestors()
        .nth(2)
        .unwrap()
        .to_path_buf()
}

fn mod_add() -> (PathBuf, CoreManifest) {
    let core_dir = repo_root().join("examples").join("af-mod-add");
    let manifest = CoreManifest::from_path(core_dir.join("af-core.toml")).expect("manifest");
    (core_dir, manifest)
}

#[test]
fn generate_core_yaml_starts_with_capi2_header() {
    let (_core, manifest) = mod_add();
    let yaml = generate_core(&manifest);
    let trimmed: Vec<&str> = yaml.lines().take(3).collect();
    assert!(
        trimmed.iter().any(|l| l.contains("Generated by")),
        "must carry generated-by stamp"
    );
    assert!(
        trimmed.iter().any(|l| l.starts_with("CAPI=2:")),
        "second line must declare CAPI=2"
    );
}

#[test]
fn generate_core_yaml_includes_vlnv_name() {
    let (_core, manifest) = mod_add();
    let yaml = generate_core(&manifest);
    let vlnv = manifest.vlnv();
    assert!(
        yaml.lines().any(|l| l.contains(&vlnv)),
        "yaml must reference VLNV `{vlnv}`"
    );
}

#[test]
fn generate_core_lists_every_rtl_source() {
    let (_core, manifest) = mod_add();
    let yaml = generate_core(&manifest);
    for source in &manifest.sources.files {
        assert!(
            yaml.contains(source),
            "source `{source}` missing from generated yaml"
        );
    }
}

#[test]
fn generate_core_emits_toplevel_for_default_target() {
    let (_core, manifest) = mod_add();
    let yaml = generate_core(&manifest);
    let top = &manifest.rtl.top;
    let needle = format!("toplevel: '{top}'");
    assert!(
        yaml.contains(&needle),
        "yaml must declare `{needle}` for default target"
    );
}

#[test]
fn write_core_writes_yaml_identical_to_generate_core() {
    let (_core, manifest) = mod_add();
    let out = TempDir::new().unwrap();
    let artifact = write_core(&manifest, out.path()).expect("write succeeds");
    let on_disk = std::fs::read_to_string(&artifact.path).unwrap();
    let in_memory = generate_core(&manifest);
    assert_eq!(
        on_disk, in_memory,
        "write_core must round-trip generate_core verbatim"
    );
}

#[test]
fn write_core_filename_is_sanitised_to_core_extension() {
    let (_core, manifest) = mod_add();
    let out = TempDir::new().unwrap();
    let artifact = write_core(&manifest, out.path()).expect("write");
    assert_eq!(
        artifact.path.extension().and_then(|e| e.to_str()),
        Some("core")
    );
}

#[test]
fn write_core_is_byte_deterministic_across_runs() {
    let (_core, manifest) = mod_add();
    let a = TempDir::new().unwrap();
    let b = TempDir::new().unwrap();
    let pa = write_core(&manifest, a.path()).unwrap().path;
    let pb = write_core(&manifest, b.path()).unwrap().path;
    let ya = std::fs::read(&pa).unwrap();
    let yb = std::fs::read(&pb).unwrap();
    assert_eq!(ya, yb, "FuseSoC core bytes must be deterministic");
}
