// SPDX-License-Identifier: Apache-2.0
//
// Integration tests for `af-ci::generate*` workflow emission.
//
// Public contract:
//   * `generate("github-actions")` ⇒ String containing a GitHub Actions
//     YAML workflow with the documented backend jobs.
//   * `generate_with_options(target, opts)` honors `backends` filter and
//     `optional_fail_closed` flag.
//   * Unknown target ⇒ `AF_CI_TARGET_UNSUPPORTED`.
//   * Unknown backend in the filter list ⇒ `AF_CI_BACKEND_UNSUPPORTED`.
//   * `write_with_options(...)` writes the rendered YAML to disk under
//     the requested path.

use af_ci::{generate, generate_with_options, write_with_options, CiGenerateOptions};
use std::fs;
use tempfile::TempDir;

#[test]
fn default_generation_lists_documented_backends() {
    let yaml = generate("github-actions").expect("default generation must succeed");
    assert!(
        yaml.contains("Generated by AccelFury IP Toolchain"),
        "workflow must carry the generated-by marker"
    );
    // Each documented backend appears as a job label.
    for label in [
        "native-lint",
        "icarus-lint",
        "verilator-lint-sim",
        "yosys-lint",
        "sby-formal",
        "nextpnr-doctor",
        "litex-wrapper",
    ] {
        assert!(
            yaml.contains(label),
            "default workflow must include job `{label}`; missing in:\n{yaml}"
        );
    }
}

#[test]
fn filter_to_single_backend_excludes_the_others() {
    let opts = CiGenerateOptions {
        backends: vec!["yosys".to_string()],
        optional_fail_closed: false,
    };
    let yaml = generate_with_options("github-actions", &opts).expect("filtered generation");
    assert!(
        yaml.contains("yosys"),
        "filtered yosys workflow must mention yosys"
    );
    // Other optional backends must not appear as job labels.
    for label in ["icarus-lint", "verilator-lint-sim", "sby-formal"] {
        assert!(
            !yaml.contains(label),
            "filtered workflow must exclude `{label}`; full yaml:\n{yaml}"
        );
    }
}

#[test]
fn unknown_target_returns_envelope_code() {
    let err = generate("circleci-pretend-version").unwrap_err();
    assert_eq!(err.code(), "AF_CI_TARGET_UNSUPPORTED");
    assert_eq!(err.exit_code(), 2);
    assert!(err.hint().contains("github-actions"));
}

#[test]
fn unknown_backend_in_filter_returns_envelope_code() {
    let opts = CiGenerateOptions {
        backends: vec!["totally-fake-backend".to_string()],
        optional_fail_closed: false,
    };
    let err = generate_with_options("github-actions", &opts).unwrap_err();
    assert_eq!(err.code(), "AF_CI_BACKEND_UNSUPPORTED");
    assert_eq!(err.exit_code(), 2);
}

#[test]
fn optional_fail_closed_changes_workflow_text() {
    let lax = generate_with_options(
        "github-actions",
        &CiGenerateOptions {
            backends: vec![],
            optional_fail_closed: false,
        },
    )
    .unwrap();
    let strict = generate_with_options(
        "github-actions",
        &CiGenerateOptions {
            backends: vec![],
            optional_fail_closed: true,
        },
    )
    .unwrap();
    assert_ne!(
        lax, strict,
        "optional_fail_closed must observably change the rendered YAML"
    );
}

#[test]
fn write_with_options_persists_yaml_under_output_path() {
    let tmp = TempDir::new().unwrap();
    let out = tmp.path().join("workflows/ci.yml");
    let artifact = write_with_options(
        "github-actions",
        &out,
        &CiGenerateOptions {
            backends: vec!["native".to_string(), "yosys".to_string()],
            optional_fail_closed: false,
        },
    )
    .expect("write must succeed");
    assert_eq!(artifact.path, out);
    assert!(out.is_file());
    let written = fs::read_to_string(&out).unwrap();
    assert_eq!(written, artifact.content);
    assert!(written.contains("native-lint"));
    assert!(written.contains("yosys-lint"));
}

#[test]
fn generation_is_deterministic_for_same_inputs() {
    let a = generate("github-actions").unwrap();
    let b = generate("github-actions").unwrap();
    assert_eq!(a, b, "CI generation must be byte-deterministic");
}
