// SPDX-License-Identifier: Apache-2.0
use af_complexity::ProjectClass;
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

/// Stamp marker used at the head of every file emitted by this crate, to honour
/// the dev-roadmap M0 contract "all generated files carry `Generated by
/// AccelFury IP Toolchain`".
pub const GENERATED_BY_MARKER: &str = "Generated by AccelFury IP Toolchain";

fn stamp_toml(content: &str) -> String {
    format!("# {GENERATED_BY_MARKER}\n{content}")
}

fn stamp_markdown(content: &str) -> String {
    format!("<!-- {GENERATED_BY_MARKER} -->\n{content}")
}

fn stamp_hash_comment(content: &str) -> String {
    // For files that use `#` for comments (constraints.xdc/.sdc/.cst/.lpf, shell scripts).
    format!("# {GENERATED_BY_MARKER}\n{content}")
}

#[derive(Clone, Debug, Deserialize, PartialEq, Eq, Serialize)]
pub struct TemplateReport {
    pub generated_by: String,
    pub status: String,
    pub project_class: ProjectClass,
    pub root: PathBuf,
    pub artifacts: Vec<PathBuf>,
    pub warnings: Vec<String>,
    pub limitations: Vec<String>,
}

#[derive(Debug, Error)]
pub enum TemplateError {
    #[error("unsupported project class `{project_class}` for this scaffold")]
    UnsupportedClass { project_class: ProjectClass },
    #[error("refusing to overwrite existing `{path}`")]
    FileExists { path: PathBuf },
    #[error("failed to create `{path}`: {message}")]
    CreateDir { path: PathBuf, message: String },
    #[error("failed to write `{path}`: {message}")]
    Write { path: PathBuf, message: String },
}

impl TemplateError {
    pub fn code(&self) -> &'static str {
        match self {
            Self::UnsupportedClass { .. } => "AF_TEMPLATE_CLASS_UNSUPPORTED",
            Self::FileExists { .. } => "AF_FILE_EXISTS",
            Self::CreateDir { .. } => "AF_CREATE_DIR_FAILED",
            Self::Write { .. } => "AF_WRITE_FAILED",
        }
    }

    pub fn hint(&self) -> &'static str {
        match self {
            Self::UnsupportedClass { .. } => {
                "Use `af core new --class simple-portable|composite-portable|complex-vendor-aware` for core templates or `af project new --class system-platform|product-stack` for project templates."
            }
            Self::FileExists { .. } => "Choose a new directory or remove the existing file intentionally.",
            Self::CreateDir { .. } | Self::Write { .. } => "Check filesystem permissions and the selected output path.",
        }
    }

    pub fn exit_code(&self) -> i32 {
        match self {
            Self::UnsupportedClass { .. } | Self::FileExists { .. } => 2,
            Self::CreateDir { .. } | Self::Write { .. } => 5,
        }
    }
}

pub fn scaffold_project(
    root: impl AsRef<Path>,
    project_class: ProjectClass,
    name: Option<&str>,
) -> Result<TemplateReport, TemplateError> {
    let root = root.as_ref();
    match project_class {
        ProjectClass::SystemPlatform => scaffold_system_project(root, name.unwrap_or("af-system")),
        ProjectClass::ProductStack => {
            scaffold_product_stack(root, name.unwrap_or("af-product-stack"))
        }
        other => Err(TemplateError::UnsupportedClass {
            project_class: other,
        }),
    }
}

pub fn scaffold_backend(
    core_dir: impl AsRef<Path>,
    vendor: &str,
    family: &str,
) -> Result<TemplateReport, TemplateError> {
    let core_dir = core_dir.as_ref();
    let backend_dir = core_dir.join("vendor").join(vendor);
    let mut artifacts = Vec::new();
    for dir in ["ram", "fifo", "dsp", "clock", "constraints", "tests"] {
        create_dir_all(&backend_dir.join(dir))?;
    }
    let status = "planned";
    write_new(
        &backend_dir.join("backend.toml"),
        &stamp_toml(&format!(
            r#"generated_by = "AccelFury IP Toolchain"
vendor = "{vendor}"
family = "{family}"
status = "{status}"
rtl_status = "not_implemented"
notes = [
  "Generated backend scaffold only; no vendor RTL primitive implementation is claimed.",
  "Do not mark this backend supported until equivalence, timing, and resource evidence exists."
]
"#,
        )),
        &mut artifacts,
    )?;
    write_new(
        &backend_dir.join("equivalence_plan.md"),
        &stamp_markdown(
            "# Backend Equivalence Plan\n\n- Compare generic and vendor RAM/FIFO/DSP behavior.\n- Record simulator, seed, vectors, and latency alignment.\n- Keep unsupported capabilities explicit.\n",
        ),
        &mut artifacts,
    )?;
    write_new(
        &backend_dir.join("constraints").join(constraint_name(vendor)),
        &stamp_hash_comment(
            "# Placeholder constraints. Replace with verified clocks, IO, false paths, and generated-clock constraints before implementation.\n",
        ),
        &mut artifacts,
    )?;
    write_new(
        &backend_dir.join("unsupported_capabilities.md"),
        &stamp_markdown(
            "# Unsupported Capabilities\n\nThis backend is planned. List every unavailable RAM/FIFO/DSP/clocking/platform capability here before export.\n",
        ),
        &mut artifacts,
    )?;
    for dir in ["ram", "fifo", "dsp", "clock", "tests"] {
        write_new(
            &backend_dir.join(dir).join("README.md"),
            &stamp_markdown(
                "# Planned Backend Area\n\nNo working RTL is generated here. Add implementations only with tests and limitations updates.\n",
            ),
            &mut artifacts,
        )?;
    }

    Ok(TemplateReport {
        generated_by: "AccelFury IP Toolchain".to_string(),
        status: "passed".to_string(),
        project_class: ProjectClass::ComplexVendorAware,
        root: core_dir.to_path_buf(),
        artifacts,
        warnings: vec![
            "Backend scaffold is marked planned and contains no fake working RTL.".to_string(),
        ],
        limitations: vec![
            "Vendor synthesis/PnR/bitstream generation is outside the first-release backend scaffold.".to_string(),
        ],
    })
}

fn scaffold_system_project(root: &Path, name: &str) -> Result<TemplateReport, TemplateError> {
    let mut artifacts = Vec::new();
    for dir in ["cores", "platforms", "constraints", "security", "reports"] {
        create_dir_all(&root.join(dir))?;
    }
    write_new(
        &root.join("af-project.toml"),
        &stamp_toml(&format!(
            r#"[project]
name = "{name}"
class = "system-platform"

[[cores]]
path = "cores/README.md"
role = "compute"

[[platforms]]
name = "draft_platform"
vendor = "unknown"
board = "unknown"
requires = ["constraints", "clocking", "reset", "security_review"]

[security]
production_flow = false
bitstream_authentication = "planned"
readback = "policy_required"
jtag = "policy_required"
"#
        )),
        &mut artifacts,
    )?;
    write_new(
        &root.join("cores").join("README.md"),
        &stamp_markdown(
            "# Cores\n\nAdd core packages or path dependencies here. Do not copy vendor backend RTL into common core layers.\n",
        ),
        &mut artifacts,
    )?;
    write_new(
        &root.join("platforms").join("README.md"),
        &stamp_markdown(
            "# Platforms\n\nDescribe board, hard IP, clocks, resets, memory maps, and constraints per target.\n",
        ),
        &mut artifacts,
    )?;
    template_report(ProjectClass::SystemPlatform, root, artifacts)
}

fn scaffold_product_stack(root: &Path, name: &str) -> Result<TemplateReport, TemplateError> {
    let mut artifacts = Vec::new();
    for dir in ["packages", "constructor_catalog", "reports"] {
        create_dir_all(&root.join(dir))?;
    }
    write_new(
        &root.join("af-product.toml"),
        &stamp_toml(&format!(
            r#"[product]
name = "{name}"
version = "0.1.0"

[[packages]]
path = "packages/README.md"
class = "system-platform"

[constructor_catalog]
export = true
path = "constructor_catalog"
"#
        )),
        &mut artifacts,
    )?;
    write_new(
        &root.join("packages").join("README.md"),
        &stamp_markdown(
            "# Packages\n\nAdd system-platform packages with version, compatibility, and limitations metadata.\n",
        ),
        &mut artifacts,
    )?;
    write_new(
        &root.join("constructor_catalog").join("README.md"),
        &stamp_markdown(
            "# Constructor Catalog\n\nGenerated catalog metadata belongs here. Do not publish packages without compatibility reports.\n",
        ),
        &mut artifacts,
    )?;
    template_report(ProjectClass::ProductStack, root, artifacts)
}

fn template_report(
    project_class: ProjectClass,
    root: &Path,
    artifacts: Vec<PathBuf>,
) -> Result<TemplateReport, TemplateError> {
    Ok(TemplateReport {
        generated_by: "AccelFury IP Toolchain".to_string(),
        status: "passed".to_string(),
        project_class,
        root: root.to_path_buf(),
        artifacts,
        warnings: Vec::new(),
        limitations: vec![
            "Generated project scaffold contains metadata only; no bitstream, hard IP, DDR/PCIe/SERDES, or hardware implementation is claimed.".to_string(),
        ],
    })
}

fn create_dir_all(path: &Path) -> Result<(), TemplateError> {
    fs::create_dir_all(path).map_err(|err| TemplateError::CreateDir {
        path: path.to_path_buf(),
        message: err.to_string(),
    })
}

fn write_new(
    path: &Path,
    content: &str,
    artifacts: &mut Vec<PathBuf>,
) -> Result<(), TemplateError> {
    if path.exists() {
        return Err(TemplateError::FileExists {
            path: path.to_path_buf(),
        });
    }
    fs::write(path, content).map_err(|err| TemplateError::Write {
        path: path.to_path_buf(),
        message: err.to_string(),
    })?;
    artifacts.push(path.to_path_buf());
    Ok(())
}

fn constraint_name(vendor: &str) -> &'static str {
    match vendor {
        "xilinx" => "constraints.xdc",
        "intel" => "constraints.sdc",
        "gowin" => "constraints.cst",
        "lattice" => "constraints.lpf",
        _ => "constraints.sdc",
    }
}
