// SPDX-License-Identifier: Apache-2.0
//
// Core scaffold generators ("af core new").
//
// All inline templates carry a `Generated by AccelFury IP Toolchain` stamp
// applied via the helpers at the top. Byte-determinism of the produced files
// is enforced by `crates/af-cli/tests/cli.rs::core_new_output_is_byte_deterministic_*`.

use crate::{parse_project_class, write_new_file, CliError, CliOutput};
use af_complexity::{PortabilityLevel, ProjectClass};
use af_manifest::{CoreManifest, CoreMaturity, CorePriority};
use serde_json::json;
use std::fs;
use std::path::{Path, PathBuf};
use std::str::FromStr;

/// User-supplied overrides for manifesto axes. Each `Some(...)` replaces the
/// profile default in the generated manifest; `None` leaves the default
/// untouched.
#[derive(Clone, Debug, Default)]
pub struct AxesOverride {
    pub portability_level: Option<PortabilityLevel>,
    pub priority: Option<CorePriority>,
    pub maturity: Option<CoreMaturity>,
}

impl AxesOverride {
    pub fn from_cli(
        portability_level: Option<&str>,
        priority: Option<&str>,
        maturity: Option<&str>,
    ) -> Result<Self, CliError> {
        fn parse_axis<T: FromStr<Err = E>, E: std::fmt::Display>(
            value: Option<&str>,
            field: &str,
        ) -> Result<Option<T>, CliError> {
            value
                .map(|raw| {
                    raw.parse::<T>().map_err(|err| {
                        CliError::new(
                            "AF_CORE_NEW_AXIS_INVALID",
                            format!("--{field} `{raw}` is invalid: {err}"),
                            "Use one of the allowed axis values; see docs/manifest-reference.md.",
                            2,
                        )
                    })
                })
                .transpose()
        }
        Ok(Self {
            portability_level: parse_axis::<PortabilityLevel, _>(
                portability_level,
                "portability-level",
            )?,
            priority: parse_axis::<CorePriority, _>(priority, "priority")?,
            maturity: parse_axis::<CoreMaturity, _>(maturity, "maturity")?,
        })
    }

    pub fn is_empty(&self) -> bool {
        self.portability_level.is_none() && self.priority.is_none() && self.maturity.is_none()
    }
}

pub const GENERATED_CORE_LICENSE_NAME: &str = "AccelFury Source Available License v1.0";
pub const GENERATED_CORE_SPDX_LICENSE_REF: &str = "LicenseRef-AccelFury-Source-Available-1.0";
pub const GENERATED_BY_MARKER: &str = "Generated by AccelFury IP Toolchain";

pub fn stamp_toml(content: impl Into<String>) -> String {
    format!("# {GENERATED_BY_MARKER}\n{}", content.into())
}

pub fn stamp_verilog(content: impl Into<String>) -> String {
    let content = content.into();
    // Preserve SPDX header if present: insert the stamp on the line AFTER SPDX
    // so license scanners still see SPDX-License-Identifier as the first line.
    if let Some(rest) = content.strip_prefix("// SPDX-License-Identifier:") {
        if let Some(newline_idx) = rest.find('\n') {
            let (spdx_tail, rest_after_spdx) = rest.split_at(newline_idx + 1);
            return format!(
                "// SPDX-License-Identifier:{spdx_tail}// {GENERATED_BY_MARKER}\n{rest_after_spdx}"
            );
        }
    }
    format!("// {GENERATED_BY_MARKER}\n{content}")
}

pub fn stamp_markdown(content: impl Into<String>) -> String {
    format!("<!-- {GENERATED_BY_MARKER} -->\n{}", content.into())
}

pub fn stamp_plaintext(content: impl Into<String>) -> String {
    // Plain-text files (LICENSE, NOTICE) carry a `#` comment header. This adds
    // attribution without disturbing license text content checks.
    format!("# {GENERATED_BY_MARKER}\n\n{}", content.into())
}

pub fn core_new(
    core_dir: &Path,
    name: &str,
    class: Option<&str>,
    library: &str,
    language: &str,
    profile: &str,
    axes_override: AxesOverride,
) -> Result<CliOutput, CliError> {
    let (project_class, mut warnings) = match class {
        Some(class) => (parse_project_class(class)?, Vec::new()),
        None => (
            ProjectClass::SimplePortable,
            vec![
                "AF_COMPLEXITY_CLASS_INFERRED: defaulted to simple-portable; run `af project classify` for complex accelerators.".to_string(),
            ],
        ),
    };
    let language = normalize_core_language(language)?;
    let profile = normalize_core_profile(profile)?;
    let mut output = match project_class {
        ProjectClass::SimplePortable if profile == "reset-sync" => {
            core_new_reset_sync(core_dir, name, library, language)?
        }
        ProjectClass::SimplePortable => core_new_stream_ip(core_dir, name, library, language)?,
        ProjectClass::CompositePortable => {
            if profile != "stream-ip" {
                return Err(CliError::new(
                    "AF_CORE_NEW_PROFILE_UNSUPPORTED",
                    format!("profile `{profile}` is unsupported for composite-portable"),
                    "Use --profile stream-ip for composite-portable or --class simple-portable --profile reset-sync for reset synchronizers.",
                    2,
                ));
            }
            core_new_composite_portable(core_dir, name, library, language)?
        }
        ProjectClass::ComplexVendorAware => {
            if profile != "stream-ip" {
                return Err(CliError::new(
                    "AF_CORE_NEW_PROFILE_UNSUPPORTED",
                    format!("profile `{profile}` is unsupported for complex-vendor-aware"),
                    "Use --profile stream-ip for the complex vendor-aware scaffold.",
                    2,
                ));
            }
            core_new_complex_vendor_aware(core_dir, name, library, language)?
        }
        ProjectClass::SystemPlatform | ProjectClass::ProductStack => {
            return Err(CliError::new(
                "AF_COMPLEXITY_CLASS_REQUIRED",
                format!("core new cannot create `{project_class}`"),
                "Use `af project new --class system-platform|product-stack` for system/product templates.",
                2,
            ));
        }
    };
    let development_artifacts = scaffold_core_development_artifacts(core_dir)?;
    if !axes_override.is_empty() {
        apply_axes_override(core_dir, &axes_override)?;
        // Re-load manifest so the JSON output reflects the overridden axes
        // rather than the profile defaults.
        let refreshed = CoreManifest::from_path(core_dir.join("af-core.toml"))?;
        if let Some(object) = output.json.as_object_mut() {
            object.insert("manifest".to_string(), json!(refreshed));
        }
    }
    annotate_core_new_output(&mut output, project_class, &mut warnings);
    if let Some(object) = output.json.as_object_mut() {
        object.insert(
            "development_artifacts".to_string(),
            json!(development_artifacts),
        );
    }
    Ok(output)
}

fn apply_axes_override(core_dir: &Path, override_: &AxesOverride) -> Result<(), CliError> {
    let path = core_dir.join("af-core.toml");
    let raw = fs::read_to_string(&path).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_AXIS_OVERRIDE_READ_FAILED",
            format!("failed to read `{}`: {err}", path.display()),
            "Check filesystem permissions.",
            5,
        )
    })?;
    let mut value: toml::Value = raw.parse().map_err(|err: toml::de::Error| {
        CliError::new(
            "AF_CORE_NEW_AXIS_OVERRIDE_PARSE_FAILED",
            format!("failed to parse generated `{}`: {err}", path.display()),
            "Regenerate the scaffold; the manifest text is internally produced.",
            5,
        )
    })?;
    let table = value
        .as_table_mut()
        .expect("generated af-core.toml root is a table");
    if let Some(level) = override_.portability_level {
        table.insert(
            "portability_level".to_string(),
            toml::Value::String(level.as_str().to_string()),
        );
    }
    if let Some(priority) = override_.priority {
        table.insert(
            "priority".to_string(),
            toml::Value::String(priority.as_str().to_string()),
        );
    }
    if let Some(maturity) = override_.maturity {
        table.insert(
            "maturity".to_string(),
            toml::Value::String(maturity.as_str().to_string()),
        );
    }
    let serialized = toml::to_string(&value).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_AXIS_OVERRIDE_SERIALIZE_FAILED",
            format!("failed to serialize updated manifest: {err}"),
            "Report this as a bug; CLI override should not produce non-serializable manifests.",
            5,
        )
    })?;
    fs::write(&path, serialized).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_AXIS_OVERRIDE_WRITE_FAILED",
            format!("failed to write `{}`: {err}", path.display()),
            "Check filesystem permissions.",
            5,
        )
    })?;
    Ok(())
}
fn normalize_core_language(language: &str) -> Result<&'static str, CliError> {
    match language {
        "verilog" | "verilog-2001" => Ok("verilog-2001"),
        "systemverilog" => Err(CliError::new(
            "AF_CORE_NEW_LANGUAGE_UNSUPPORTED",
            "core new only scaffolds portable Verilog-2001 base cores",
            "Use --language verilog-2001 for generic cores; keep SystemVerilog, vendor primitives, AXI adapters, and PLL logic in optional wrappers outside the base core.",
            2,
        )),
        _ => Err(CliError::new(
            "AF_CORE_NEW_LANGUAGE_UNSUPPORTED",
            format!("core new language `{language}` is unsupported"),
            "Use --language verilog-2001 for the built-in portable scaffold.",
            2,
        )),
    }
}

fn normalize_core_profile(profile: &str) -> Result<&'static str, CliError> {
    match profile {
        "stream-ip" => Ok("stream-ip"),
        "reset-sync" | "atomic-reset-sync" => Ok("reset-sync"),
        _ => Err(CliError::new(
            "AF_CORE_NEW_PROFILE_UNSUPPORTED",
            format!("core new profile `{profile}` is unsupported"),
            "Use --profile stream-ip or --profile reset-sync for the built-in scaffold.",
            2,
        )),
    }
}

fn ensure_portable_core_language(language: &str, profile: &str) -> Result<(), CliError> {
    if language != "verilog-2001" {
        return Err(CliError::new(
            "AF_CORE_NEW_LANGUAGE_UNSUPPORTED",
            format!("core new language `{language}` is unsupported"),
            format!("Use --language verilog-2001 with --profile {profile}."),
            2,
        ));
    }
    Ok(())
}

fn write_generated_core_legal_artifacts(
    core_dir: &Path,
    core_name: &str,
    description: &str,
) -> Result<(), CliError> {
    let license = generated_core_license_text(core_name);
    let commercial = generated_core_commercial_license_text(core_name);
    let notice = generated_core_notice_text(core_name, description);
    write_new_file(&core_dir.join("LICENSE"), license.as_bytes())?;
    write_new_file(
        &core_dir.join("COMMERCIAL-LICENSE.md"),
        commercial.as_bytes(),
    )?;
    write_new_file(&core_dir.join("NOTICE"), notice.as_bytes())?;
    Ok(())
}

fn generated_core_license_text(core_name: &str) -> String {
    stamp_plaintext(format!(
        r#"AccelFury Source Available License v1.0

Copyright (c) 2026 AccelFury.

This license applies to the {core_name} source code, documentation, tests,
examples, and board-support files distributed in this repository, unless a file
explicitly states a different license.

1. Public Open-Source Use

You may use, copy, modify, build, simulate, synthesize, and redistribute this
software for public open-source projects, provided that:

- the complete corresponding source code of the project using {core_name} is
  publicly available under an open-source license;
- attribution to AccelFury and this repository is retained in source
  distributions, documentation, and notices;
- this license text and copyright notice are preserved.

2. Closed-Source And Commercial Use

Closed-source, proprietary, private, customer-delivered, paid, ASIC, SoC,
chiplet, embedded product, or commercial use requires a separate paid
commercial license from AccelFury before use.

Examples requiring a commercial license include, but are not limited to:

- private or proprietary repositories;
- closed-source FPGA products or bitstreams;
- customer-delivered hardware, firmware, or gateware;
- paid internal tools, appliances, services, or products;
- ASIC, SoC, or chiplet integration;
- commercial systems where the complete corresponding source is not public.

See COMMERCIAL-LICENSE.md for the commercial licensing summary.

3. No Trademark Rights

This license does not grant rights to use AccelFury names, logos, or trademarks
except for factual attribution.

4. No Warranty

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR
A PARTICULAR PURPOSE, NONINFRINGEMENT, SAFETY, OR HARDWARE SUITABILITY.

You are responsible for verifying electrical compatibility, pin constraints,
timing closure, and safe operation on the target board before connecting
external hardware.

5. Limitation Of Liability

TO THE MAXIMUM EXTENT PERMITTED BY LAW, ACCELFURY AND CONTRIBUTORS SHALL NOT BE
LIABLE FOR ANY CLAIM, DAMAGE, LOSS, COST, OR LIABILITY ARISING FROM USE OF THIS
SOFTWARE, INCLUDING HARDWARE DAMAGE, DATA LOSS, COMMERCIAL LOSS, OR
CONSEQUENTIAL DAMAGES.
"#
    ))
}

fn generated_core_commercial_license_text(core_name: &str) -> String {
    stamp_markdown(format!(
        r#"# Commercial Licensing

`{core_name}` is available for closed-source and commercial use under a separate
paid commercial license from AccelFury.

You need a commercial license if you use the core in any of these ways:

- Closed-source FPGA product.
- Private or proprietary repository.
- Customer-delivered bitstream.
- ASIC, SoC, or chiplet integration.
- Paid internal tool, product, appliance, or service.
- Commercial system where the complete corresponding source is not public.

The public license allows use in public open projects with attribution. It does
not grant closed commercial rights.

Contact AccelFury for commercial terms, support, warranty options, and custom
integration work.
"#
    ))
}

fn generated_core_notice_text(core_name: &str, description: &str) -> String {
    stamp_plaintext(format!(
        r#"{core_name}
Copyright (c) 2026 AccelFury.

{description}.

Attribution requirement:
Products, projects, source distributions, and documentation that use this
core under the public-source terms must retain the copyright notice, license
notice, and attribution to AccelFury.
"#
    ))
}

fn core_new_stream_ip(
    core_dir: &Path,
    name: &str,
    library: &str,
    language: &str,
) -> Result<CliOutput, CliError> {
    ensure_portable_core_language(language, "stream-ip")?;
    let module = to_module_ident(name)?;
    let extension = "v";
    let source_file = format!("rtl/{module}.{extension}");
    let rtl_dir = core_dir.join("rtl");
    fs::create_dir_all(&rtl_dir).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_CREATE_DIR_FAILED",
            format!("failed to create `{}`: {err}", rtl_dir.display()),
            "Check filesystem permissions and choose a writable core directory.",
            5,
        )
    })?;

    let manifest = stamp_toml(format!(
        r#"af_version = "0.3"
name = "{name}"
vendor = "accelfury"
library = "{library}"
core = "{module}"
version = "0.1.0"
known_limitations = ["Generated scaffold; no timing, board, or hardware validation claims."]

[complexity]
class = "simple-portable"
score = 1
decision = "portable starter core with one clock/reset domain"
triggers = []

[[verification_required]]
kind = "simulation"
description = "Smoke testbench (add before promoting maturity from experimental)."

[architecture]
style = "portable_verilog_2001"
reference_backend = "generic"

[reuse]
prefer_existing_microcores = true

[constructor]
export = false

[metadata]
license = "{license}"
authors = ["AccelFury contributors"]
description = "Generated AccelFury core scaffold."

[rtl]
top = "{module}"
language = "{language}"
default_clock = "clk"
default_reset = "rst_n"

[sources]
files = ["{source_file}"]
include_dirs = []

[[clocks]]
name = "clk"

[[resets]]
name = "rst_n"
active = "low"

[[ports]]
name = "clk"
direction = "input"
width = 1
clock = "clk"

[[ports]]
name = "rst_n"
direction = "input"
width = 1
reset = "rst_n"

[[ports]]
name = "enable"
direction = "input"
width = 1
clock = "clk"
reset = "rst_n"

[[ports]]
name = "done"
direction = "output"
width = 1
clock = "clk"
reset = "rst_n"

[backend_compatibility]
verilator = true
fusesoc = true
"#,
        license = GENERATED_CORE_LICENSE_NAME,
    ));
    let rtl = stamp_verilog(format!(
        r#"// SPDX-License-Identifier: {spdx_license}
`default_nettype none

module {module} (
  input wire clk,
  input wire rst_n,
  input wire enable,
  output reg done
);
  always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
      done <= 1'b0;
    end else begin
      done <= enable;
    end
  end
endmodule

`default_nettype wire
"#,
        spdx_license = GENERATED_CORE_SPDX_LICENSE_REF,
    ));
    write_new_file(&core_dir.join("af-core.toml"), manifest.as_bytes())?;
    write_generated_core_legal_artifacts(core_dir, name, "Generated AccelFury core scaffold")?;
    write_new_file(
        &rtl_dir.join(format!("{module}.{extension}")),
        rtl.as_bytes(),
    )?;
    let manifest = CoreManifest::from_path(core_dir.join("af-core.toml"))?;
    Ok(CliOutput {
        human: format!("core scaffold written: {}", core_dir.display()),
        json: json!({
            "status": "passed",
            "core_dir": core_dir,
            "profile": "stream-ip",
            "manifest": manifest,
        }),
    })
}

fn core_new_reset_sync(
    core_dir: &Path,
    name: &str,
    library: &str,
    language: &str,
) -> Result<CliOutput, CliError> {
    ensure_portable_core_language(language, "reset-sync")?;
    let module = to_module_ident(name)?;
    let top_file = format!("rtl/{module}.v");
    let rtl_dir = core_dir.join("rtl");
    fs::create_dir_all(&rtl_dir).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_CREATE_DIR_FAILED",
            format!("failed to create `{}`: {err}", rtl_dir.display()),
            "Check filesystem permissions and choose a writable core directory.",
            5,
        )
    })?;

    let manifest = stamp_toml(format!(
        r#"af_version = "0.3"
name = "{name}"
vendor = "accelfury"
library = "{library}"
core = "{module}"
version = "0.1.0"
category = "stream_infra"
portability_level = "U0"
priority = "P0"
maturity = "experimental"
known_limitations = [
  "Reset input must be glitch-free at system level.",
  "One synchronizer instance is valid for one clock domain only.",
  "Generated reset-sync scaffold has no timing, board, vendor synthesis, or hardware validation claims."
]

[complexity]
class = "simple-portable"
score = 1
decision = "portable reset synchronizer with one destination clock domain"
triggers = []

[[verification_required]]
kind = "formal-cdc-assumption"
description = "Async assertion and N-cycle synchronous deassertion with no glitch on dst_rst."

[[verification_required]]
kind = "simulation"
description = "Smoke testbench under tb/ (add before promoting maturity from experimental)."

[architecture]
style = "portable_verilog_2001"
reference_backend = "generic"

[reuse]
prefer_existing_microcores = true

[constructor]
export = false

[metadata]
license = "{license}"
authors = ["AccelFury contributors"]
description = "Portable Verilog-2001 reset synchronizer scaffold (canonical form: STAGES + RESET_POLARITY, src_rst/dst_rst)."

[rtl]
top = "{module}"
language = "verilog-2001"
default_clock = "clk"
default_reset = "src_rst"

[sources]
files = ["{top_file}"]
include_dirs = []

[[parameters]]
name = "STAGES"
value = "2"
kind = "integer"
description = "Number of synchronizer flops in the destination clock domain."

[[parameters]]
name = "RESET_POLARITY"
value = "0"
kind = "integer"
allowed = ["0", "1"]
description = "0 = active-low (src_rst is src_rst_n); 1 = active-high."

[[clocks]]
name = "clk"
port = "clk"
description = "Target clock domain for reset release."

[[resets]]
name = "src_rst"
port = "src_rst"
active = "low"
style = "async"
clock_domain = "clk"
asynchronous = true

[[ports]]
name = "clk"
direction = "input"
width = 1
kind = "clock"

[[ports]]
name = "src_rst"
direction = "input"
width = 1
kind = "reset"

[[ports]]
name = "dst_rst"
direction = "output"
width = 1
kind = "reset"

[backend_compatibility]
verilator = true
fusesoc = true
"#,
        license = GENERATED_CORE_LICENSE_NAME,
    ));
    let rtl = stamp_verilog(format!(
        r#"// SPDX-License-Identifier: {spdx_license}
//
// Canonical N-stage reset synchronizer (parameterized polarity).
// Asynchronous assertion, synchronous deassertion. Mirrors
// examples/af-reset-sync/rtl/af_reset_sync.v one-to-one.

`default_nettype none

module {module}
#(
    parameter STAGES         = 2,
    parameter RESET_POLARITY = 0
)
(
    input  wire clk,
    input  wire src_rst,
    output wire dst_rst
);

    // synthesis translate_off
    initial begin
        if (STAGES < 2) begin
            $display("{module}: STAGES must be >= 2 (got %0d)", STAGES);
            $finish;
        end
    end
    // synthesis translate_on

    reg [STAGES-1:0] sync_chain;

    generate
        if (RESET_POLARITY == 0) begin : g_active_low
            always @(posedge clk or negedge src_rst) begin
                if (!src_rst) begin
                    sync_chain <= {{STAGES{{1'b0}}}};
                end else begin
                    sync_chain <= {{sync_chain[STAGES-2:0], 1'b1}};
                end
            end
            assign dst_rst = sync_chain[STAGES-1];
        end else begin : g_active_high
            always @(posedge clk or posedge src_rst) begin
                if (src_rst) begin
                    sync_chain <= {{STAGES{{1'b1}}}};
                end else begin
                    sync_chain <= {{sync_chain[STAGES-2:0], 1'b0}};
                end
            end
            assign dst_rst = sync_chain[STAGES-1];
        end
    endgenerate

endmodule

`default_nettype wire
"#,
        spdx_license = GENERATED_CORE_SPDX_LICENSE_REF,
    ));
    write_new_file(&core_dir.join("af-core.toml"), manifest.as_bytes())?;
    write_generated_core_legal_artifacts(
        core_dir,
        name,
        "Portable Verilog-2001 reset synchronizer scaffold",
    )?;
    write_new_file(&rtl_dir.join(format!("{module}.v")), rtl.as_bytes())?;
    let manifest = CoreManifest::from_path(core_dir.join("af-core.toml"))?;
    Ok(CliOutput {
        human: format!("core scaffold written: {}", core_dir.display()),
        json: json!({
            "status": "passed",
            "core_dir": core_dir,
            "profile": "reset-sync",
            "manifest": manifest,
        }),
    })
}

fn core_new_composite_portable(
    core_dir: &Path,
    name: &str,
    library: &str,
    language: &str,
) -> Result<CliOutput, CliError> {
    ensure_portable_core_language(language, "stream-ip")?;
    let module = to_module_ident(name)?;
    let stage = format!("{module}_stage");
    let rtl_dir = core_dir.join("rtl");
    fs::create_dir_all(&rtl_dir).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_CREATE_DIR_FAILED",
            format!("failed to create `{}`: {err}", rtl_dir.display()),
            "Check filesystem permissions and choose a writable core directory.",
            5,
        )
    })?;
    let manifest = stamp_toml(format!(
        r#"af_version = "0.3"
name = "{name}"
vendor = "accelfury"
library = "{library}"
core = "{module}"
version = "0.1.0"
known_limitations = ["Generated composite scaffold; dependency, latency, timing, and board evidence are not populated."]

[complexity]
class = "composite-portable"
score = 3
decision = "ready/valid shell with reusable portable stage boundary"
triggers = ["core_dependencies", "multiple_interfaces"]

[[verification_required]]
kind = "simulation"
description = "Composite scaffold smoke (verify stage interaction before promoting maturity)."

[architecture]
style = "composite_portable"
reference_backend = "generic"

[reuse]
prefer_existing_microcores = true

[[dependencies.cores]]
name = "af-stream-skid-buffer"
version = ">=0.2.0"
role = "ready_valid_boundary"

[metadata]
license = "{license}"
authors = ["AccelFury contributors"]
description = "Generated AccelFury composite portable core scaffold."

[rtl]
top = "{module}"
language = "{language}"
default_clock = "clk"
default_reset = "rst_n"

[sources]
files = ["rtl/{module}.v", "rtl/{stage}.v"]
include_dirs = []

[[parameters]]
name = "DATA_WIDTH"
kind = "integer"
value = "32"
min = "1"

[[clocks]]
name = "clk"
port = "clk"

[[resets]]
name = "rst_n"
port = "rst_n"
active = "low"
clock_domain = "clk"

[[ports]]
name = "clk"
direction = "input"
width = 1
clock = "clk"

[[ports]]
name = "rst_n"
direction = "input"
width = 1
reset = "rst_n"

[[ports]]
name = "in_data"
direction = "input"
width = "DATA_WIDTH"
clock = "clk"
reset = "rst_n"

[[ports]]
name = "in_valid"
direction = "input"
width = 1
clock = "clk"
reset = "rst_n"

[[ports]]
name = "in_ready"
direction = "output"
width = 1
clock = "clk"
reset = "rst_n"

[[ports]]
name = "out_data"
direction = "output"
width = "DATA_WIDTH"
clock = "clk"
reset = "rst_n"

[[ports]]
name = "out_valid"
direction = "output"
width = 1
clock = "clk"
reset = "rst_n"

[[ports]]
name = "out_ready"
direction = "input"
width = 1
clock = "clk"
reset = "rst_n"

[[stream_interfaces]]
name = "input_stream"
kind = "ready_valid"
clock_domain = "clk"
data = "in_data"
valid = "in_valid"
ready = "in_ready"
data_width = "DATA_WIDTH"

[[stream_interfaces]]
name = "output_stream"
kind = "ready_valid"
clock_domain = "clk"
data = "out_data"
valid = "out_valid"
ready = "out_ready"
data_width = "DATA_WIDTH"

[constructor]
export = true
category = "compute"
compatibility_profile = "af_stream_v1"

[backend_compatibility]
verilator = true
fusesoc = true
"#,
        license = GENERATED_CORE_LICENSE_NAME,
    ));
    let top_rtl = stamp_verilog(format!(
        r#"// SPDX-License-Identifier: {spdx_license}
`default_nettype none

module {module}
#(
    parameter DATA_WIDTH = 32
)
(
    input wire clk,
    input wire rst_n,
    input wire [DATA_WIDTH-1:0] in_data,
    input wire in_valid,
    output wire in_ready,
    output wire [DATA_WIDTH-1:0] out_data,
    output wire out_valid,
    input wire out_ready
);

{stage}
#(
    .DATA_WIDTH(DATA_WIDTH)
)
u_stage (
    .clk       (clk),
    .rst_n     (rst_n),
    .in_data   (in_data),
    .in_valid  (in_valid),
    .in_ready  (in_ready),
    .out_data  (out_data),
    .out_valid (out_valid),
    .out_ready (out_ready)
);

endmodule

`default_nettype wire
"#,
        spdx_license = GENERATED_CORE_SPDX_LICENSE_REF,
    ));
    let stage_rtl = stamp_verilog(format!(
        r#"// SPDX-License-Identifier: {spdx_license}
`default_nettype none

module {stage}
#(
    parameter DATA_WIDTH = 32
)
(
    input wire clk,
    input wire rst_n,
    input wire [DATA_WIDTH-1:0] in_data,
    input wire in_valid,
    output wire in_ready,
    output reg [DATA_WIDTH-1:0] out_data,
    output reg out_valid,
    input wire out_ready
);

assign in_ready = !out_valid || out_ready;

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        out_data <= {{DATA_WIDTH{{1'b0}}}};
        out_valid <= 1'b0;
    end else if (in_ready) begin
        out_data <= in_data;
        out_valid <= in_valid;
    end
end

endmodule

`default_nettype wire
"#,
        spdx_license = GENERATED_CORE_SPDX_LICENSE_REF,
    ));
    write_new_file(&core_dir.join("af-core.toml"), manifest.as_bytes())?;
    write_generated_core_legal_artifacts(
        core_dir,
        name,
        "Generated AccelFury composite portable core scaffold",
    )?;
    write_new_file(&rtl_dir.join(format!("{module}.v")), top_rtl.as_bytes())?;
    write_new_file(&rtl_dir.join(format!("{stage}.v")), stage_rtl.as_bytes())?;
    let af_arch_toml = stamp_toml(
        "generated_by = \"AccelFury IP Toolchain\"\n\n[layers]\ncommon = [\"rtl/*.v\"]\n\n[verification]\nsignoff = [\"lint\", \"sim\", \"dependency-check\", \"compatibility-check\"]\n",
    );
    write_new_file(&core_dir.join("af-arch.toml"), af_arch_toml.as_bytes())?;
    let constructor_readme = stamp_markdown(
        "# Constructor Metadata\n\nRun `af constructor export` to generate machine-readable package files.\n",
    );
    write_new_file(
        &core_dir.join("constructor/README.md"),
        constructor_readme.as_bytes(),
    )?;
    let manifest = CoreManifest::from_path(core_dir.join("af-core.toml"))?;
    Ok(CliOutput {
        human: format!("composite core scaffold written: {}", core_dir.display()),
        json: json!({
            "status": "passed",
            "core_dir": core_dir,
            "profile": "stream-ip",
            "manifest": manifest,
        }),
    })
}

fn core_new_complex_vendor_aware(
    core_dir: &Path,
    name: &str,
    library: &str,
    language: &str,
) -> Result<CliOutput, CliError> {
    ensure_portable_core_language(language, "stream-ip")?;
    let module = to_module_ident(name)?;
    let common = format!("{module}_core");
    let work_ram = format!("{module}_work_ram");
    let rtl_dir = core_dir.join("rtl");
    fs::create_dir_all(rtl_dir.join("common")).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_CREATE_DIR_FAILED",
            format!(
                "failed to create `{}`: {err}",
                rtl_dir.join("common").display()
            ),
            "Check filesystem permissions and choose a writable core directory.",
            5,
        )
    })?;
    fs::create_dir_all(rtl_dir.join("generic")).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_CREATE_DIR_FAILED",
            format!(
                "failed to create `{}`: {err}",
                rtl_dir.join("generic").display()
            ),
            "Check filesystem permissions and choose a writable core directory.",
            5,
        )
    })?;
    fs::create_dir_all(core_dir.join("vendor")).map_err(|err| {
        CliError::new(
            "AF_CORE_NEW_CREATE_DIR_FAILED",
            format!(
                "failed to create `{}`: {err}",
                core_dir.join("vendor").display()
            ),
            "Check filesystem permissions and choose a writable core directory.",
            5,
        )
    })?;
    let manifest = stamp_toml(format!(
        r#"af_version = "0.3"
name = "{name}"
vendor = "accelfury"
library = "{library}"
core = "{module}"
version = "0.1.0"
known_limitations = [
  "Generated complex scaffold only; vendor RAM/FIFO/DSP/clocking backends are planned, not implemented.",
  "No backend equivalence, timing closure, resource utilization, CDC/RDC, or hardware evidence exists yet."
]

[complexity]
class = "complex-vendor-aware"
score = 8
decision = "memory banking and vendor DSP backend required"
triggers = ["memory_banking", "vendor_dsp_backend_required", "vendor_backend_matrix", "online_constructor"]

[[verification_required]]
kind = "simulation"
description = "Portable contract simulation prior to wiring vendor backends."

[[verification_required]]
kind = "synthesis-report"
description = "Vendor or Yosys synthesis report for the generic backend before promoting maturity."

[architecture]
style = "portable_contract_with_vendor_backends"
reference_backend = "generic"

[reuse]
prefer_existing_microcores = true

[[dependencies.cores]]
name = "af-stream-skid-buffer"
version = ">=0.2.0"
role = "ready_valid_boundary"

[metadata]
license = "{license}"
authors = ["AccelFury contributors"]
description = "Generated AccelFury complex vendor-aware core scaffold."

[rtl]
top = "{module}"
language = "{language}"
default_clock = "clk"
default_reset = "rst_n"

[sources]
files = ["rtl/{module}.v", "rtl/common/{common}.v", "rtl/generic/{work_ram}.v"]
include_dirs = []

[[parameters]]
name = "DATA_WIDTH"
kind = "integer"
value = "64"
min = "1"

[[parameters]]
name = "ADDR_WIDTH"
kind = "integer"
value = "12"
min = "1"

[[clocks]]
name = "clk"
port = "clk"

[[resets]]
name = "rst_n"
port = "rst_n"
active = "low"
clock_domain = "clk"

[[ports]]
name = "clk"
direction = "input"
width = 1
clock = "clk"

[[ports]]
name = "rst_n"
direction = "input"
width = 1
reset = "rst_n"

[[ports]]
name = "start"
direction = "input"
width = 1
clock = "clk"
reset = "rst_n"

[[ports]]
name = "done"
direction = "output"
width = 1
clock = "clk"
reset = "rst_n"

[[ports]]
name = "data_i"
direction = "input"
width = "DATA_WIDTH"
clock = "clk"
reset = "rst_n"

[[ports]]
name = "data_o"
direction = "output"
width = "DATA_WIDTH"
clock = "clk"
reset = "rst_n"

[[resources.memory]]
name = "work_ram"
kind = "ram_1r1w"
width = 64
depth = 4096
latency_cycles = 1
backend_policy = "prefer_vendor"

[[resources.dsp]]
name = "mul_pipeline"
kind = "multiplier"
count = 64
backend_policy = "require_vendor"

[[backend_variants]]
name = "xilinx_ultrascale_plus"
vendor = "xilinx"
families = ["ultrascale-plus"]
status = "planned"

[[backend_variants]]
name = "intel_agilex"
vendor = "intel"
families = ["agilex"]
status = "planned"

[[backend_variants]]
name = "gowin_gw2a"
vendor = "gowin"
families = ["gw2a"]
status = "planned"

[constructor]
export = true
category = "compute"
compatibility_profile = "af_stream_v1"

[backend_compatibility]
verilator = true
fusesoc = true
"#,
        license = GENERATED_CORE_LICENSE_NAME,
    ));
    let top_rtl = stamp_verilog(format!(
        r#"// SPDX-License-Identifier: {spdx_license}
`default_nettype none

module {module}
#(
    parameter DATA_WIDTH = 64,
    parameter ADDR_WIDTH = 12
)
(
    input wire clk,
    input wire rst_n,
    input wire start,
    output wire done,
    input wire [DATA_WIDTH-1:0] data_i,
    output wire [DATA_WIDTH-1:0] data_o
);

wire [DATA_WIDTH-1:0] scratch_q;
wire [ADDR_WIDTH-1:0] scratch_addr;
wire scratch_we;

{common}
#(
    .DATA_WIDTH(DATA_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
)
u_core (
    .clk          (clk),
    .rst_n        (rst_n),
    .start        (start),
    .done         (done),
    .data_i       (data_i),
    .data_o       (data_o),
    .scratch_q    (scratch_q),
    .scratch_addr (scratch_addr),
    .scratch_we   (scratch_we)
);

{work_ram}
#(
    .DATA_WIDTH(DATA_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
)
u_work_ram (
    .clk  (clk),
    .we   (scratch_we),
    .addr (scratch_addr),
    .d    (data_i),
    .q    (scratch_q)
);

endmodule

`default_nettype wire
"#,
        spdx_license = GENERATED_CORE_SPDX_LICENSE_REF,
    ));
    let common_rtl = stamp_verilog(format!(
        r#"// SPDX-License-Identifier: {spdx_license}
`default_nettype none

module {common}
#(
    parameter DATA_WIDTH = 64,
    parameter ADDR_WIDTH = 12
)
(
    input wire clk,
    input wire rst_n,
    input wire start,
    output reg done,
    input wire [DATA_WIDTH-1:0] data_i,
    output reg [DATA_WIDTH-1:0] data_o,
    input wire [DATA_WIDTH-1:0] scratch_q,
    output reg [ADDR_WIDTH-1:0] scratch_addr,
    output reg scratch_we
);

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        done <= 1'b0;
        data_o <= {{DATA_WIDTH{{1'b0}}}};
        scratch_addr <= {{ADDR_WIDTH{{1'b0}}}};
        scratch_we <= 1'b0;
    end else begin
        done <= start;
        data_o <= scratch_q ^ data_i;
        scratch_addr <= scratch_addr + 1'b1;
        scratch_we <= start;
    end
end

endmodule

`default_nettype wire
"#,
        spdx_license = GENERATED_CORE_SPDX_LICENSE_REF,
    ));
    let ram_rtl = stamp_verilog(format!(
        r#"// SPDX-License-Identifier: {spdx_license}
`default_nettype none

module {work_ram}
#(
    parameter DATA_WIDTH = 64,
    parameter ADDR_WIDTH = 12
)
(
    input wire clk,
    input wire we,
    input wire [ADDR_WIDTH-1:0] addr,
    input wire [DATA_WIDTH-1:0] d,
    output reg [DATA_WIDTH-1:0] q
);

reg [DATA_WIDTH-1:0] mem [0:(1 << ADDR_WIDTH)-1];

always @(posedge clk) begin
    if (we) begin
        mem[addr] <= d;
    end
    q <= mem[addr];
end

endmodule

`default_nettype wire
"#,
        spdx_license = GENERATED_CORE_SPDX_LICENSE_REF,
    ));
    let arch = stamp_toml(
        "generated_by = \"AccelFury IP Toolchain\"\n\n[layers]\ncommon = [\"rtl/common\"]\ngeneric = [\"rtl/generic\"]\nvendor = [\"vendor/<vendor>\"]\nconstructor = [\"constructor\"]\n\n[performance]\ntarget_fmax_mhz = 250\nresource_uncertainty = \"high\"\n\n[[cdc]]\nname = \"single_clock_baseline\"\nsource = \"clk\"\ndestination = \"clk\"\nstrategy = \"not_applicable\"\n\n[verification]\nsignoff = [\"lint\", \"sim\", \"formal-targets\", \"backend-equivalence\", \"cdc-rdc-plan\", \"timing-resource-plan\"]\n",
    );
    let constructor_readme = stamp_markdown(
        "# Constructor Metadata\n\nRun `af constructor export` to generate JSON package files for this complex core.\n",
    );
    let vendor_readme = stamp_markdown(
        "# Vendor Backends\n\nRun `af backend scaffold <core> --vendor <vendor> --family <family>` before implementing vendor RAM/FIFO/DSP/clocking layers.\n",
    );
    write_new_file(&core_dir.join("af-core.toml"), manifest.as_bytes())?;
    write_generated_core_legal_artifacts(
        core_dir,
        name,
        "Generated AccelFury complex vendor-aware core scaffold",
    )?;
    write_new_file(&rtl_dir.join(format!("{module}.v")), top_rtl.as_bytes())?;
    write_new_file(
        &rtl_dir.join("common").join(format!("{common}.v")),
        common_rtl.as_bytes(),
    )?;
    write_new_file(
        &rtl_dir.join("generic").join(format!("{work_ram}.v")),
        ram_rtl.as_bytes(),
    )?;
    write_new_file(&core_dir.join("af-arch.toml"), arch.as_bytes())?;
    write_new_file(
        &core_dir.join("constructor/README.md"),
        constructor_readme.as_bytes(),
    )?;
    write_new_file(&core_dir.join("vendor/README.md"), vendor_readme.as_bytes())?;
    let manifest = CoreManifest::from_path(core_dir.join("af-core.toml"))?;
    Ok(CliOutput {
        human: format!(
            "complex vendor-aware core scaffold written: {}",
            core_dir.display()
        ),
        json: json!({
            "status": "passed",
            "core_dir": core_dir,
            "profile": "stream-ip",
            "manifest": manifest,
        }),
    })
}

fn annotate_core_new_output(
    output: &mut CliOutput,
    project_class: ProjectClass,
    warnings: &mut Vec<String>,
) {
    warnings.sort();
    warnings.dedup();
    if !warnings.is_empty() {
        output
            .human
            .push_str(&format!("\nwarning: {}", warnings.join("\nwarning: ")));
    }
    if let Some(object) = output.json.as_object_mut() {
        object.insert("project_class".to_string(), json!(project_class));
        object.insert("warnings".to_string(), json!(warnings));
    }
}

fn scaffold_core_development_artifacts(core_dir: &Path) -> Result<Vec<PathBuf>, CliError> {
    let readme = core_dir.join("artifacts/openfpga-ci/README.md");
    let body = stamp_markdown(
        "# Core Development Artifacts\n\nRun `af core tooling . --json` from this core directory, or `af core tooling <core-dir> --json` from a parent repository, to refresh development tool visibility artifacts:\n\n- `reports/core-tooling.json`\n- `reports/core-smt-solvers.json`\n- `reports/core-integration-tools.json`\n- `logs/smt-solvers-tool-versions.txt`\n- `logs/integration-tool-versions.txt`\n\nThese artifacts prove only tool visibility for Boolector, Z3, Yices, Bitwuzla, cvc5, xmllint, FuseSoC and Edalize. They do not prove formal coverage, package semantic completeness, timing closure, CDC/RDC signoff, vendor implementation, or hardware readiness.\n",
    );
    write_new_file(&readme, body.as_bytes())?;
    Ok(vec![readme])
}

fn to_module_ident(name: &str) -> Result<String, CliError> {
    let mut out = String::new();
    for ch in name.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            out.push(ch);
        } else if matches!(ch, '-' | '.') {
            out.push('_');
        } else {
            return Err(CliError::new(
                "AF_IDENTIFIER_INVALID",
                format!("unsupported character `{ch}` in core name `{name}`"),
                "Use letters, digits, underscore, dash, or dot.",
                2,
            ));
        }
    }
    let Some(first) = out.chars().next() else {
        return Err(CliError::new(
            "AF_IDENTIFIER_INVALID",
            "core name must not be empty",
            "Provide a non-empty core name.",
            2,
        ));
    };
    if !(first.is_ascii_alphabetic() || first == '_') {
        return Err(CliError::new(
            "AF_IDENTIFIER_INVALID",
            format!("core name `{name}` must start with a letter or underscore"),
            "Use a Verilog-compatible module name.",
            2,
        ));
    }
    Ok(out)
}
