// SPDX-License-Identifier: Apache-2.0

pub mod backend;
pub mod ci_add_board;
pub mod ci_doctor;
pub mod ci_improve;
pub mod ci_init;
pub mod ci_render;
pub mod ci_run_local;
pub mod ci_validate;
pub mod core_new;
pub mod evidence;
pub mod release_check;
pub mod self_check;
pub mod wrapper;

// Stamps live in each command-generator crate so submodules and external
// crates (af-template, af-wrapper-gen, af-constructor-export, af-cli/ci_*)
// stay independent. The contract is documented at docs/dev-roadmap.md:
// every generated file carries `Generated by AccelFury IP Toolchain` and is
// covered by an integration test under crates/af-cli/tests/cli.rs.
