// SPDX-License-Identifier: Apache-2.0

use crate::ci::{
    artifacts::artifact_paths_from_root,
    config::{CiBoardConfig, CiConfig},
    detector::ProjectProfile,
    is_board_complete,
    scanner::RepoScan,
};

const WORKFLOW_NAME: &str = "HDL CI";

pub fn render_workflow(config: &CiConfig, scan: &RepoScan, profile: ProjectProfile) -> String {
    let mut out = String::new();
    out.push_str("# Generated by AccelFury IP Toolchain\n");
    out.push_str(&format!("name: {WORKFLOW_NAME}\n\n"));
    out.push_str("on:\n");
    out.push_str("  push:\n");
    out.push_str("    branches: [\"main\"]\n");
    out.push_str("  pull_request:\n");
    out.push_str("  workflow_dispatch:\n\n");
    out.push_str("permissions:\n");
    out.push_str("  contents: read\n\n");
    out.push_str("jobs:\n");

    if should_add_simulation_job(config, scan, profile) {
        out.push_str(&render_sim_job(config, scan, profile));
    }

    out.push_str(&render_synth_job(config));

    if scan.has_sby || !scan.formal_files.is_empty() {
        out.push_str(&render_formal_job(config));
    }

    for (index, board) in config
        .boards
        .iter()
        .filter(|board| board.enabled)
        .enumerate()
    {
        if is_board_complete(board, scan.repo_root.as_path()) {
            out.push_str(&render_pnr_job(config, board, index));
        }
    }

    out.push_str(&render_package_job(config, scan));
    out
}

fn should_add_simulation_job(config: &CiConfig, scan: &RepoScan, profile: ProjectProfile) -> bool {
    if !config.simulation.enabled {
        return false;
    }
    if !config.simulation.command.trim().is_empty() {
        return true;
    }
    if scan.has_make_test_target {
        return profile == ProjectProfile::VerilogWithIverilogMake
            || profile == ProjectProfile::VerilatorCpp;
    }
    false
}

fn render_sim_job(config: &CiConfig, scan: &RepoScan, profile: ProjectProfile) -> String {
    let artifact_root = "artifacts/openfpga-ci";
    let command = if !config.simulation.command.trim().is_empty() {
        config.simulation.command.as_str()
    } else if scan.has_make_test_target {
        "cd sim && make test"
    } else {
        "echo no simulation target"
    };
    let tool_checks = if profile == ProjectProfile::VerilogWithIverilogMake {
        "          if ! command -v iverilog >/dev/null; then\n            echo \"iverilog missing\"; exit 1; fi\n            iverilog -V\n          if ! command -v vvp >/dev/null; then\n            echo \"vvp missing\"; exit 1; fi\n            vvp -V\n          if [ -d sim/build ]; then\n            find sim/build -type f -name \"*.log\" -exec cp {} artifacts/openfpga-ci/logs/ \\;\n          fi"
    } else {
        "          true"
    };
    format!(
        "  sim:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Simulation\n        run: |\n          set -euo pipefail\n          mkdir -p {artifact_root}/logs\n          {tool_checks}\n          {command} 2>&1 | tee {artifact_root}/logs/sim.log\n      - name: Upload simulation logs\n        if: always()\n        uses: actions/upload-artifact@v4\n        with:\n          name: af-sim-artifacts\n          path: |\n            {artifact_root}/logs/sim.log\n\n"
    )
}

fn render_synth_job(config: &CiConfig) -> String {
    let artifact_root = config.sorted_artifacts_root();
    let read_globs = config
        .core
        .source_globs
        .iter()
        .filter(|entry| !entry.trim().is_empty())
        .map(|entry| entry.to_string())
        .collect::<Vec<_>>()
        .join(" ");
    let command = format!(
        "yosys -p 'read_verilog -sv {read_globs}; hierarchy -check -top {top}; write_json {artifact_root}/synth/synth_core.json'",
        top = config.core.top
    );

    format!(
        "  synth_core:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Yosys synth\n        run: |\n          set -euo pipefail\n          mkdir -p {artifact_root}/synth\n          mkdir -p {artifact_root}/logs\n          {command} | tee {artifact_root}/logs/synth.log\n      - name: Capture tool versions\n        if: always()\n        run: |\n          set -euo pipefail\n          if command -v yosys >/dev/null; then\n            yosys -V | tee {artifact_root}/logs/tool-versions.txt\n          else\n            echo \"yosys: not found\" > {artifact_root}/logs/tool-versions.txt\n          fi\n\n",
    )
}

fn render_formal_job(config: &CiConfig) -> String {
    let artifact_root = config.sorted_artifacts_root();
    format!(
        "  formal:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Formal checks\n        run: |\n          set -euo pipefail\n          mkdir -p {artifact_root}/logs\n          if command -v sby >/dev/null; then\n            for file in formal/*.sby; do\n              sby -f \"$file\";\n            done\n          else\n            echo \"sby: not found\";\n            exit 1;\n          fi\n\n",
    )
}

fn render_pnr_job(config: &CiConfig, board: &CiBoardConfig, index: usize) -> String {
    let artifact_root = config.sorted_artifacts_root();
    let safe_name = safe_file_name(&board.name);
    let pnr_artifact = format!("{artifact_root}/pnr/{safe_name}.json");
    let command = match board.family.to_lowercase().as_str() {
        "gowin" => format!(
            "nextpnr-gowin --device {device} --package {package} --json {root}/synth/synth_core.json --pcf {constraints} --write {root}/pnr/{name}.json",
            device = board.device,
            package = board.pack_device,
            constraints = board.constraints,
            root = artifact_root,
            name = safe_name,
        ),
        "ecp5" => format!(
            "nextpnr-ecp5 --json {root}/synth/synth_core.json --lpf {constraints} --write {root}/pnr/{name}.json",
            constraints = board.constraints,
            root = artifact_root,
            name = safe_name,
        ),
        "ice40" => format!(
            "nextpnr-ice40 --json {root}/synth/synth_core.json --pcf {constraints} --write {root}/pnr/{name}.json",
            constraints = board.constraints,
            root = artifact_root,
            name = safe_name,
        ),
        _ => format!("echo \"unsupported family: {}\"; exit 1", board.family),
    };
    format!(
        "  pnr_{index}:\n    needs: [synth_core]\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - name: Board P&R {name}\n        run: |\n          set -euo pipefail\n          mkdir -p {artifact_root}/pnr\n          {command}\n      - name: Upload P&R artifacts\n        if: always()\n        uses: actions/upload-artifact@v4\n        with:\n          name: af-pnr-{name}\n          path: |\n            {pnr_artifact}\n\n",
        index = index,
        name = safe_name,
        artifact_root = artifact_root,
        command = command,
        pnr_artifact = pnr_artifact,
    )
}

fn render_package_job(config: &CiConfig, _scan: &RepoScan) -> String {
    let artifact_root = config.sorted_artifacts_root();
    let paths = artifact_paths_from_root(config.sorted_artifacts_root());
    let mut lines = String::new();
    for path in paths {
        lines.push_str(&format!("            {path}\n"));
    }

    format!(
        "  package_artifacts:\n    runs-on: ubuntu-latest\n    needs: [synth_core]\n    steps:\n      - name: Prepare artifact reports\n        run: |\n          set -euo pipefail\n          mkdir -p {artifact_root}/reports\n          if command -v sha256sum >/dev/null; then\n            (cd {artifact_root} && find . -type f \\( -name \"*.json\" -o -name \"*.log\" -o -name \"SHA256SUMS\" \\) -print0 | \\\n            xargs -0 sha256sum > SHA256SUMS)\n          fi\n      - name: Upload artifacts\n        if: always()\n        uses: actions/upload-artifact@v4\n        with:\n          name: af-ci-artifacts\n          path: |\n{paths}\n\n",
        artifact_root = artifact_root,
        paths = lines
    )
}

pub fn render_pr_template(profile: ProjectProfile) -> String {
    let mut out = String::new();
    out.push_str("<!-- Generated by AccelFury IP Toolchain -->\n");
    out.push_str("## CI Checklist\n\n");
    out.push_str("- [ ] Simulation job checks regressions\n");
    out.push_str("- [ ] Yosys hierarchy/check and JSON synthesis succeeds\n");
    out.push_str("- [ ] Artifact bundle is produced and attached\n");
    out.push_str("- [ ] `docs/ci.md` contains what CI can and cannot prove\n");
    out.push_str("\n### Artifacts\n");
    out.push_str("- logs/tool-versions.txt\n");
    out.push_str("- synth/*.json\n");
    out.push_str("- reports/*.json\n");
    out.push_str("- SHA256SUMS\n");
    if matches!(
        profile,
        ProjectProfile::Verilog2001CoreOnly | ProjectProfile::VerilogWithIverilogMake
    ) {
        out.push_str("- [ ] add tests\n");
    }
    out
}

pub fn render_docs(config: &CiConfig, scan: &RepoScan, profile: ProjectProfile) -> String {
    let mut out = String::new();
    out.push_str("<!-- Generated by AccelFury IP Toolchain -->\n");
    out.push_str("# CI contract\n\n");
    out.push_str(&format!("Project: `{}`\n", config.project.name));
    out.push_str(&format!("Detected HDL profile: `{}`\n", profile.as_str()));
    out.push_str(&format!("Top module: `{}`\n\n", config.core.top));

    out.push_str("## Что CI проверяет\n");
    out.push_str("- Yosys hierarchy и JSON-synthesis core-модуля.\n");
    out.push_str("- Базовый прогон статических проверок (формат и структура).\n");
    if should_add_simulation_job(config, scan, profile) {
        out.push_str("- Регрессионную симуляцию.\n");
    }
    if scan.has_sby {
        out.push_str("- Формальная верификация при наличии `.sby`.\n");
    }
    if scan.top_candidates.len() == 1 {
        out.push_str("- Top-модуль определён автоматически.\n");
    }

    if !config.boards.is_empty() {
        out.push_str("\n## Board targets\n");
        for board in &config.boards {
            out.push_str(&format!(
                "- `{}`: family={}, constraints={}\n",
                board.name, board.family, board.constraints
            ));
        }
    }

    out.push_str("\n## Что CI не доказывает\n");
    out.push_str("- CI не доказывает timing signoff.\n");
    out.push_str("- CI не доказывает CDC signoff.\n");
    out.push_str("- CI не доказывает vendor-tool implementation или hardware-ready статус.\n");
    out.push_str("- Открытые OSS проверки не заменяют полный in-field hardware review.\n");

    out
}

fn safe_file_name(text: &str) -> String {
    text.chars()
        .map(|ch| match ch {
            'a'..='z' | 'A'..='Z' | '0'..='9' | '-' | '_' => ch,
            _ => '_',
        })
        .collect()
}
