// SPDX-License: Apache-2.0

use crate::ci::{config::CiConfig, scanner::RepoScan};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Detection {
    pub hdl: String,
    pub core_top: String,
    pub rtl_files: Vec<String>,
    pub test_flow: serde_json::Value,
    pub boards: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CiDiagnosticReport {
    pub schema_version: String,
    #[serde(default = "default_generated_by")]
    pub generated_by: String,
    pub project: String,
    pub status: String,
    pub detected: Detection,
    pub generated_files: Vec<String>,
    pub blocking_errors: Vec<String>,
    pub warnings: Vec<String>,
    pub artifact_contract: Vec<String>,
    pub next_actions: Vec<String>,
}

fn default_generated_by() -> String {
    "Generated by AccelFury IP Toolchain".to_string()
}

impl CiDiagnosticReport {
    pub fn pass(project: &str, config: &CiConfig, scan: &RepoScan) -> Self {
        let mut report = Self {
            schema_version: "1.0".to_string(),
            generated_by: default_generated_by(),
            project: project.to_string(),
            status: "pass".to_string(),
            detected: build_detection(config, scan),
            generated_files: Vec::new(),
            blocking_errors: Vec::new(),
            warnings: Vec::new(),
            artifact_contract: crate::ci::artifacts::allowlist()
                .into_iter()
                .map(|path| path.to_string())
                .collect(),
            next_actions: Vec::new(),
        };
        if config.boards.is_empty() {
            report
                .next_actions
                .push("add_board flow requires explicit --family/platform profile".to_string());
        }
        report
    }

    pub fn with_warning(
        project: &str,
        config: &CiConfig,
        scan: &RepoScan,
        warning: impl Into<String>,
    ) -> Self {
        let mut report = Self::pass(project, config, scan);
        report.status = "warning".to_string();
        report.warnings.push(warning.into());
        report
    }

    pub fn with_blocking(
        project: &str,
        config: &CiConfig,
        scan: &RepoScan,
        blocking: impl Into<String>,
    ) -> Self {
        let mut report = Self::pass(project, config, scan);
        report.status = "fail".to_string();
        report.blocking_errors.push(blocking.into());
        report
    }
}

pub fn build_detection_map(config: &CiConfig, scan: &RepoScan) -> serde_json::Value {
    let mut detected = serde_json::Map::new();
    detected.insert(
        "hdl".to_string(),
        serde_json::json!(config.project.hdl.clone()),
    );
    detected.insert(
        "core_top".to_string(),
        serde_json::json!(config.core.top.clone()),
    );
    detected.insert(
        "rtl_files".to_string(),
        serde_json::Value::Array(
            scan.rtl_files
                .iter()
                .map(|path| serde_json::Value::String(path.display().to_string()))
                .collect(),
        ),
    );
    let mut flow = serde_json::Map::new();
    flow.insert(
        "simulation".to_string(),
        serde_json::json!(scan.has_make_test_target),
    );
    flow.insert("formal".to_string(), serde_json::json!(scan.has_sby));
    detected.insert("test_flow".to_string(), serde_json::Value::Object(flow));
    detected.insert(
        "boards".to_string(),
        serde_json::Value::Array(
            config
                .boards
                .iter()
                .map(|board| serde_json::json!({ "name": board.name.clone() }))
                .collect(),
        ),
    );
    serde_json::Value::Object(detected)
}

fn build_detection(config: &CiConfig, scan: &RepoScan) -> Detection {
    let mut test_flow = serde_json::Map::new();
    test_flow.insert(
        "simulation".to_string(),
        serde_json::json!(scan.has_make_test_target),
    );
    test_flow.insert("formal".to_string(), serde_json::json!(scan.has_sby));

    Detection {
        hdl: config.project.hdl.clone(),
        core_top: config.core.top.clone(),
        rtl_files: scan
            .rtl_files
            .iter()
            .map(|path| path.display().to_string())
            .collect(),
        test_flow: serde_json::Value::Object(test_flow),
        boards: config
            .boards
            .iter()
            .map(|board| board.name.clone())
            .collect(),
    }
}
