// SPDX-License-Identifier: LicenseRef-AccelFury-Source-Available-1.0
// Generated by AccelFury IP Toolchain
`default_nettype none

module vendor_aware_skeleton_work_ram
#(
    parameter DATA_WIDTH = 64,
    parameter ADDR_WIDTH = 12
)
(
    input wire clk,
    input wire we,
    input wire [ADDR_WIDTH-1:0] addr,
    input wire [DATA_WIDTH-1:0] d,
    output reg [DATA_WIDTH-1:0] q
);

reg [DATA_WIDTH-1:0] mem [0:(1 << ADDR_WIDTH)-1];

always @(posedge clk) begin
    if (we) begin
        mem[addr] <= d;
    end
    q <= mem[addr];
end

endmodule

`default_nettype wire
