// SPDX-License-Identifier: LicenseRef-AccelFury-Source-Available-1.0
// Generated by AccelFury IP Toolchain
`default_nettype none

module vendor_aware_skeleton
#(
    parameter DATA_WIDTH = 64,
    parameter ADDR_WIDTH = 12
)
(
    input wire clk,
    input wire rst_n,
    input wire start,
    output wire done,
    input wire [DATA_WIDTH-1:0] data_i,
    output wire [DATA_WIDTH-1:0] data_o
);

wire [DATA_WIDTH-1:0] scratch_q;
wire [ADDR_WIDTH-1:0] scratch_addr;
wire scratch_we;

vendor_aware_skeleton_core
#(
    .DATA_WIDTH(DATA_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
)
u_core (
    .clk          (clk),
    .rst_n        (rst_n),
    .start        (start),
    .done         (done),
    .data_i       (data_i),
    .data_o       (data_o),
    .scratch_q    (scratch_q),
    .scratch_addr (scratch_addr),
    .scratch_we   (scratch_we)
);

vendor_aware_skeleton_work_ram
#(
    .DATA_WIDTH(DATA_WIDTH),
    .ADDR_WIDTH(ADDR_WIDTH)
)
u_work_ram (
    .clk  (clk),
    .we   (scratch_we),
    .addr (scratch_addr),
    .d    (data_i),
    .q    (scratch_q)
);

endmodule

`default_nettype wire
