#!/usr/bin/env bash
# Generated by AccelFury IP Toolchain
set -euo pipefail

AF_BIN="${AF_BIN:-${CARGO_TARGET_DIR:-target}/debug/af}"
BUILD_ROOT="${AF_BUILD_ROOT:-/tmp/af-build-smoke}"
CORE_DIR="${AF_CORE_DIR:-examples/af-pdm-rx}"
ICARUS_CORE_DIR="${AF_ICARUS_CORE_DIR:-examples/af-reset-sync}"

case "${BUILD_ROOT}" in
  ""|"/"|".")
    echo "Refusing unsafe AF_BUILD_ROOT=${BUILD_ROOT}" >&2
    exit 2
    ;;
esac

rm -rf "${BUILD_ROOT}"
mkdir -p "${BUILD_ROOT}/logs"

echo "== AccelFury Docker smoke: tool visibility =="
verilator --version
fusesoc --version
xmllint --version
python3 --version
python3 -c "import edalize; print('edalize import ok')"
if python3 -c "import litex; print('litex import ok')"; then
  :
else
  echo "LiteX Python package is optional for MVP skeleton generation."
fi
iverilog -V | sed -n '1p'
vvp -V | sed -n '1p'
yosys -V
boolector --version | sed -n '1p'
z3 --version | sed -n '1p'
yices-smt2 --version | sed -n '1p'
bitwuzla --version | sed -n '1p'
cvc5 --version | sed -n '1p'

echo "== AccelFury Docker smoke: Rust build =="
if [ -x "${AF_BIN}" ]; then
  echo "Using prebuilt AF binary: ${AF_BIN}"
else
  echo "Prebuilt AF binary is unavailable; building workspace binary."
  cargo build --locked -p af-cli --bin af
  AF_BIN="${CARGO_TARGET_DIR:-target}/debug/af"
fi

echo "== AccelFury Docker smoke: CLI diagnostics =="
"${AF_BIN}" --build-root "${BUILD_ROOT}" doctor --json | tee "${BUILD_ROOT}/logs/doctor.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" backend list --json | tee "${BUILD_ROOT}/logs/backend-list.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" self check --json | tee "${BUILD_ROOT}/logs/self-check.json"

echo "== AccelFury Docker smoke: manifest and core checks =="
"${AF_BIN}" --build-root "${BUILD_ROOT}" manifest validate "${CORE_DIR}/af-core.toml" --json | tee "${BUILD_ROOT}/logs/manifest-validate.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" core check "${CORE_DIR}" --json | tee "${BUILD_ROOT}/logs/core-check.json"

echo "== AccelFury Docker smoke: Verilator =="
"${AF_BIN}" --build-root "${BUILD_ROOT}" core lint "${CORE_DIR}" --backend verilator --json | tee "${BUILD_ROOT}/logs/verilator-lint.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" core sim "${CORE_DIR}" --backend verilator --json | tee "${BUILD_ROOT}/logs/verilator-sim.json"

echo "== AccelFury Docker smoke: Icarus =="
"${AF_BIN}" --build-root "${BUILD_ROOT}" core lint "${ICARUS_CORE_DIR}" --backend icarus --json | tee "${BUILD_ROOT}/logs/icarus-lint.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" core sim "${ICARUS_CORE_DIR}" --backend icarus --json | tee "${BUILD_ROOT}/logs/icarus-sim.json"

echo "== AccelFury Docker smoke: FuseSoC and LiteX wrappers =="
"${AF_BIN}" --build-root "${BUILD_ROOT}" wrapper generate "${CORE_DIR}" --target fusesoc --json | tee "${BUILD_ROOT}/logs/fusesoc-wrapper.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" wrapper generate "${CORE_DIR}" --target litex --board tang-nano-20k --json | tee "${BUILD_ROOT}/logs/litex-wrapper.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" build "${CORE_DIR}" --board tang-nano-20k --backend litex --json | tee "${BUILD_ROOT}/logs/litex-build.json"

echo "== AccelFury Docker smoke: Yosys =="
"${AF_BIN}" --build-root "${BUILD_ROOT}" core lint "${CORE_DIR}" --backend yosys --json | tee "${BUILD_ROOT}/logs/yosys-lint.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" build "${CORE_DIR}" --board tang-nano-20k --backend yosys --json | tee "${BUILD_ROOT}/logs/yosys-build.json"

echo "== AccelFury Docker smoke: package and report contracts =="
"${AF_BIN}" --build-root "${BUILD_ROOT}" core package "${CORE_DIR}" --format manifest --json | tee "${BUILD_ROOT}/logs/core-package.json"
"${AF_BIN}" --build-root "${BUILD_ROOT}" core report "${CORE_DIR}" --json | tee "${BUILD_ROOT}/logs/core-report.json"

echo "== AccelFury Docker smoke: legacy manifest migration dry-run =="
MIGRATION_DIR="${BUILD_ROOT}/migration"
mkdir -p "${MIGRATION_DIR}"
cp "${CORE_DIR}/af-core.toml" "${MIGRATION_DIR}/af-core.toml"
"${AF_BIN}" --build-root "${BUILD_ROOT}" manifest migrate "${MIGRATION_DIR}/af-core.toml" --from 0.1 --to 0.2 --json | tee "${BUILD_ROOT}/logs/manifest-migrate.json"

echo "Docker smoke passed. Reports: ${BUILD_ROOT}/reports"
