#!/usr/bin/env bash
# Generated by AccelFury IP Toolchain
set -euo pipefail

AF_BIN="${AF_BIN:-}"
BUILD_ROOT="${AF_BUILD_ROOT:-.af-build/oss-hdl-smoke}"

case "${BUILD_ROOT}" in
  ""|"/"|".")
    echo "Refusing unsafe AF_BUILD_ROOT=${BUILD_ROOT}" >&2
    exit 2
    ;;
esac

case "${BUILD_ROOT}" in
  /*) ;;
  *) BUILD_ROOT="$(pwd)/${BUILD_ROOT}" ;;
esac

if [ -z "${AF_BIN}" ]; then
  cargo build --locked -p af-cli --bin af
  AF_BIN="${CARGO_TARGET_DIR:-target}/debug/af"
elif [ ! -x "${AF_BIN}" ]; then
  echo "AF_BIN is not executable: ${AF_BIN}" >&2
  exit 2
fi

mkdir -p "${BUILD_ROOT}/logs"

run_json() {
  local label="$1"
  shift
  echo "== ${label} =="
  "${AF_BIN}" --json --build-root "${BUILD_ROOT}/${label}" "$@" \
    | tee "${BUILD_ROOT}/logs/${label}.json"
}

run_json "doctor" doctor
run_json "pdm-verilator-sim" core sim examples/af-pdm-rx --backend verilator
run_json "pdm-icarus-sim" core sim examples/af-pdm-rx --backend icarus
run_json "pdm-yosys-lint" core lint examples/af-pdm-rx --backend yosys
run_json "mod-add-verilator-lint" core lint examples/af-mod-add --backend verilator
run_json "mod-add-verilator-sim" core sim examples/af-mod-add --backend verilator
run_json "mod-add-icarus-skip" core sim examples/af-mod-add --backend icarus
run_json "reset-sync-verilator-sim" core sim examples/af-reset-sync --backend verilator
run_json "reset-sync-icarus-sim" core sim examples/af-reset-sync --backend icarus
run_json "reset-sync-sby-formal" core formal examples/af-reset-sync --backend sby

echo "OSS HDL smoke passed. Logs: ${BUILD_ROOT}/logs"
