// SPDX-License-Identifier: LicenseRef-AccelFury-Source-Available-1.0
// Generated by AccelFury IP Toolchain
`default_nettype none

module vendor_aware_skeleton_core
#(
    parameter DATA_WIDTH = 64,
    parameter ADDR_WIDTH = 12
)
(
    input wire clk,
    input wire rst_n,
    input wire start,
    output reg done,
    input wire [DATA_WIDTH-1:0] data_i,
    output reg [DATA_WIDTH-1:0] data_o,
    input wire [DATA_WIDTH-1:0] scratch_q,
    output reg [ADDR_WIDTH-1:0] scratch_addr,
    output reg scratch_we
);

always @(posedge clk or negedge rst_n) begin
    if (!rst_n) begin
        done <= 1'b0;
        data_o <= {DATA_WIDTH{1'b0}};
        scratch_addr <= {ADDR_WIDTH{1'b0}};
        scratch_we <= 1'b0;
    end else begin
        done <= start;
        data_o <= scratch_q ^ data_i;
        scratch_addr <= scratch_addr + 1'b1;
        scratch_we <= start;
    end
end

endmodule

`default_nettype wire
