// SPDX-License-Identifier: Apache-2.0
//
// Wrapper-target parser and end-to-end artefact emission. The detailed
// byte-level golden snapshots live in Tier 7.C (`golden_artifacts.rs`
// with insta); these tests pin the public contract: target resolution,
// file naming, and writability under `--build-root`.

mod common;

use af_wrapper_gen::{
    generate_wrapper, wrapper_target_capabilities, WrapperGenError, WrapperTarget,
};
use common::clone_example;
use tempfile::TempDir;

#[test]
fn wrapper_target_parses_documented_values() {
    assert_eq!(
        WrapperTarget::parse("fusesoc").unwrap(),
        WrapperTarget::FuseSoc
    );
    assert_eq!(WrapperTarget::parse("litex").unwrap(), WrapperTarget::LiteX);
    assert_eq!(
        WrapperTarget::parse("ipxact").unwrap(),
        WrapperTarget::IpXact
    );
    assert_eq!(
        WrapperTarget::parse("stream-fifo").unwrap(),
        WrapperTarget::StreamFifo
    );
}

#[test]
fn wrapper_target_rejects_other_strings() {
    let err = WrapperTarget::parse("vendor-specific").unwrap_err();
    assert_eq!(err.code(), "AF_WRAPPER_TARGET_UNSUPPORTED");
    assert_eq!(err.exit_code(), 2);
    assert!(!err.hint().is_empty());
}

#[test]
fn wrapper_target_capabilities_identify_generated_protocol_adapters() {
    let capabilities = wrapper_target_capabilities();
    let stream_fifo = capabilities
        .iter()
        .find(|capability| capability.target == "stream-fifo")
        .expect("stream-fifo capability");

    assert!(stream_fifo.generates_rtl);
    assert_eq!(
        stream_fifo.adapter_kind.as_deref(),
        Some("stream_fifo_adapter")
    );
    assert!(capabilities
        .iter()
        .any(|capability| capability.target == "fusesoc" && !capability.generates_rtl));
}

#[test]
fn fusesoc_wrapper_writes_a_core_file() {
    let project = clone_example("af-mod-add");
    let build_root = TempDir::new().unwrap();
    let report = generate_wrapper(
        project.path(),
        build_root.path(),
        WrapperTarget::FuseSoc,
        None,
    )
    .expect("fusesoc wrapper");
    assert_eq!(report.target, WrapperTarget::FuseSoc);
    assert_eq!(report.artifacts.len(), 1);
    let artifact = &report.artifacts[0];
    assert!(
        artifact.is_file(),
        "fusesoc artefact must exist: {}",
        artifact.display()
    );
    assert!(
        artifact.starts_with(build_root.path()),
        "artefact must live under --build-root, got {}",
        artifact.display()
    );
    assert_eq!(artifact.extension().and_then(|e| e.to_str()), Some("core"));
}

#[test]
fn litex_wrapper_writes_a_python_skeleton() {
    let project = clone_example("af-mod-add");
    let build_root = TempDir::new().unwrap();
    let report = generate_wrapper(
        project.path(),
        build_root.path(),
        WrapperTarget::LiteX,
        Some("digilent_arty_a7"),
    )
    .expect("litex wrapper");
    assert_eq!(report.artifacts.len(), 1);
    let artifact = &report.artifacts[0];
    assert!(artifact.is_file());
    let text = std::fs::read_to_string(artifact).unwrap();
    assert!(
        text.contains("Generated by AccelFury IP Toolchain"),
        "litex skeleton must carry the generated-by stamp"
    );
}

#[test]
fn ipxact_wrapper_writes_valid_xml() {
    let project = clone_example("af-mod-add");
    let build_root = TempDir::new().unwrap();
    let report = generate_wrapper(
        project.path(),
        build_root.path(),
        WrapperTarget::IpXact,
        None,
    )
    .expect("ipxact wrapper");
    let artifact = &report.artifacts[0];
    let text = std::fs::read_to_string(artifact).unwrap();
    assert!(text.starts_with("<?xml version=\"1.0\""));
    assert!(text.contains("1685-2022"));
    assert!(text.contains("<ipxact:component"));
    assert!(text.contains("<ipxact:vendor>accelfury</ipxact:vendor>"));
    assert!(text.contains("<ipxact:fileSets>"));
    assert!(text.contains("<af:portabilityTier>"));
    assert!(
        report.limitations.iter().any(|l| l.contains("IP-XACT")),
        "ipxact wrapper must disclose its adapter-only nature"
    );
}

#[test]
fn stream_fifo_wrapper_writes_verilog_adapter() {
    let project = TempDir::new().unwrap();
    write_fifo_project(project.path());
    let build_root = TempDir::new().unwrap();
    let report = generate_wrapper(
        project.path(),
        build_root.path(),
        WrapperTarget::StreamFifo,
        None,
    )
    .expect("stream fifo wrapper");
    assert_eq!(report.target, WrapperTarget::StreamFifo);
    let artifact = &report.artifacts[0];
    assert!(artifact.is_file());
    let text = std::fs::read_to_string(artifact).unwrap();
    assert!(text.contains("module af_sync_fifo_stream_fifo"));
    assert!(text.contains("assign s_ready      = !fifo_full_w || fifo_rd_en_w;"));
    assert!(text.contains(".wr_en(fifo_wr_en_w)"));
}

#[test]
fn ipxact_filename_uses_sanitised_identifiers() {
    use af_manifest::CoreManifest;
    use af_wrapper_gen::generate_ipxact_skeleton;

    let project = clone_example("af-mod-add");
    let manifest =
        CoreManifest::from_path(project.path().join("af-core.toml")).expect("manifest loads");
    let skeleton = generate_ipxact_skeleton(&manifest, None);
    assert!(skeleton.file_name.ends_with(".xml"));
    // Every char in the file name must be a-z, 0-9, _ or '-'.
    for ch in skeleton.file_name.trim_end_matches(".xml").chars() {
        assert!(
            ch.is_ascii_alphanumeric() || ch == '_' || ch == '-',
            "ipxact filename must be sanitised: {}",
            skeleton.file_name
        );
    }
}

#[test]
fn unknown_target_string_returns_envelope_error() {
    let res = WrapperTarget::parse("unknown");
    match res {
        Err(WrapperGenError::UnsupportedTarget { target }) => {
            assert_eq!(target, "unknown");
        }
        other => panic!("expected UnsupportedTarget, got {other:?}"),
    }
}

fn write_fifo_project(root: &std::path::Path) {
    std::fs::create_dir_all(root.join("rtl")).unwrap();
    std::fs::write(
        root.join("LICENSE"),
        "AccelFury Source Available License v1.0\n\nCopyright (c) 2026 AccelFury.\n",
    )
    .unwrap();
    std::fs::write(
        root.join("COMMERCIAL-LICENSE.md"),
        "# Commercial Licensing\n\nClosed-source and commercial use requires a separate paid commercial license from AccelFury.\nCommercial triggers include closed-source FPGA products and proprietary repositories.\nContact AccelFury for commercial terms, support, warranty options, and custom integration work.\n",
    )
    .unwrap();
    std::fs::write(
        root.join("af-core.toml"),
        r#"
af_version = "0.3"
name = "af-sync-fifo"
vendor = "accelfury"
library = "ip"
core = "af_sync_fifo"
version = "0.1.0"

[metadata]
license = "AccelFury Source Available License v1.0"

[rtl]
top = "af_sync_fifo"
language = "verilog-2001"

[sources]
files = ["rtl/af_sync_fifo.v"]

[[parameters]]
name = "DATA_BITS"
value = "32"

[[parameters]]
name = "FIFO_ADDR_BITS"
value = "4"

[[parameters]]
name = "ALMOST_FULL_TH"
value = "(1 << FIFO_ADDR_BITS) - 2"

[[clocks]]
name = "clk"
port = "clk"

[[resets]]
name = "rst"
port = "rst"
active = "high"

[[ports]]
name = "clk"
direction = "input"
width = 1

[[ports]]
name = "rst"
direction = "input"
width = 1

[[ports]]
name = "clear"
direction = "input"
width = 1

[[ports]]
name = "wr_en"
direction = "input"
width = 1

[[ports]]
name = "wr_data"
direction = "input"
width = "DATA_BITS"

[[ports]]
name = "full"
direction = "output"
width = 1

[[ports]]
name = "almost_full"
direction = "output"
width = 1

[[ports]]
name = "rd_en"
direction = "input"
width = 1

[[ports]]
name = "rd_data"
direction = "output"
width = "DATA_BITS"

[[ports]]
name = "empty"
direction = "output"
width = 1

[[ports]]
name = "level"
direction = "output"
width = "FIFO_ADDR_BITS + 1"

[contracts.fifo]
kind = "single_clock"
interface = "wr_rd_control"
read_mode = "first_word_fall_through"
full_write_policy = "accept_when_full_with_read"
clear_behavior = "sync_flush"
overflow_policy = "backpressure_no_drop"
"#,
    )
    .unwrap();
    std::fs::write(
        root.join("rtl/af_sync_fifo.v"),
        r#"`default_nettype none
module af_sync_fifo #(
    parameter DATA_BITS = 32,
    parameter FIFO_ADDR_BITS = 4,
    parameter ALMOST_FULL_TH = (1 << FIFO_ADDR_BITS) - 2
) (
    input wire clk,
    input wire rst,
    input wire clear,
    input wire wr_en,
    input wire [DATA_BITS-1:0] wr_data,
    output wire full,
    output wire almost_full,
    input wire rd_en,
    output wire [DATA_BITS-1:0] rd_data,
    output wire empty,
    output wire [FIFO_ADDR_BITS:0] level
);
endmodule
`default_nettype wire
"#,
    )
    .unwrap();
}
