// SPDX-License-Identifier: Apache-2.0
//
// Wrapper-target parser and end-to-end artefact emission. The detailed
// byte-level golden snapshots live in Tier 7.C (`golden_artifacts.rs`
// with insta); these tests pin the public contract: target resolution,
// file naming, and writability under `--build-root`.

mod common;

use af_wrapper_gen::{generate_wrapper, WrapperGenError, WrapperTarget};
use common::clone_example;
use tempfile::TempDir;

#[test]
fn wrapper_target_parses_documented_values() {
    assert_eq!(
        WrapperTarget::parse("fusesoc").unwrap(),
        WrapperTarget::FuseSoc
    );
    assert_eq!(WrapperTarget::parse("litex").unwrap(), WrapperTarget::LiteX);
    assert_eq!(
        WrapperTarget::parse("ipxact").unwrap(),
        WrapperTarget::IpXact
    );
}

#[test]
fn wrapper_target_rejects_other_strings() {
    let err = WrapperTarget::parse("vendor-specific").unwrap_err();
    assert_eq!(err.code(), "AF_WRAPPER_TARGET_UNSUPPORTED");
    assert_eq!(err.exit_code(), 2);
    assert!(!err.hint().is_empty());
}

#[test]
fn fusesoc_wrapper_writes_a_core_file() {
    let project = clone_example("af-mod-add");
    let build_root = TempDir::new().unwrap();
    let report = generate_wrapper(
        project.path(),
        build_root.path(),
        WrapperTarget::FuseSoc,
        None,
    )
    .expect("fusesoc wrapper");
    assert_eq!(report.target, WrapperTarget::FuseSoc);
    assert_eq!(report.artifacts.len(), 1);
    let artifact = &report.artifacts[0];
    assert!(
        artifact.is_file(),
        "fusesoc artefact must exist: {}",
        artifact.display()
    );
    assert!(
        artifact.starts_with(build_root.path()),
        "artefact must live under --build-root, got {}",
        artifact.display()
    );
    assert_eq!(artifact.extension().and_then(|e| e.to_str()), Some("core"));
}

#[test]
fn litex_wrapper_writes_a_python_skeleton() {
    let project = clone_example("af-mod-add");
    let build_root = TempDir::new().unwrap();
    let report = generate_wrapper(
        project.path(),
        build_root.path(),
        WrapperTarget::LiteX,
        Some("digilent_arty_a7"),
    )
    .expect("litex wrapper");
    assert_eq!(report.artifacts.len(), 1);
    let artifact = &report.artifacts[0];
    assert!(artifact.is_file());
    let text = std::fs::read_to_string(artifact).unwrap();
    assert!(
        text.contains("Generated by AccelFury IP Toolchain"),
        "litex skeleton must carry the generated-by stamp"
    );
}

#[test]
fn ipxact_wrapper_writes_valid_xml() {
    let project = clone_example("af-mod-add");
    let build_root = TempDir::new().unwrap();
    let report = generate_wrapper(
        project.path(),
        build_root.path(),
        WrapperTarget::IpXact,
        None,
    )
    .expect("ipxact wrapper");
    let artifact = &report.artifacts[0];
    let text = std::fs::read_to_string(artifact).unwrap();
    assert!(text.starts_with("<?xml version=\"1.0\""));
    assert!(text.contains("<spirit:component"));
    assert!(text.contains("<spirit:vendor>accelfury</spirit:vendor>"));
    assert!(
        report.limitations.iter().any(|l| l.contains("IP-XACT")),
        "ipxact wrapper must disclose its adapter-only nature"
    );
}

#[test]
fn ipxact_filename_uses_sanitised_identifiers() {
    use af_manifest::CoreManifest;
    use af_wrapper_gen::generate_ipxact_skeleton;

    let project = clone_example("af-mod-add");
    let manifest =
        CoreManifest::from_path(project.path().join("af-core.toml")).expect("manifest loads");
    let skeleton = generate_ipxact_skeleton(&manifest, None);
    assert!(skeleton.file_name.ends_with(".xml"));
    // Every char in the file name must be a-z, 0-9, _ or '-'.
    for ch in skeleton.file_name.trim_end_matches(".xml").chars() {
        assert!(
            ch.is_ascii_alphanumeric() || ch == '_' || ch == '-',
            "ipxact filename must be sanitised: {}",
            skeleton.file_name
        );
    }
}

#[test]
fn unknown_target_string_returns_envelope_error() {
    let res = WrapperTarget::parse("unknown");
    match res {
        Err(WrapperGenError::UnsupportedTarget { target }) => {
            assert_eq!(target, "unknown");
        }
        other => panic!("expected UnsupportedTarget, got {other:?}"),
    }
}
