// SPDX-License-Identifier: Apache-2.0
use af_backend::{AfBackend, BackendReport};
use af_manifest::CoreManifest;
use std::path::Path;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LiteXSkeleton {
    pub file_name: String,
    pub content: String,
    pub warnings: Vec<String>,
    pub limitations: Vec<String>,
}

#[derive(Clone, Debug, Default)]
pub struct LitexBackend;

pub fn generate_litex_skeleton(
    manifest: &CoreManifest,
    module_class: Option<&str>,
) -> LiteXSkeleton {
    let class_name = module_class
        .map(ToString::to_string)
        .unwrap_or_else(|| pascal_ident(&manifest.core));
    let file_name = format!("{}_litex.py", manifest.core.replace('-', "_"));
    let content = format!(
        r#"# Generated by AccelFury IP Toolchain.
# Review signal widths, reset policy, and platform integration before use.
from migen import Module


class {class_name}(Module):
    def __init__(self):
        self.specials += Instance(
            "{top}",
            # TODO: bind LiteX signals to the generated core ports.
        )
"#,
        top = manifest.rtl.top
    );

    LiteXSkeleton {
        file_name,
        content,
        warnings: vec![
            "LiteX wrapper is a skeleton; bind clocks, resets, buses, and platform resources before integration.".to_string(),
        ],
        limitations: vec![
            "Generated LiteX skeleton is not a buyer-grade integration artifact until it is reviewed and tested.".to_string(),
        ],
    }
}

fn pascal_ident(input: &str) -> String {
    let mut out = String::new();
    for part in input
        .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '_'))
        .filter(|part| !part.is_empty())
    {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.extend(chars);
        }
    }
    if out.is_empty() {
        "GeneratedCore".to_string()
    } else {
        out
    }
}

impl AfBackend for LitexBackend {
    fn name(&self) -> &'static str {
        "litex"
    }

    fn doctor(&self) -> Result<BackendReport, af_backend::BackendError> {
        Ok(BackendReport::unavailable(
            self.name(),
            "litex",
            "LiteX backend crate is present, but wrapper/build orchestration is not implemented yet.",
        ))
    }

    fn lint(
        &self,
        _manifest: &CoreManifest,
        _core_dir: &Path,
        _build_root: &Path,
    ) -> Result<BackendReport, af_backend::BackendError> {
        self.doctor()
    }

    fn sim(
        &self,
        _manifest: &CoreManifest,
        _core_dir: &Path,
        _build_root: &Path,
    ) -> Result<BackendReport, af_backend::BackendError> {
        self.doctor()
    }
}
