// SPDX-License-Identifier: Apache-2.0
use af_backend::{AfBackend, BackendCapability, BackendReport};
use af_manifest::CoreManifest;
use std::path::Path;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct LiteXSkeleton {
    pub file_name: String,
    pub content: String,
    pub warnings: Vec<String>,
    pub limitations: Vec<String>,
}

#[derive(Clone, Debug, Default)]
pub struct LitexBackend;

pub fn generate_litex_skeleton(manifest: &CoreManifest, board: Option<&str>) -> LiteXSkeleton {
    let class_name = pascal_ident(&manifest.core);
    let board = board.unwrap_or("unbound-board");
    let file_name = format!("{}_litex.py", manifest.core.replace('-', "_"));
    let content = format!(
        r#"# Generated by AccelFury IP Toolchain
# LiteX reference integration skeleton only.
# Handwritten RTL remains the source of hardware logic.
# This file must not generate CDC, FIFO, filters, or bus bridges.

from litex.soc.interconnect import stream


class {class_name}RawPdmRx:
    def __init__(self, platform):
        platform.add_source("{source}")
        self.board = "{board}"
        self.top = "{top}"
        self.raw_stream = stream.Endpoint([("data", 32)])
        # Connect signals explicitly in a board/top integration file.
"#,
        board = board,
        source = manifest
            .sources
            .files
            .first()
            .map(String::as_str)
            .unwrap_or("rtl/unbound.sv"),
        top = manifest.rtl.top
    );

    LiteXSkeleton {
        file_name,
        content,
        warnings: vec![
            "LiteX wrapper is a skeleton; bind clocks, resets, buses, and platform resources before integration.".to_string(),
        ],
        limitations: vec![
            "Generated LiteX skeleton intentionally contains no critical hardware logic.".to_string(),
        ],
    }
}

fn pascal_ident(input: &str) -> String {
    let mut out = String::new();
    for part in input
        .split(|ch: char| !(ch.is_ascii_alphanumeric() || ch == '_'))
        .filter(|part| !part.is_empty())
    {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.extend(chars);
        }
    }
    if out.is_empty() {
        "GeneratedCore".to_string()
    } else {
        out
    }
}

impl AfBackend for LitexBackend {
    fn name(&self) -> &'static str {
        "litex"
    }

    fn capabilities(&self) -> Vec<BackendCapability> {
        vec![BackendCapability {
            name: "wrapper-skeleton".to_string(),
            supported: true,
            detail: Some("Generates a LiteX reference wrapper skeleton only.".to_string()),
        }]
    }

    fn doctor(&self) -> Result<BackendReport, af_backend::BackendError> {
        Ok(BackendReport::unavailable(
            self.name(),
            "litex",
            "LiteX backend crate is present, but wrapper/build orchestration is not implemented yet.",
        ))
    }

    fn lint(
        &self,
        _manifest: &CoreManifest,
        _core_dir: &Path,
        _build_root: &Path,
    ) -> Result<BackendReport, af_backend::BackendError> {
        self.doctor()
    }

    fn sim(
        &self,
        _manifest: &CoreManifest,
        _core_dir: &Path,
        _build_root: &Path,
    ) -> Result<BackendReport, af_backend::BackendError> {
        self.doctor()
    }
}
