// SPDX-License-Identifier: Apache-2.0
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

pub const GENERATED_HEADER: &str = "Generated by AccelFury IP Toolchain";

#[derive(Debug, Error)]
pub enum CiError {
    #[error("unsupported CI target `{target}`")]
    UnsupportedTarget { target: String },
    #[error("failed to create CI directory `{path}`: {message}")]
    CreateDir { path: PathBuf, message: String },
    #[error("failed to write CI file `{path}`: {message}")]
    Write { path: PathBuf, message: String },
}

impl CiError {
    pub fn code(&self) -> &'static str {
        match self {
            CiError::UnsupportedTarget { .. } => "AF_CI_TARGET_UNSUPPORTED",
            CiError::CreateDir { .. } => "AF_CI_CREATE_DIR_FAILED",
            CiError::Write { .. } => "AF_CI_WRITE_FAILED",
        }
    }

    pub fn hint(&self) -> &'static str {
        match self {
            CiError::UnsupportedTarget { .. } => "Use --target github-actions for MVP.",
            CiError::CreateDir { .. } | CiError::Write { .. } => {
                "Check filesystem permissions for the selected output path."
            }
        }
    }

    pub fn exit_code(&self) -> i32 {
        match self {
            CiError::UnsupportedTarget { .. } => 2,
            _ => 5,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct CiArtifact {
    pub path: PathBuf,
    pub content: String,
}

pub fn generate(target: &str) -> Result<String, CiError> {
    match target {
        "github-actions" => Ok(generate_github_actions()),
        other => Err(CiError::UnsupportedTarget {
            target: other.to_string(),
        }),
    }
}

pub fn write(target: &str, output: impl AsRef<Path>) -> Result<CiArtifact, CiError> {
    let content = generate(target)?;
    let output = output.as_ref();
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).map_err(|err| CiError::CreateDir {
            path: parent.to_path_buf(),
            message: err.to_string(),
        })?;
    }
    fs::write(output, &content).map_err(|err| CiError::Write {
        path: output.to_path_buf(),
        message: err.to_string(),
    })?;
    Ok(CiArtifact {
        path: output.to_path_buf(),
        content,
    })
}

pub fn generate_github_actions() -> String {
    format!(
        r#"# {GENERATED_HEADER}
name: AccelFury CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: test
        run: cargo test --workspace
      - name: CLI smoke
        run: |
          cargo run -p af-cli --bin af -- doctor --json
          cargo run -p af-cli --bin af -- core check examples/af-pdm-rx --json
          cargo run -p af-cli --bin af -- wrapper generate examples/af-pdm-rx --target fusesoc --json
      - name: Optional OSS CAD Suite hint
        run: |
          if command -v verilator >/dev/null 2>&1; then
            cargo run -p af-cli --bin af -- core lint examples/af-pdm-rx --backend verilator --json
          else
            echo "Verilator not installed; backend is optional for MVP CI smoke."
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: accelfury-reports
          path: .af-build/**
"#
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn github_actions_has_required_steps() {
        let workflow = generate_github_actions();
        assert!(workflow.contains("cargo fmt --all -- --check"));
        assert!(workflow.contains("cargo clippy --workspace --all-targets -- -D warnings"));
        assert!(workflow.contains("cargo test --workspace"));
        assert!(workflow.contains(GENERATED_HEADER));
    }
}
