// SPDX-License-Identifier: Apache-2.0
use serde::{Deserialize, Serialize};
use std::fs;
use std::path::{Path, PathBuf};
use thiserror::Error;

pub const GENERATED_HEADER: &str = "Generated by AccelFury IP Toolchain";

#[derive(Debug, Error)]
pub enum CiError {
    #[error("unsupported CI target `{target}`")]
    UnsupportedTarget { target: String },
    #[error("unsupported CI backend `{backend}`")]
    UnsupportedBackend { backend: String },
    #[error("failed to create CI directory `{path}`: {message}")]
    CreateDir { path: PathBuf, message: String },
    #[error("failed to write CI file `{path}`: {message}")]
    Write { path: PathBuf, message: String },
}

impl CiError {
    pub fn code(&self) -> &'static str {
        match self {
            CiError::UnsupportedTarget { .. } => "AF_CI_TARGET_UNSUPPORTED",
            CiError::UnsupportedBackend { .. } => "AF_CI_BACKEND_UNSUPPORTED",
            CiError::CreateDir { .. } => "AF_CI_CREATE_DIR_FAILED",
            CiError::Write { .. } => "AF_CI_WRITE_FAILED",
        }
    }

    pub fn hint(&self) -> &'static str {
        match self {
            CiError::UnsupportedTarget { .. } => "Use --target github-actions for MVP.",
            CiError::UnsupportedBackend { .. } => {
                "Use --backends with one of: native, icarus, verilator, yosys, sby, nextpnr, litex."
            }
            CiError::CreateDir { .. } | CiError::Write { .. } => {
                "Check filesystem permissions for the selected output path."
            }
        }
    }

    pub fn exit_code(&self) -> i32 {
        match self {
            CiError::UnsupportedTarget { .. } | CiError::UnsupportedBackend { .. } => 2,
            _ => 5,
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
pub struct CiArtifact {
    pub path: PathBuf,
    pub content: String,
}

#[derive(Clone, Debug, Default)]
pub struct CiGenerateOptions {
    pub backends: Vec<String>,
    pub optional_fail_closed: bool,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
struct BackendMatrixItem {
    backend: &'static str,
    label: &'static str,
    optional: bool,
}

const GITHUB_ACTIONS_DEFAULT_BACKENDS: [BackendMatrixItem; 7] = [
    BackendMatrixItem {
        backend: "native",
        label: "native-lint",
        optional: false,
    },
    BackendMatrixItem {
        backend: "icarus",
        label: "icarus-lint",
        optional: true,
    },
    BackendMatrixItem {
        backend: "verilator",
        label: "verilator-lint-sim",
        optional: true,
    },
    BackendMatrixItem {
        backend: "yosys",
        label: "yosys-lint",
        optional: true,
    },
    BackendMatrixItem {
        backend: "sby",
        label: "sby-formal",
        optional: true,
    },
    BackendMatrixItem {
        backend: "nextpnr",
        label: "nextpnr-doctor",
        optional: true,
    },
    BackendMatrixItem {
        backend: "litex",
        label: "litex-wrapper",
        optional: false,
    },
];

pub fn generate(target: &str) -> Result<String, CiError> {
    generate_with_options(target, &CiGenerateOptions::default())
}

pub fn generate_with_options(target: &str, options: &CiGenerateOptions) -> Result<String, CiError> {
    let backends = resolve_backends(&options.backends)?;
    match target {
        "github-actions" => Ok(generate_github_actions(
            &backends,
            options.optional_fail_closed,
        )),
        other => Err(CiError::UnsupportedTarget {
            target: other.to_string(),
        }),
    }
}

pub fn write(target: &str, output: impl AsRef<Path>) -> Result<CiArtifact, CiError> {
    write_with_options(target, output, &CiGenerateOptions::default())
}

pub fn write_with_options(
    target: &str,
    output: impl AsRef<Path>,
    options: &CiGenerateOptions,
) -> Result<CiArtifact, CiError> {
    let content = generate_with_options(target, options)?;
    let output = output.as_ref();
    if let Some(parent) = output.parent() {
        fs::create_dir_all(parent).map_err(|err| CiError::CreateDir {
            path: parent.to_path_buf(),
            message: err.to_string(),
        })?;
    }
    fs::write(output, &content).map_err(|err| CiError::Write {
        path: output.to_path_buf(),
        message: err.to_string(),
    })?;
    Ok(CiArtifact {
        path: output.to_path_buf(),
        content,
    })
}

fn resolve_backends(requested: &[String]) -> Result<Vec<BackendMatrixItem>, CiError> {
    if requested.is_empty() {
        return Ok(GITHUB_ACTIONS_DEFAULT_BACKENDS.to_vec());
    }

    let mut selected = Vec::new();
    for backend in requested {
        let id = normalize_backend_id(backend);
        let Some(item) = lookup_backend(&id) else {
            return Err(CiError::UnsupportedBackend {
                backend: backend.clone(),
            });
        };
        if !selected
            .iter()
            .any(|entry: &BackendMatrixItem| entry.backend == item.backend)
        {
            selected.push(item);
        }
    }
    Ok(selected)
}

fn normalize_backend_id(backend: &str) -> String {
    match backend
        .trim()
        .to_ascii_lowercase()
        .replace(['_', ' '], "-")
        .as_str()
    {
        "iverilog" | "icarus-verilog" => "icarus".to_string(),
        "symbiyosys" | "formal-sby" => "sby".to_string(),
        "next-pnr" => "nextpnr".to_string(),
        other => other.to_string(),
    }
}

fn lookup_backend(id: &str) -> Option<BackendMatrixItem> {
    GITHUB_ACTIONS_DEFAULT_BACKENDS
        .iter()
        .find(|backend| backend.backend == id)
        .copied()
}

fn generate_github_actions(backends: &[BackendMatrixItem], fail_closed: bool) -> String {
    let matrix = matrix_entries(backends);
    let backend_expr = "${{ matrix.backend }}";
    let label_expr = "${{ matrix.label }}";
    let case = backend_case_script(backends, backend_expr);
    let continue_on_error = if fail_closed {
        String::new()
    } else {
        "      continue-on-error: ${{ matrix.optional }}\n".to_string()
    };

    format!(
        r#"# {GENERATED_HEADER}
name: AccelFury CI

on:
  push:
  pull_request:

jobs:
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - name: rustfmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --workspace --all-targets -- -D warnings
      - name: test
        run: cargo test --workspace
      - name: CLI smoke
        run: |
          cargo run -p af-cli --bin af -- doctor --json
          cargo run -p af-cli --bin af -- self check --json
          cargo run -p af-cli --bin af -- registry check --json
          cargo run -p af-cli --bin af -- board check boards/tang-nano-20k/af-board.toml --json
          cargo run -p af-cli --bin af -- backend list --json
      - name: Publish preflight reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accelfury-reports
          path: .af-build/**
  backend-matrix:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
{matrix}    steps:
      - uses: actions/checkout@v4
{continue_on_error}      - name: Run backend workload
        run: |
          case "{backend_expr}" in
{case}          esac
      - name: Publish backend reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: accelfury-{label_expr}-reports
          path: .af-build/**
  docker-open-source-flow:
    runs-on: ubuntu-latest
    env:
      RUST_TOOLCHAIN: 1.95.0-x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker runtime
        run: docker build --build-arg RUST_TOOLCHAIN=$RUST_TOOLCHAIN -t accelfury-af:ci .
      - name: Docker smoke
        run: |
          docker run --rm \
            -v "$PWD:/work" \
            -v "$HOME/.cargo/registry:/usr/local/cargo/registry" \
            -v "$HOME/.cargo/git:/usr/local/cargo/git" \
            -v "/tmp/af-docker-target:/tmp/af-target" \
            -w /work \
            -e AF_BUILD_ROOT=/work/.af-build/docker-smoke \
            -e RUSTUP_TOOLCHAIN=$RUST_TOOLCHAIN \
            -e CARGO_TARGET_DIR=/tmp/af-target \
            accelfury-af:ci scripts/docker-smoke.sh
      - name: Normalize Docker smoke ownership
        if: always()
        run: |
          set -euo pipefail
          if [ -d .af-build/docker-smoke ]; then
            sudo chown -R "$(id -u):$(id -g)" .af-build/docker-smoke
          fi
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: accelfury-docker-reports
          path: .af-build/docker-smoke/**
"#
    )
}

fn matrix_entries(backends: &[BackendMatrixItem]) -> String {
    let mut output = String::new();
    for backend in backends {
        output.push_str("          - backend: ");
        output.push_str(backend.backend);
        output.push('\n');
        output.push_str("            label: ");
        output.push_str(backend.label);
        output.push('\n');
        output.push_str("            optional: ");
        if backend.optional {
            output.push_str("true");
        } else {
            output.push_str("false");
        }
        output.push('\n');
    }
    output
}

fn backend_case_script(backends: &[BackendMatrixItem], backend_expr: &str) -> String {
    let mut output = String::new();
    for backend in backends {
        output.push_str("            ");
        output.push_str(backend.backend);
        output.push_str(")\n");
        for line in backend_case_lines(backend.backend).iter() {
            output.push_str("              ");
            output.push_str(line);
            output.push('\n');
        }
        output.push_str("              ;;\n");
    }
    output.push_str("            *)\n");
    output.push_str("              echo \"unsupported backend: ");
    output.push_str(backend_expr);
    output.push_str("\"\n");
    output.push_str("              exit 1\n");
    output.push_str("              ;;\n");
    output
}

fn backend_case_lines(backend: &str) -> Vec<&'static str> {
    match backend {
        "native" => vec!["cargo run -p af-cli --bin af -- core lint examples/af-pdm-rx --backend native --json"],
        "icarus" => vec![
            "if ! command -v iverilog >/dev/null 2>&1 || ! command -v vvp >/dev/null 2>&1; then",
            "  echo \"Icarus Verilog toolchain is not installed.\"",
            "  exit 1",
            "fi",
            "cargo run -p af-cli --bin af -- core new /tmp/af-icarus-ci --name af-icarus-ci --language verilog --json",
            "cargo run -p af-cli --bin af -- core lint /tmp/af-icarus-ci --backend icarus --json",
        ],
        "verilator" => vec![
            "if ! command -v verilator >/dev/null 2>&1; then",
            "  echo \"Verilator toolchain is not installed.\"",
            "  exit 1",
            "fi",
            "cargo run -p af-cli --bin af -- core lint examples/af-pdm-rx --backend verilator --json",
            "cargo run -p af-cli --bin af -- core sim examples/af-pdm-rx --backend verilator --json",
        ],
        "yosys" => vec![
            "if ! command -v yosys >/dev/null 2>&1; then",
            "  echo \"Yosys toolchain is not installed.\"",
            "  exit 1",
            "fi",
            "cargo run -p af-cli --bin af -- core lint examples/af-pdm-rx --backend yosys --json",
        ],
        "sby" => vec![
            "if ! command -v sby >/dev/null 2>&1; then",
            "  echo \"SymbiYosys is not installed.\"",
            "  exit 1",
            "fi",
            "cargo run -p af-cli --bin af -- core formal examples/af-mod-add --backend sby --json",
        ],
        "nextpnr" => vec![
            "cargo run -p af-cli --bin af -- backend run nextpnr --target doctor --json",
            "cargo run -p af-cli --bin af -- build examples/af-mod-add --board ulx3s_ecp5 --backend nextpnr --json",
        ],
        "litex" => vec![
            "cargo run -p af-cli --bin af -- wrapper generate examples/af-pdm-rx --target litex --board tang-nano-20k --json",
        ],
        _ => vec!["exit 1"],
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn github_actions_has_required_steps() {
        let workflow = generate_github_actions(&GITHUB_ACTIONS_DEFAULT_BACKENDS, false);
        assert!(workflow.contains("cargo fmt --all -- --check"));
        assert!(workflow.contains("cargo clippy --workspace --all-targets -- -D warnings"));
        assert!(workflow.contains("cargo test --workspace"));
        assert!(workflow.contains("accelfury-${{ matrix.label }}-reports"));
        assert!(workflow.contains("case \"${{ matrix.backend }}\""));
        assert!(workflow.contains("continue-on-error: ${{ matrix.optional }}"));
        assert!(workflow.contains("- backend: native"));
        assert!(workflow.contains("- backend: icarus"));
        assert!(workflow.contains("- backend: verilator"));
        assert!(workflow.contains("- backend: sby"));
        assert!(workflow.contains("- backend: nextpnr"));
        assert!(workflow.contains(GENERATED_HEADER));
    }

    #[test]
    fn github_actions_can_fail_closed() {
        let workflow = generate_github_actions(&GITHUB_ACTIONS_DEFAULT_BACKENDS, true);
        assert!(!workflow.contains("continue-on-error: ${{ matrix.optional }}"));
    }

    #[test]
    fn github_actions_accepts_open_source_backend_aliases() {
        let workflow = generate_with_options(
            "github-actions",
            &CiGenerateOptions {
                backends: vec!["iverilog".into(), "symbiyosys".into(), "next-pnr".into()],
                optional_fail_closed: false,
            },
        )
        .unwrap();

        assert!(workflow.contains("- backend: icarus"));
        assert!(workflow.contains("- backend: sby"));
        assert!(workflow.contains("- backend: nextpnr"));
        assert!(workflow.contains("core lint /tmp/af-icarus-ci --backend icarus"));
        assert!(workflow.contains("backend run nextpnr --target doctor"));
    }

    #[test]
    fn unknown_backend_is_rejected() {
        let err = generate_with_options(
            "github-actions",
            &CiGenerateOptions {
                backends: vec!["unsupported".into()],
                optional_fail_closed: false,
            },
        )
        .unwrap_err();
        assert_eq!(err.code(), "AF_CI_BACKEND_UNSUPPORTED");
        assert!(err
            .to_string()
            .contains("unsupported CI backend `unsupported`"));
    }
}
